### ISSUE TITLE
2.12 release notes

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#101]
Let's start fleshing out the notes based on the release-notes label. Can everyone pick a topic they care about and write a paragraph? Let's use this ticket to coordinate.

**Comment by SethTisue** [comment]
I put a bunch of notes-towards-notes at https://github.com/scala/make-release-notes/issues/202

**Comment by szeiger** [comment]
## sbt-based build

The old ant-based build system has been removed from the main Scala repository in favor of an sbt-based build. This makes it easier to get started hacking on the compiler and standard library. All you need on your machine is JDK 8 and sbt - no ant, no environment variables to set, no shell scripts to run. You can build, use, test and publish Scala like any other sbt-based project.

## scala-java8-compat

The [Java 8 compatibility module for Scala](https://github.com/scala/scala-java8-compat) has received an overhaul for Scala 2.12. Even though interoperability of Java 8 SAMs and Scala functions is now baked into the language, this module provides additional convenience for working with Java 8 SAMs. Java 8 streams support was also added during the development cycle of Scala 2.12. Releases are available for both, Scala 2.11 and Scala 2.12.

**Comment by adriaanm** [comment]
Moving to https://github.com/scala/make-release-notes/issues/202
