### ISSUE TITLE
sbt-republish can't be found anymore

### ISSUE THREAD

**Issue by kiritsuku** [scala/scala-dev#104]
All builds since this one are broken: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2277/console

Error message:

```
[sbt-republish] [info] Wrote /home/jenkins/workspace/scala-2.11.x-integrate-ide/target/zinc/target-0.9.1/project-builds/sbt-republish-a28809b70a2479754a8b71f9062df6108267d9fc/compiler-interface-precompiled/target/compiler-interface-precompiled-0.13.8-on-2.11.9-b2920ad-SNAPSHOT-for-IDE-SNAPSHOT.pom
[sbt-republish] [warn]  [NOT FOUND  ] org.scala-sbt#compiler-interface;0.13.8-dbuildx11d448dccd5e5a7485997426650d238161e6b77e!compiler-interface.jar (0ms)
[sbt-republish] [warn] ==== ivy-build-local: tried
[sbt-republish] [warn]   /home/jenkins/workspace/scala-2.11.x-integrate-ide/target/zinc/target-0.9.1/project-builds/sbt-republish-a28809b70a2479754a8b71f9062df6108267d9fc/.dbuild/local-repo/0/org.scala-sbt/compiler-interface/0.13.8-dbuildx11d448dccd5e5a7485997426650d238161e6b77e/jars/compiler-interface.jar
[sbt-republish] [warn]  [NOT FOUND  ] org.scala-sbt#compiler-interface;0.13.8-dbuildx11d448dccd5e5a7485997426650d238161e6b77e!compiler-interface.jar(src) (0ms)
[sbt-republish] [warn] ==== ivy-build-local: tried
[sbt-republish] [warn]   /home/jenkins/workspace/scala-2.11.x-integrate-ide/target/zinc/target-0.9.1/project-builds/sbt-republish-a28809b70a2479754a8b71f9062df6108267d9fc/.dbuild/local-repo/0/org.scala-sbt/compiler-interface/0.13.8-dbuildx11d448dccd5e5a7485997426650d238161e6b77e/srcs/compiler-interface-sources.jar
[sbt-republish] [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[sbt-republish] [warn]  ::              FAILED DOWNLOADS            ::
[sbt-republish] [warn]  :: ^ see resolution messages for details  ^ ::
[sbt-republish] [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[sbt-republish] [warn]  :: org.scala-sbt#compiler-interface;0.13.8-dbuildx11d448dccd5e5a7485997426650d238161e6b77e!compiler-interface.jar
[sbt-republish] [warn]  :: org.scala-sbt#compiler-interface;0.13.8-dbuildx11d448dccd5e5a7485997426650d238161e6b77e!compiler-interface.jar(src)
[sbt-republish] [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[sbt-republish] sbt.ResolveException: download failed: org.scala-sbt#compiler-interface;0.13.8-dbuildx11d448dccd5e5a7485997426650d238161e6b77e!compiler-interface.jar
[sbt-republish] download failed: org.scala-sbt#compiler-interface;0.13.8-dbuildx11d448dccd5e5a7485997426650d238161e6b77e!compiler-interface.jar(src)
```

@eed3si9n Could this be because of the merge of https://github.com/typesafehub/sbt-republish/pull/13? The build failures started to happen at the same time when this PR was merged. Right now uber-build depends on the master branch of sbt-republish. Do you regularly tag releases of this repo where we can depend on?

**Comment by eed3si9n** [comment]
I might be because it's using sbt 0.13.8? The current master of sbt-republish is for 0.13.11.
I can certainly tag releases.

**Comment by kiritsuku** [comment]
I didn't realize 0.13.11 was already released. Let's see if an update solves the problem.

**Comment by lrytz** [comment]
an update where - can i do something?

**Comment by kiritsuku** [comment]
I already did the update in uber-build but it didn't work. The error message is still the same. Actually, sbt-republish occurs twice in the logs. The first time it works (which is compiled with 0.13.11), the second time it doesn't (which still compiles with 0.13.8). I think the second one is a dependency of sbt and therefore needs to be compiled with 0.13.8. On the other side, sbt shouldn't depend on the master branch of sbt-republish, therefore the version shouldn't matter. But I have to verify it.

**Comment by SethTisue** [comment]
@sschaef status on this? is there something we should be doing on our end? we're still seeing failures e.g. https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2316/console (corresponding PR is https://github.com/scala/scala/pull/5061)

**Comment by performantdata** [comment]
Is it OK that you're mixing 0.13.8 with 0.13.11 usage?

**Comment by kiritsuku** [comment]
I do not know. I understand less about that stuff than I would like.

**Comment by SethTisue** [comment]
I'm going to try and solve this in the context of the community build first (it's https://github.com/scala/community-builds/issues/234), then presumably whatever I find there will apply to integrate-ide as well

**Comment by kiritsuku** [comment]
I looked into this once again but after hours of trying I gave up. I think it is best for now when the scala-ide 2.11.x integration is disabled because I don't know how to fix it. I have hopes that I manage to fix the build once sbt/zinc is available and we can depend on that instead of depending on sbt. But I couldn't yet try that out.

**Comment by SethTisue** [comment]
ok, I've submitted https://github.com/scala/scala/pull/5139 on this

**Comment by SethTisue** [comment]
(and it was merged)

**Comment by performantdata** [comment]
LMK, or rebuild scala/scala#5074, when it's installed.

**Comment by SethTisue** [comment]
the integrate-ide jobs no longer exist.
