### ISSUE TITLE
regression: 2.11.8 Scaladoc is missing inheritance diagrams (2.12.0 too)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#105]
so e.g. http://www.scala-lang.org/api/2.11.7/#scala.collection.Seq has a "Type Hierarchy" section at the top with a diagram, but http://www.scala-lang.org/api/2.11.8/#scala.collection.Seq has no such section

(reported by a user (bejeb) on the #scala IRC channel)

**Comment by SethTisue** [comment]
I'll get to this soon. doing 2.12.0-M4 related stuff first

**Comment by som-snytt** [comment]
This happened previously in an RC.

The "learn more" link on the diagram seems to be broken.

Also, http://www.scala-lang.org/api/2.12.0-M4/scala/collection/Seq.html

**Comment by SethTisue** [comment]
still broken in 2.12.0

**Comment by SethTisue** [comment]
there may be clues in https://github.com/scala/scala-jenkins-infra/issues/190

**Comment by SethTisue** [comment]
the diagram stuff got redone for 2.13. example: https://www.scala-lang.org/api/2.13.0-M5/scala/collection/Seq.html
