### ISSUE TITLE
community build status

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#108]
I ran a community build against 2.12.x after merging the flat-classpath-by-default PR (https://github.com/scala/scala/commit/952da60a5be15ef972b521bdaf5e650f7e0a5245)

Logs
- https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/350/consoleFull
- https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/351/consoleFull
- https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/352/consoleFull

Failures: acyclic and ~~shapeless~~ play-twirl
### acyclic

There seems to be a source-incompatibility with utest. We are tracking the master branches for both projects (see https://github.com/scala/community-builds/blob/2.12.x/common.conf#L92-L93). Before diving into details, maybe @lihaoyi will just say "oh, right"?

```
[acyclic] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/acyclic-1d868ca75d00f4a1d93435c88e0dae97cd16c902/src/test/scala/acyclic/TestUtils.scala:62: not found: value intercept
[acyclic] [error]     val ex = intercept[CompilationException]{ make(path) }
[acyclic] [error]              ^
[acyclic] [warn] one warning found
[acyclic] [error] one error found
[acyclic] [error] (test:compileIncremental) Compilation failed
```
### play-twirl

10 failed tests, for example

```
[play-twirl] [info] New twirl parser should
[play-twirl] [info]   succeed for
[play-twirl] [error]     x static.scala.html
[play-twirl] [error]      'Success(Template(,None,(),ArrayBuffer(),ArrayBuffer(),ArrayBuffer(),ArrayBuffer(),ArrayBuffer(Plain(<h1>It works</h1>))),Input())' is incorrect:  (ParserSpec.scala:30)
```

The test succeeds for `case Success(_, rest) if rest.atEnd`. It looks like `rest` is `Input()` in this case.

**Comment by lrytz** [comment]
cc @pvlugter - any idea about the play-twirl test failures?

**Comment by lihaoyi** [comment]
@lrytz oh right, yeah it's a source incompatibility. I don't have time to look now but maybe over the weekend

**Comment by pvlugter** [comment]
@lrytz, sorry, most of this was just copied out of play into a separate repo. Looks like @adriaanm has fixed already by using the same parser instance.

**Comment by SethTisue** [comment]
I'm on this now, it's reached the front of my queue.

**Comment by SethTisue** [comment]
Adriaan's test run with `acyclic` and `play-twirl` pinned: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/354/

**Comment by SethTisue** [comment]
Adriaan's notes on his wip changes to the 2.12 community build: https://github.com/scala/scala/pull/4971#issuecomment-202636451

**Comment by SethTisue** [comment]
superseded by https://github.com/scala/scala-dev/issues/203
