### ISSUE TITLE
Eliminate box-unbox pairs, tuples, *Refs

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#11]
Miguel's code: [UnBoxElider](https://github.com/scala-opt/scala/blob/opt/rebase/src/compiler/scala/tools/nsc/backend/bcode/UnBoxElider.java), [fixpointGivenConsumer](https://github.com/scala-opt/scala/blob/opt/rebase/src/compiler/scala/tools/nsc/backend/bcode/ProdConsAnalyzer.java#L218)

NOTE: benchmark before doing anything. It seems the JVM optimizes *Refs modified in a while loop.

Related:
- eliminate tuples in multi-returns (`val (a, b) = foo()`)
- eliminate *Ref objects for caputred variables after inlining a closure

Also eliminate boxing of values that are discarded: see for exmple [SI-9160](https://issues.scala-lang.org/browse/SI-9160)

**Comment by lrytz** [comment]
IntRef example:

```
def f(a: Array[Int]): Int = {
  var x = 0
  a.foreach(y => x += y)
  x
}
```

**Comment by lrytz** [comment]
Box-Unbox example below. Specialization fixes it for the common `Function` case, but using a higher-arity, non-specialized function also incurs boxing. Also, mixing primitve and reference types prevents specialization (`(s: String) => s.length`).

```
scala> abstract class BoxingFun[T] { def f(x: T): T }
scala> class KKK {
  def foo = {
    val fun = new BoxingFun[Int] { def f(x: Int) = x + 10 }
    fun.f(1)
  }
}
scala> :javap KKK
  public int foo();
        10: iconst_1
        11: invokestatic  #36   // boxToInteger:(I)Ljava/lang/Integer;
        14: invokevirtual #40   // $read$$iw$$iw$BoxingFun.f:(Ljava/lang/Object;)Ljava/lang/Object;
        17: invokestatic  #44   // unboxToInt:(Ljava/lang/Object;)I
```

**Comment by lrytz** [comment]
Similar to box-unbox paris, also eliminate value class instantiation and value extraction pairs.

```
class A(val x: Int) extends AnyVal
class T {
  def f(n: A) = {
    val f = (a: A) => a
    f(n)
  }
}
```

produces (`cfr-decompiler`)

```
    public int f(int n) {
        A a = new A(n);
        return new A(a.x()).x();
    }
```

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/4858 / https://github.com/scala/scala/commit/29d772d0655a3a5af79c3d8eca91bb33a82c7194
