### ISSUE TITLE
Synchronized methods in traits should use ACC_SYNCHRONIZED

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#110]
``` scala
trait T {
  def foo = synchronized(toString) // translated to monitorenter/exit
}
class C {
  def foo = synchronized(toString) // translated to ACC_SYNCHRONIZED
}
```

**Comment by dragos** [comment]
So the title should be "use ACC_SYNCHRONIZED", right?

**Comment by retronym** [comment]
Ack! You are right.

**Comment by retronym** [comment]
Turns out this isn't legal JVM-ese.

> Methods of interfaces may have any of the flags in Table 4.6-A set except ACC_PROTECTED, ACC_FINAL, ACC_SYNCHRONIZED, and ACC_NATIVE
