### ISSUE TITLE
refine classpath implementation?

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#114]
Flat classpaths enabled by default in M4 by scala/scala#5057 (introduced by scala/scala#4176)

**Comment by lrytz** [comment]
i reviewed the details of the flat classpath implementation while working on the PR that enables it by default. i clened up a few minor things, other than that it looks very good. so i think there's nothing to do here.

the one thing we should do is remove the old implementation, i'm in favor of doing that for m5.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/5112
