### ISSUE TITLE
scour JIRA for bugs that must be fixed in last milestone

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#116]

**Comment by szeiger** [comment]
Does "last milestone" refer to M5 or RC1? Or the ominous M6 that's listed in JIRA?

**Comment by adriaanm** [comment]
M5 aka RC0. Please delete M6 on jira :)

**Comment by szeiger** [comment]
I have no idea how to do that and didn't find anything useful in the JIRA manual. But I don't see anything to edit the project in JIRA, so I probably lack the required rights anyway.

**Comment by SethTisue** [comment]
I deleted M6 on Jira, via https://issues.scala-lang.org/plugins/servlet/project-config/SI/versions.

I also added user szeiger to the jira-administrators group, which hopefully will resolve any future permissions issues (or give you the power to resolve them yourself).

**Comment by szeiger** [comment]
Rescheduled some tickets from RC1 to M5. Next up: Look through tickets with assignee but no target milestone, and finally untriaged tickets.

**Comment by szeiger** [comment]
@SethTisue Thanks, I have access to the version configuration now.

**Comment by adriaanm** [comment]
Also start thinking about which issues should _not_ be fixed in M5. The main contentious issues I can think of are the fields & lambdalift rework, and some cleanup in the REPL to set the scene for better spark support. Those are mostly polish & robustness, but they get a bit close to feature work.

To me, M5 is not quite an RC, but close. The difference is we're still willing to risk regressions for important but non-blocker bugs. (For example, a very nice to have improvement that breaks binary compatibility, so we do it now or in 2.13...) For RC1, regression risk must be really low for fixes to go in, and ideally we'd avoid binary incompatibilities as a metric. In any case, we should turn on MIMA after M5, and maybe even already for M4 to at least get a heads up when we break stuff.

**Comment by szeiger** [comment]
Rescheduled some assigned tickets. Still have to look at the untriaged ones.

**Comment by szeiger** [comment]
Went back 3 years in the "untriaged" tickets and found a handful of candidates that would have to go into M5 if we want to do them in 2.12.

**Comment by lrytz** [comment]
@szeiger there are [100+ tickets with fix-version 2.12.0-M4](https://issues.scala-lang.org/browse/SI-9607?filter=13303&jql=project%20%3D%20SI%20AND%20status%20%3D%20Open%20AND%20fixVersion%20%3D%20%22Scala%202.12.0-M4%22) in JIRA, did you look a these? i guess you caught most of them when you say "Went back 3 years in the untriaged tickets". Question is: what should we do with their fix-version, can we bulk-assign to "Backlog"?

**Comment by szeiger** [comment]
I did not check M4 tickets. By untriaged I meant ones without a fix date or assignee.

**Comment by szeiger** [comment]
I'll check if they are still current or if there's anything that should be moved to M5

**Comment by szeiger** [comment]
Only two dozen without an assignee. I rescheduled them. Got partway through triaging the assigned ones but someone beat me to it and bulk-updated them halfway through :-)

**Comment by lrytz** [comment]
@szeiger I still see 73 open issues with fixVersion M4: https://issues.scala-lang.org/browse/SI-8849?jql=project%20%3D%20SI%20AND%20status%20%3D%20Open%20AND%20fixVersion%20%3D%20%22Scala%202.12.0-M4%22 - should we move them to M5?

**Comment by szeiger** [comment]
@lrytz Huh, strange, the search came up empty while I was working on those tickets so I assumed someone else updated them. Must have been a JIRA issue. I'll get back to those today.

**Comment by szeiger** [comment]
All moved to M5. I didn't spot any ticket with a more obvious target.
