### ISSUE TITLE
Peephole optimization: eliminate push-pop

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#12]
Useful for example after dead-store-elimination, which introduces drops.

Miguel's code: [PushPopCollapser](https://github.com/scala-opt/scala/blob/opt/rebase/src/compiler/scala/tools/nsc/backend/bcode/PushPopCollapser.java)

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/4858 / https://github.com/scala/scala/commit/29d772d0655a3a5af79c3d8eca91bb33a82c7194
