### ISSUE TITLE
Fix code comments mentioning implementation classes

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#127]
Some of this is done in https://github.com/scala/scala/pull/5082.

For the rest, search `src/` for comments mentioning "implclass", "impl class" or "implementation class" and update them.

Examples:
- https://github.com/scala/scala/blob/3c466670d2526f4a1ff77e005fbc5b32cc31f52f/src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala#L161
- https://github.com/scala/scala/blob/3c466670d2526f4a1ff77e005fbc5b32cc31f52f/src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala#L293
- https://github.com/scala/scala/blob/3c466670d2526f4a1ff77e005fbc5b32cc31f52f/src/compiler/scala/tools/nsc/transform/Mixin.scala#L37 and the rest of Mixin.scala

**Comment by dwijnand** [comment]
Let's call this notabug.
