### ISSUE TITLE
Type propagation analysis

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#13]
Allows inlining non-final methods when the receiver is precisely known.

Miguel's code: [TypeFlowAnalysis](https://github.com/scala-opt/scala/blob/opt/rebase/src/compiler/scala/tools/nsc/backend/icode/analysis/TypeFlowAnalysis.scala)

**Comment by lrytz** [comment]
Note that the following already works without type analysis

``` scala
class C { 
  @inline def f = 0
}
final class D extends C
class Test {
  def t(d: D) = d.f
}
```

Code generation emits the invocation `d.f` as `INVOKEVIRTUAL D.f`, even though `f` is declared in class `C`. The inliner already makes use of the more specific receiver type that is available.

However, there are cases where it helps to know if the receiver type is precise or not, which this doesn't give you:

``` scala
class A { def f = 1 }
def test = (new A).f
```

**Comment by lrytz** [comment]
The analysis itself is implemented in https://github.com/scala/scala/commit/e4319789ea6d1a4e958d383619cf7e51338bfde2, but we still need to make use of it for inlining.

**Comment by lrytz** [comment]
done in https://github.com/scala/scala/pull/7133
