### ISSUE TITLE
get IDE integration running again on 2.11

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#132]
The first page of https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/ is 99% red :-/

**Comment by SethTisue** [comment]
basically a dupe of https://github.com/scala/scala-dev/issues/104. @sschaef, I suggest you just change the integration script to use an older revision of sbt-republish; I didn't get to the end of my investigation of what a better fix might be.
