### ISSUE TITLE
Scabot isn't starting PR validation jobs on Jenkins

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#134]
so e.g. at https://github.com/scala/scala/pull/5102 even `/rebuild` isn't resulting in any jobs showing up at https://scala-ci.typesafe.com

**Comment by SethTisue** [comment]
there are multiple wedged validate-main jobs at https://scala-ci.typesafe.com/job/scala-2.11.x-validate-main/ that don't respond to the abort button

**Comment by adriaanm** [comment]
From the scabot logs:

```
[ERROR] [04/20/2016 19:43:59.248] [application-akka.actor.default-dispatcher-33213] 
[akka://application/user/github/scala-scala/5102] 
FAILED synchBuildStatuses(CombiCommitStatus(pending,b1f3e7acc3cc3f5ceca51bb8192a087265331cb3,
List(CommitStatus(pending,Some(validate-main),Some([?] Pending. ),Some())),1)):
 spray.httpx.PipelineException: Object is missing required member 'building'
```

**Comment by SethTisue** [comment]
ah, that looks like an easy fix. (but I won't have time today, can tackle tomorrow)

**Comment by SethTisue** [comment]
@adriaanm I guess you fixed this?

**Comment by adriaanm** [comment]
i think it only happens when there's a problem on jenkins master (disk space low -- i fixed that)

**Comment by SethTisue** [comment]
optimistically closing then
