### ISSUE TITLE
rename optimizer compiler flags

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#137]
remove the `Y`s in `-Yopt`, `-Yopt-warnings`, maybe not in `-Yopt-inline-heuristics`, `-Yopt-trace`

**Comment by lrytz** [comment]
also provide a new option extends the current `l:project`. provably a list of white-listed packages. a by-library option would be useful, but that's more disruptive (how to refer name a library on the command-line? how to know in the backend what library a class belongs to?)

**Comment by lrytz** [comment]
also check https://github.com/scala/scala-dev/issues/31

**Comment by dwijnand** [comment]
Can be closed with https://github.com/scala/scala/pull/5189 merged. (I was just in the neighbourhood)
