### ISSUE TITLE
Closure inlining / elimination

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#14]
After inlining a higer-order function, inline the closure body. Enables further optimizations such as #11.

After that it would be nice to avoid emitting unnecessary closure classes. Note that with `InDy+LambdaMetaFactory`, we don't actually emit closure classes anymore, so it's simply a matter of removing the indy call if the closure doesn't escape / becomes unused.

**Comment by lrytz** [comment]
partly implemented in https://github.com/scala/scala/pull/4552. removing the closure allocation (indy invocation) will be part of a different optimization (probably push-pop elimination, just consider the indy call as side-effect-free)

**Comment by lrytz** [comment]
elimination of unused closure allocations implemented in https://github.com/scala/scala/pull/4858 / https://github.com/scala/scala/commit/29d772d0655a3a5af79c3d8eca91bb33a82c7194
