### ISSUE TITLE
inliner picks the wrong default method

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#140]
```
trait T {
  @inline def f = 0
}

trait U extends T {
  @inline override def f = 1
}

trait V extends T {
  def m = 0
}

final class A extends V with U {
  override def m = super[V].m
}

object Test {
  def main(args: Array[String]): Unit = {
    println((new A).f)
  }
}
```

```
$ qsc Test.scala && qs Test && qsc -Yopt:l:classpath Test.scala && qs Test
1
0
```

See https://github.com/scala/scala/blob/93f209dd65d5c05fc2cb61916a850940499c9261/src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala#L131-L167 - just picks the first match it finds in parents.

We need to implement "maximally-specific superinterface method" (https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.3).

**Comment by lrytz** [comment]
the example is a bit convoluted because the backend uses `erasure.minimizeParents` to get a minimal list of interfaces. some interfaces will be added back due to super calls during code gen.

**Comment by sjrd** [comment]
FYI: [the Scala.js implementation](https://github.com/scala-js/scala-js/blob/v0.6.8/tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala#L362)

**Comment by lrytz** [comment]
thanks!

**Comment by lrytz** [comment]
@sjrd re the comment in the scala-js source https://github.com/scala-js/scala-js/blob/v0.6.8/tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala#L383-L389

this is actually specified. note that [method _resolution_](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.3) picks one trait method at random if there is not maximally-specific one. but afterwards, method _selection_ fails, the [spec of `invokevirtual` / `invokeinterface`](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html#jvms-6.5.invokevirtual) explicitly says:

> if step 3 of the lookup procedure determines there are multiple maximally-specific methods in the superinterfaces of C that match the resolved method's name and descriptor and are not abstract, invokevirtual throws an IncompatibleClassChangeError

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/5140
