### ISSUE TITLE
compiler option for fine-grained control over bytecode sources for inlining

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#148]
the current `opt:l:none` / `default` / `method` / `project` / `classpath` and `-opt:inline-project` / `inline-global` are too coarse-grained:
- `l:none` / `l:default` / `l:method` are probably ok
- `l:method` could include inlining of nested methods
- `l:project` / `inline-project` is the main problem, it has very limited practical use
  - it basically means "inline from compilation units only", which can be surprising under incremental compilation
  - "project" basically assumes a project is compiled in one single module
- `l:classpath` is ok to have; it should probably be renamed `l:global`
- what we really need is a way to specify what classpath elements to inline from
  - only within the same source file
  - any source file - not recommended, as this changes with incremental compilation
  - specific classpath elements (folders, jars)

for specifying folders / jars, we could implement some matching, e.g., `*akka-actor*.jar`, or `*target/scala-*/classes`.

we'd need to provide some sbt examples how to pass output directories (own module, other modules) and dependency jars to this new option.

**Comment by lrytz** [comment]
@scala/team-core-scala comments / ideas welcome

**Comment by szeiger** [comment]
Instead of files that are safe for inlining we could use packages, like in Java 9 modules.

**Comment by lrytz** [comment]
Yes, using packages is probably more sane than talking about jars. It would certainly be simpler to implement.

**Comment by adriaanm** [comment]
Maybe we could start with an option to opt-in to inlining from a package (and its subpackages). E.g., "scala".

**Comment by lrytz** [comment]
Possibly an include and an exclude list, also look at https://git-scm.com/docs/gitignore for inspiration

**Comment by szeiger** [comment]
My gitignore implementation in Scala: https://github.com/szeiger/ornate/blob/master/core/src/main/scala/com/novocode/ornate/FileMatcher.scala

**Comment by dwijnand** [comment]
Also look at https://github.com/sjl/friendly-find/blob/v1.0.1/ffind#L167-L216 for an inspiring rant about gitignore :P

**Comment by szeiger** [comment]
I didn't find the rules in the git documentation hard to understand but I'll leave it to others to judge whether my implementation matches their own (or git's) understanding of the rules :-)

One additional feature that I would have liked is to include selected files / subdirectories of excluded directories but this would require a more complex execution engine.

**Comment by lrytz** [comment]
Another angle: instead of a long list at the command line, it should be possible to pass the include/exclude list as a file

**Comment by lrytz** [comment]
Playing around for a bit, I think we can do something a bit simpler than gitignore. Proposal: the syntax consists of
  - slices of qualified class names: `List`, `scala.collection.List`, `collection.mutable`, etc
  - `*`: longest match of identifier parts (not `.`)
  - `**`: longest match of anything
  - leading `!` to make a rule excluding

Examples

|                       |                                                                           |
| --------------------- | ------------------------------------------------------------------------- |
| `*`                   | classes in the empty package                                              |
| `scala.*`             | classes in package scala, including the package object (`scala.package$`) |
| `**`                  | any class                                                                 |
| `scala.collection.**` | classes in package scala.collection, or any sub-package                   |
| `com.corp.**.util.*`  | classes in a util package below com.corp, including com.corp.util.Foo     |
| `**.Util`             | classes named Util in any package, including `_root_.Util`                |
| `**.*Util*`           | classes containing Util                                                   |

There's a special case to make `.**.` match `.`, so `a.**.b.C` matches `a.b.C`. Similarly, `**.A` matches `A`.

Note that we're talking about classfile names here, so a nested class `foo.C#D` would be `foo.C$D`, a module class is `scala.Predef$`.

More examples:
  - `scalac -opt:l:inline -opt-inlnie-from scala.**,com.corp.**`: white-listing is probably going to be recommended, because
  - Trying to exclude everything from `rt.jar` is not easy! The following is just a start, there are many more packages: `**:!java.**:!javax.**:!jdk.**:!apple.**:!com.apple.**:!com.oracle.**:!com.sun.**:...`
  - `**:!foo.**:foo.util.**`: the last matching rule counts.

Comments?

**Comment by lrytz** [comment]
WIP with a parser for the proposal above: https://github.com/scala/scala/compare/2.12.x...lrytz:inline-from?expand=1
