### ISSUE TITLE
SI-7187 deprecate eta-expansion of arity 0

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#152]
Lukas says in https://github.com/scala/scala/pull/4822#issuecomment-157013973:

```
object Test {
  def foo(): () => String = () => ""
  val f: () => Any = foo

  def main(args: Array[String]): Unit = {
    println(f()) // <function0>
  }
}
```

Should we emit a deprecation in this case?

**Comment by retronym** [comment]
Dup? #179

**Comment by adriaanm** [comment]
see scala/bug#7187

**Comment by adriaanm** [comment]
to decide: how to handle migration/deprecation

**Comment by adriaanm** [comment]
https://github.com/scala/scala/pull/5309

**Comment by adriaanm** [comment]
scala/scala#5327
