### ISSUE TITLE
Consider removal of `test/files/codelib/code.jar` and `test/files/speclib/instrumented.jar`

### ISSUE THREAD

**Issue by szeiger** [scala/scala-dev#154]
`code.jar` may not be necessary anymore. `instrumented.jar` could either be built by sbt on demand or the tests that use it (in `specialized`) ported to the new testing style in `instrumented`. Both JARs' locations are hardcoded in https://github.com/scala/scala-partest and partest will fail to run if they are missing, even if they are not required by the tests.

**Comment by SethTisue** [comment]
current status: code.jar is gone, instrumented.jar is still around

**Comment by SethTisue** [comment]
and it is actually used, `partest specialized` fails without it

**Comment by dwijnand** [comment]
Fixed in [`4070df4` (#6799)](https://github.com/scala/scala/pull/6799/commits/4070df494d749feb7e796750871b2814c46b4ccd)
