### ISSUE TITLE
SI-9871 infer higher-order function argument types from overloaded method if argument types agree (fix source incompat introduced by sammy)

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#157]
Overloaded method with argument of function type  --> ok as long as argument types derived from lub of function types agree:

```
def map(f: Char => A)
def map(f: Char => Char)
```

fails now, but could be made to work (would fix sam breaking overloads, and align with dotty)

**Comment by adriaanm** [comment]
see #125 (dupe) for example: 

```
trait Bijection[A, B] extends (A => B) {
   def andThen[C](g: Bijection[B, C]): Bijection[A, C] = ???
   def compose[T](g: Bijection[T, A]) = g andThen this
}

// <console>:14: error: overloaded method compose needs result type
// def compose[T](g: Bijection[T, A]) = g andThen this
//                                        ^
```

https://github.com/adriaanm/util/commit/78f8eefa3c669e4657a278bba80127f6f610cbdb

**Comment by retronym** [comment]
See also: https://issues.scala-lang.org/browse/SI-9871

**Comment by SethTisue** [comment]
note that scala/scala#5307 doesn't actually make the `trait Bijection` example from #125 compile
