### ISSUE TITLE
repl shouldn't deadlock with lambdas + parallellism

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#161]
This keeps tripping people up. I think we should fix this in RC1. We already have some prior art, such as: 
https://github.com/scala/scala/pull/4349

https://issues.scala-lang.org/browse/SI-9076
https://issues.scala-lang.org/browse/SI-9824

**Comment by DarkDimius** [comment]
As far as I understand the reason, I've fixed in in dotty by making lambdas inside static modules be non static and refer to module itself through `this`. 
https://github.com/lampepfl/dotty/pull/1281/commits/3b0cb481e379ee07ce33d80a1bee5ff67c32eb40

**Comment by adriaanm** [comment]
Thanks!

**Comment by adriaanm** [comment]
dupe of #133
