### ISSUE TITLE
SI-8576 Vector should have SerialVersionUID, and other problems with SI-8549 discovered by the Xcheckinit build

### ISSUE THREAD

**Issue by szeiger** [scala/scala-dev#169]
https://issues.scala-lang.org/browse/SI-8576

**Comment by szeiger** [comment]
https://github.com/scala/scala/blob/2.12.x/test/files/run/t8549.scala

**Comment by szeiger** [comment]
Relevant links:
- http://stackoverflow.com/questions/3876163/how-can-i-keep-xcheckinit-from-interfering-with-the-deserialization-of-scala-ob
- https://docs.oracle.com/javase/7/docs/platform/serialization/spec/serialTOC.html

**Comment by szeiger** [comment]
`-Xcheckinit` breaks completion in the REPL: https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/2643/consoleFull

**Comment by szeiger** [comment]
PR for 2.12: https://github.com/scala/scala/pull/5306 - More in 2.13 (see JIRA)

**Comment by dwijnand** [comment]
Closing in favour of https://github.com/scala/bug/issues/8576.
