### ISSUE TITLE
minimal subproject for publishing only core (library/reflect/compiler)

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#176]
to speed up local development, it would be good to be able to easily only publishLocal the minimal amount of code needed to bootstrap

ideally, i'd be able to do `core/publishLocal`, restart sbt with the right `starr.version` and do e.g., `library/compile`

Speaking of local dev, this is what I have in my local.sbt at the moment:

```
publishArtifact in (Compile, packageDoc) in ThisBuild := false
baseVersionSuffix := s"local-${Process("tools/get-scala-commit-sha").lines.head.substring(0, 7)}"

antStyle := true
```

**Comment by retronym** [comment]
Does `;setupPublishCore;publishLocal` suffice?

**Comment by SethTisue** [comment]
I think it does, and I've opened #568 on the possibility of improving it further
