### ISSUE TITLE
Throw ConcurrentModificationException exception's in scala collections?

### ISSUE THREAD

**Issue by varming** [scala/scala-dev#188]
In [SI-8774](https://issues.scala-lang.org/browse/SI-8774), [scala/scala/#3911](https://github.com/scala/scala/pull/3911), @alextg-github, @Ichoran, @lrytz, @gkossakowski and @retronym discussed the need for throwing exceptions when using an iterator over a collection that has been invalidated by modifications to the collection.

In [scala/scala#5295](https://github.com/scala/scala/pull/5295) (merged in to 2.12.x) I made sure that removing the element last returned from an iterator would not cause a problem for the iterator. This is similar to jdk collections where iterators can implement a remove method. This was a conservative measure to avoid breaking too much code.

Should scala collections implement iterators that notice modifications to the underlying collection and throw an exception if the iterator has been invalidated? Before you answer that question you might want to look at newer APIs for traversing collections such as the streams API in Java8.

**Comment by SethTisue** [comment]
@NthPortal didn't we discuss this elsewhere recently?

**Comment by NthPortal** [comment]
scala/bug#12009

I suggest we close this in favour of that ticket
