### ISSUE TITLE
make module init compliant with the jvm spec

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#194]
Details: https://github.com/lampepfl/dotty/issues/1441

Proposed fix: https://github.com/scala/scala/compare/2.12.x...retronym:topic/module-init

**Comment by retronym** [comment]
Worth considering for 2.12.0 IMO. It will only blow up on Java 9, which we don't claim to support yet, but it would be good to at least have support for running code that we've compiled against JDK8 in JDK9.

**Comment by adriaanm** [comment]
Agreed.

**Comment by DarkDimius** [comment]
@retronym see comment here https://github.com/lampepfl/dotty/issues/1441#issuecomment-237721583 that shows a counterexample to your solution and a possible fix.

**Comment by retronym** [comment]
@DarkDimius Good catch. That is very subtle: we currently set the field after the module's super constructors are called but before the rest of the module's own constructor is called.

Perhaps our safest bet for 2.12.x is to make the static `MODULE$` field non-final in bytecode. We're already subverting its finality by assigning is in the `<init>` rather than `<clinit>`.

In the future, should consider changing the `putfield` to a compare-and-set that enforces that the field is only written once (`ensureAccessible(O.getClass).newInstance()` should not be able to overwrite the field as it can today.

**Comment by adriaanm** [comment]
Since this only blows up on bytecode version 53, which we won't generate for a while, I'd vote for doing nothing for 2.12. Removing the `final` modifier has an impact on the memory model, right?

**Comment by retronym** [comment]
https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.5

The clinit method is called within an initialisation lock that takes care of publishing the field write to other threads

**Comment by retronym** [comment]
But I wasn't aware of version 53, so agree this could be pushed back.

https://bugs.openjdk.java.net/browse/JDK-8148785

**Comment by adriaanm** [comment]
I'm a little uneasy about punting on this because I couldn't find a public commitment to not close this loophole in old classfiles, but I'm more worried about breaking our initialization semantics on current Java.

It's still not clear to me how doing a `putstatic` to a _non-_`final` field in the `<init>` method ensures safe publications. I see that the `<clinit>` method establishes a happens-before relation, but is the same true for the regular constructor, as we can't use the `clinit` method due to cycles?

**Comment by DarkDimius** [comment]
> It's still not clear to me how doing a putstatic to a non-final field in the `<init>` method ensures safe publications.

In our current state `clinit` calls `init` that assigns a `MODULE$` field.
`clinit` is run inside a synchronized block that ensures safe publication.

If you would call a module-class constructor using reflection, this would not be a safe publication, but this should be simply prohibited, ie constructor should check that current value of `MODULE$` field is `null`.

**Comment by adriaanm** [comment]
Ah, thanks for explaining!

**Comment by adriaanm** [comment]
https://github.com/scala/scala/pull/5322
