### ISSUE TITLE
SI-9076 SAM in REPL gives non-termination of Java 8 Stream

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#195]
@DarkDimius said:

> As far as I understand the reason, I've fixed in in dotty by making lambdas inside static modules be non static and refer to module itself through this.  lampepfl/dotty@3b0cb48

**Comment by adriaanm** [comment]
We could also fix this by changing the encoding in the REPL to be like the currently experimental class-based encoding. This has a workaround as well, so not a release blocker.

**Comment by adriaanm** [comment]
See also the analysis at https://github.com/rickynils/scalacheck/issues/290#issuecomment-295964426

**Comment by SethTisue** [comment]
There are a lot of tickets in this area. Besides, https://github.com/scala/bug/issues/9076, there's https://github.com/scala/bug/issues/8119 and https://github.com/scala/bug/issues/9824.

(I personally am not sure, without going back over it, how many "different" issues there actually are here.)

**Comment by SethTisue** [comment]
the best minimal reproducer I know that is 2.12-specific is:

```scala
for (i <- (1 to 100).par) yield i
```

this hangs the 2.12 REPL but not the 2.11 REPL

**Comment by adriaanm** [comment]
I think it makes more sense to tackle this in 2.14.

**Comment by olafurpg** [comment]
Regular programs are also affected, here's a repro that crashes outside the REPL

```scala
object Boom {
  import scala.concurrent._, duration._, ExecutionContext.Implicits.global
  val x = Await.result(Future(1), Duration("1s"))
}
```

The following program does not crash.

```scala
import scala.concurrent._, duration._, ExecutionContext.Implicits.global
object Boom {
  val x = Future(1)
}
object Ok {
  val x = Await.result(Boom.x, Duration("1s"))
}
```

Workaround is to enable `-Ydelambdafy:inline`.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/8748

**Comment by SethTisue** [comment]
🍾
