### ISSUE TITLE
Add thicket support to the tree transformers

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#199]
It is handy for a tree transformers transform a single tree to a thicket of trees. 

We do this in subtly different ways in overrides of `transformStats` in `Fields`, `AddInitBitsTransformer`, `LambdaLift` as well as in `LazyVals.flattenThickets`.

There are a variety of approaches: communicating via back channels of `Map[Symbol, List[Tree]]` or by returning a dummy `Block(trees, EmptyTree)` to encode `Thicket`.

It is pretty subtle to get right with the interaction with the already tricky implementation of `Transformer#transformStats`.

We should refactor these places to use a common scheme. `transformStats` is something of a hot method, so we should be keep efficiency in mind.

**Comment by dwijnand** [comment]
Done in [`7d46e6b` (#8816)](https://github.com/scala/scala/pull/8816/commits/7d46e6b4ce47360817e7639dd7a60325cfd89501), which shipped in 2.12.12/2.13.3.
