### ISSUE TITLE
Prevent code size explosion due to blindly inlining methods marked @inline

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#2]
Currently, every method marked `@inline` is inlined, which can lead to exponential code growth.

We should probably have two kinds of threshold: one for the maximum method size, one for the maximum method growth.

Discussion and further references here: https://github.com/scala/scala/pull/4041#issuecomment-67774217

**Comment by lrytz** [comment]
Done in https://github.com/scala/scala/pull/7133
