### ISSUE TITLE
test/files/run/t8549.scala failing on 2.12.x

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#201]
reported by @milessabin at https://gitter.im/scala/contributors?at=57ae17ea0fd99f7041362ca9

reproduced locally from clean 2.12.x build:

```
 serialization unstable: rO0ABXNyAClzY2FsYS5jb2xsZWN0aW9uLm11dGFibGUuRG91YmxlTGlua2VkTGlzdI73LKsKRr1RAgADTAAEZWxlbXQAEkxqYXZhL2xhbmcvT2JqZWN0O0wABG5leHR0ACtMc2NhbGEvY29sbGVjdGlvbi9tdXRhYmxlL0RvdWJsZUxpbmtlZExpc3Q7TAAEcHJldnEAfgACeHBzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGphdmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAAAXNxAH4AAHNxAH4ABAAAAAJzcQB+AABzcQB+AAQAAAADc3EAfgAAcHEAfgALcQB+AAlxAH4AB3EAfgADcA==
   found: rO0ABXNyAClzY2FsYS5jb2xsZWN0aW9uLm11dGFibGUuRG91YmxlTGlua2VkTGlzdI73LKsKRr1RAgADTAAEZWxlbXQAEkxqYXZhL2xhbmcvT2JqZWN0O0wABG5leHR0AB5Mc2NhbGEvY29sbGVjdGlvbi9tdXRhYmxlL1NlcTtMAARwcmV2cQB+AAJ4cHNyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAAABc3EAfgAAc3EAfgAEAAAAAnNxAH4AAHNxAH4ABAAAAANzcQB+AABwcQB+AAtxAH4ACXEAfgAHcQB+AANw
    at scala.Predef$.assert(Predef.scala:219)
    at Test$.check(t8549.scala:78)
```

**Comment by retronym** [comment]
I think it only fails in "skip locker" mode

**Comment by milessabin** [comment]
What is "skip locker" mode and how would I avoid it (if necessary)?

**Comment by retronym** [comment]
The test assumes that the library was built with the latest compiler, not
Starr. Bootstrapping with publishLocal, as described in the readme, makes
it work. Maybe we should have some way to flag tests that require
bootstrapping and skip them with a warning in the default config.

**Comment by adriaanm** [comment]
with the following local.sbt (first two lines are relevant):

```
publishArtifact in (Compile, packageDoc) in ThisBuild := false
baseVersionSuffix := s"local-${Process("tools/get-scala-commit-sha").lines.head.substring(0, 7)}"
testOptions in IntegrationTest in LocalProject("test") ++= Seq(Tests.Argument("--show-log"), Tests.Argument("--show-diff"))

antStyle := true

```

bootstrapping is convenient as follows (assuming `git config core.abbrev 7`):

```
sbt publishLocal ; sbt -Dstarr.version=2.12.0-local-$(git rev-parse --short HEAD)
```

**Comment by milessabin** [comment]
@adriaanm's recipe works for me, but I'd like to push back on things being left at that.

Presumably this process has to be repeated each time a fresh commit is added? It doesn't add a huge amount of time if you're running all of `partest run` anyway, but it's an additional manual step that has to be known about and taken before someone working on the compiler can get the tests to pass.

This is raising the barrier to contribution (a little) again, and I think it's unfortunate to be taking a step backwards after so much forward progress has been made.

I think @retronym's suggestion of flagging tests as requiring bootstrapping and have the build skip them with a warning (and a pointer to instructions on how to bootstrap) is a good one.

**Comment by retronym** [comment]
Another alternative would be to more aggressively update STARR, rather than waiting for the next RC release. We could have a nightly build that fails when we get into this pickle, and the resolution would be to either immediately publish a release and update STARR, or to move the tests to `test/pending`. The problem with disabling tests is making sure they are re-enabled.

**Comment by adriaanm** [comment]
> Presumably this process has to be repeated each time a fresh commit is added?

No, this is only needed when something fundamental changes about how we generate bytecode or when we make a binary incompatible change. This is something that should only happen once in a while during the milestone cycle. After that, it is no longer allowed.

**Comment by milessabin** [comment]
> This is something that should only happen once in a while during the milestone cycle.

Understood. Am I right in thinking that anyone starting from fresh will hit this for a while? What has to happen for that to not to be the case? Publication of a new STARR? Is there any reason not to do that straight away?

**Comment by adriaanm** [comment]
Yes, until RC1 is out. That should be soon, though! 8 PRs to go, hopefully we can stage it in a week. In the mean time, you can add the following resolver and set starr.version to `2.12.0-804133f-SNAPSHOT` in versions.properties (every commit is built and published by the CI).

```
resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
```

**Comment by milessabin** [comment]
Why not add that to `build.sbt`? Ideally at the same time (or immediately after) the necessitating change is made?

I agree this is a little thing, but it's little things like this which make it harder for new people to start contributing.

**Comment by lrytz** [comment]
FTR, I agree with Miles that we should try to avoid these failures if possible. I recently did a similar cleanup (of failures that I introduced myself) for the JUnit test: https://github.com/scala/scala/commit/64fdae87975f019d3821ca943852df37d50db801

**Comment by retronym** [comment]
The risk of adding dev conveniences to the build is that we accidentally lean on them in a release or CI build. That doesn't mean we can't add them, but we have to be careful to about how we do it.

In this case, we could conditionally add that resolver based on the `scalaVersion` being of the shape `\d+.\d+.\d+-\w+-SNAPSHOT`.

**Comment by milessabin** [comment]
Why does the CI-build succeed but a local build fail?

**Comment by retronym** [comment]
It bootstraps with https://github.com/scala/scala/blob/2.12.x/scripts/jobs/validate/test

**Comment by milessabin** [comment]
And because it bootstraps the updated STARR isn't necessary?

**Comment by lrytz** [comment]
the ci build runs in two stages (separate jobs on jenkins)
- publish-core, which pushes a build (built with STARR) to `scala-pr-validation-snapshots`
- validate-test, which builds everything from source again using the previously published version as STARR, and then runs the tests

**Comment by milessabin** [comment]
Got it. Thanks.

**Comment by milessabin** [comment]
Could we smooth this out with a `bumpStarr` SBT task which publishes a snapshot and updates and commits `versions.properties`?

Presumably this is a task which could only be successfully run by someone with signing/publishing privileges for org.scala-lang.

**Comment by dwijnand** [comment]
@retronym 

> In this case, we could conditionally add that resolver based on the scalaVersion being of the shape \d+.\d+.\d+-\w+-SNAPSHOT.

BTW there's existing art in sbt for these things in (IIRC) CrossVersionUtils. Just saying it would be good to converge rather than duplicate.
