### ISSUE TITLE
avoid unneeded boxing of argument to `synchronized` primitive method?

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#209]
... perhaps by special-casing synchronized, even though that complicates erasure for performance, not correctness

https://github.com/adriaanm/scala/tree/poly-synch

**Comment by smarter** [comment]
See also https://github.com/lampepfl/dotty/issues/505

**Comment by lrytz** [comment]
fixed in https://github.com/scala/scala/pull/5294/commits/92d1af11b04b4f7c8aafd4ff911bf747eb1029aa, no? cc @adriaanm

**Comment by adriaanm** [comment]
Yes indeed
