### ISSUE TITLE
Trait super accessors inherit all annotations

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#213]
Test.java:

``` java
public @interface Test { }
```

T.scala

``` scala
trait T { @Test def foo = 0 }
```

gives

```
public abstract interface T {

...

  public static synthetic foo$(LT;)I
    // parameter final synthetic  $this
  @LTest;()

...

  public default foo()I
  @LTest;()

...

}
```

Imagine `@Test` being JUnit's annotation. It should probably not be on the forwarder method. We should add a way to control this behavior.

**Comment by adriaanm** [comment]
In https://github.com/scala/scala/pull/5570, @retronym proposes we drop all annotations from the static forwarders. They should be on the default method in the interface (and on the mixed in metho in subclasses). Right?

**Comment by lrytz** [comment]
I think the inliner relies on static accessors inheriting `@inline`, so inlining of super calls might break.

**Comment by lrytz** [comment]
Turns out it doesn't: https://github.com/scala/scala/pull/5570#issuecomment-264800855
