### ISSUE TITLE
upgrade 2.12 build from sbt 0.13.11 to 0.13.12

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#218]
I tried but when I run `sbt update` (with either 0.13.12 or 0.13.13-M1) I get:

```
java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.scala-lang#scala-library;2.12.0-RC1
    at org.apache.ivy.core.resolve.IvyNode.getArtifacts(IvyNode.java:809)
```

reproducible every time.

**Comment by SethTisue** [comment]
I'm talking w/ @eed3si9n and @dwijnand about it, will summarize here

**Comment by SethTisue** [comment]
@dwijnand tried 0.13 head, same error.

the relevant ticket is probably https://github.com/sbt/sbt/issues/2015

**Comment by dwijnand** [comment]
For the history books, the current HEAD of 0.13 (preparing for the release of 0.13.13) is https://github.com/sbt/sbt/commit/0a13ac1231715fbe7548787be46961eb83cb1dd1

**Comment by eed3si9n** [comment]
scala/scala probably won't need the recently-added meditation that forces `scalaVersion` during build:

``` scala
    ivyScala := { ivyScala.value map {_.copy(overrideScalaVersion = sbtPlugin.value)} }
```

**Comment by SethTisue** [comment]
closing now that we have the PR. thanks Dale!
