### ISSUE TITLE
Write an optimizer FAQ

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#22]
Random points (need cleanup)
- What optimizations are implemented? What do they do?
- Why should I use the optimizer (isn't the JVMs good enough)?
- What options should I use?
- What happens to binary compatibility?
- When can I inline from the classpath?
- What are the limitations?

**Comment by lrytz** [comment]
started in https://github.com/scala-opt/scala/wiki/Scala-2.12-Bytecode-Optimizer

**Comment by SethTisue** [comment]
retargeted for 2.12.x

**Comment by SethTisue** [comment]
this happened: https://developer.lightbend.com/blog/2018-11-01-the-scala-2.12-2.13-inliner-and-optimizer/index.html

it would be nice if this information also found a more permanent home on docs.scala-lang.org. regardless, closing.
