### ISSUE TITLE
Crash with supercall to Java interface

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#224]
Related to https://github.com/scala/scala-dev/issues/143 - possibly regressed in https://github.com/scala/scala/pull/5377 (just a guess):

T.java

``` java
interface T { default int f() { return 1; } }
```

Test.scala

``` scala
trait U extends T
class C extends U { def t = super.f }
```

compiling `scalac Test.scala T.java`

```
java.lang.AssertionError: assertion failed:
  cannot invokespecial T.f, the interface is not a direct parent.
```

For some reason we don't catch this case in SuperAccessors.

**Comment by lrytz** [comment]
Fixed in my branch for https://github.com/scala/scala-dev/issues/228 that eliminates static forwarders (https://github.com/scala/scala/compare/2.12.0...lrytz:traitSuperAccessors?expand=1)

**Comment by adriaanm** [comment]
https://github.com/scala/scala/pull/5429
