### ISSUE TITLE
regression involving DelayedInit

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#229]
``` scala
class Broken {
  def is(ee: AnyRef) = {
    new Delayed {
      ee
    }
  }
}

class Delayed extends DelayedInit {
  def delayedInit(x: => Unit): Unit = ()
}

```

```
java.util.NoSuchElementException: key not found: value ee$1
    at scala.collection.MapLike.default(MapLike.scala:232)
    at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
    at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$locals$.load(BCodeSkelBuilder.scala:392)
    at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:352)
    at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:82)
```

Minimized from a compiler crash compiling the play test suite. Specs 2 uses `DelayedInit` in part of its DSL.

**Comment by retronym** [comment]
Workaround would be to rewrite the above as:

``` scala
class Workaround {
  def is(ee: AnyRef) = {
    new MyDelayed(ee)

  }
  class MyDelayed(ee: AnyRef) extends Delayed
}

class Delayed extends DelayedInit {
  def delayedInit(x: => Unit): Unit = ()
}

```

**Comment by retronym** [comment]
Hmm, this example actually crashes in 2.11.8 as well. I need to figure out what aspect of the original source in the Play tests leads to something that used to compile but now crashes.

**Comment by retronym** [comment]
This variation compiled without crashing in 2.11.8:

``` scala
class Broken {
  def test = {
    val capture = ""
    () => {
      final class X extends DelayedInit {
        capture.toString
        def delayedInit(body: => Unit) = ()
      }
    }
  }
}

```

**Comment by retronym** [comment]
I think that when we switched on `delambdafy:method` as the default, we've shifted this example from into known bugs of the `DelayedInit` transform.

I've prototyped an [change](https://github.com/retronym/scala/tree/ticket/SD-229) to `Constructors` to many examples work again. But, as shown in the `pending` test and discussed in the commit comment, we might find a more robust fix by adjusting `LambdaLift` instead.

I'm a bit torn about what severity we give to this bug. Even though we've deprecated `DelayedInit` usage (other than in the restricted use case of `App`), it has relatively widespread usage via part of the in the Specs2 DSL.

**Comment by SethTisue** [comment]
fyi @etorreborre

**Comment by som-snytt** [comment]
We mere observers don't appreciate the difficulty of supporting this feature. I wanted it the other day, and I often rely on the special qualities of `App`. I just remembered, my twist was that I wanted to override `args` in `App`, which is deprecated now. In the abstract, these seem like edge use cases, but once one fully embraces the feature, you start to see `DelayedInit` everywhere.

Like the old saw about the hammer, once you have `DelayedInit`, you see all init as delayed. Apologies for mixed metaphors, saw and hammer.

**Comment by etorreborre** [comment]
Thanks for the ping @SethTisue.

**Comment by retronym** [comment]
@lrytz I was playing with this patch to fix this in `LambdaLift`:

https://github.com/retronym/scala/tree/topic/SD-229b

My first attempt, which was more successful, was:

https://github.com/retronym/scala/tree/ticket/SD-229

**Comment by adriaanm** [comment]
https://github.com/scala/scala/pull/5423
