### ISSUE TITLE
provide hooks for CI environment outside of version control

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#236]
... since they are subject to forces outside of version control 

use case: being able to bump the EC2 instance type to get more RAM/CPU without breaking all pending PRs because partest runs out of ram in this new environment. We should not have to depend on everyone rebasing on our latest fix to counter-act these changes, so that means that e.g., concurrency and Java heap sizing should be configurable using environment vars?

**Comment by adriaanm** [comment]
For now, I've reverted my desperate change to bump our EC2 instance type as it had these unexpected consequences. We first need to prepare for those with something along the lines of scala/scala#5434 or perhaps more generally hooks in our CI scripts so that we can control them outside of git.

**Comment by dwijnand** [comment]
Seems hard and at the same time not a problem these days - Seth Tisue.

**Comment by SethTisue** [comment]
My name is Seth Tisue and I endorse this message.
