### ISSUE TITLE
Collect collections gotchas.

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#245]
Let's build a collection of collection usage patterns that surprised users, to inform the renovations in 2.13.

**Comment by adriaanm** [comment]
https://news.ycombinator.com/item?id=12730239

**Comment by dwijnand** [comment]
I believe the partial methods are a gotcha that would be nice to improve: eg. `Option.get`, `Seq.head`, `Seq.reduce`.

A good naming convention to alert the reader might be sufficient (in Ruby it's a `!` suffix, in Scala I've generally seen the methods prefixed with `unsafe`, so perhaps `unsafeGet`, `unsafeHead`, etc)

**Comment by lrytz** [comment]
A related concern: `apply` vs `get` is often confusing in maps, also because `get` is the partial method in `Option`. But it would be a loss if `Map[A, B]` was no longer an `A => B`.

**Comment by SethTisue** [comment]
this ship has sailed

**Comment by dwijnand** [comment]
How do we avoid that in the future?  I tend to avoid nudging tickets if I see they're in the intended milestone, but maybe it's better to?
