### ISSUE TITLE
Scalatest compilation time regression in 2.12

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#246]
Report by @cheeseng about 2.12.0-RC2:

> @adriaanm @retronym @SethTisue @bvenners just want to report the latest finding, using Scala 2.12.0-RC2, it seems the performance issue is still there, here's the result of sbt test:compile using our 3.1.x branch:
> 
> 2.11.8 - 602 seconds
> 2.12.0-RC2 - 1520 seconds
> 
> The difference probably is too much for us to swallow. :)

**Comment by retronym** [comment]
Can you try with sbt 0.13.3-RC3?

**Comment by adriaanm** [comment]
I can reproduce on my machine with roughly the same timings. By disabling val signature inference (using `-Xsource:2.11`), I got the compile time down to 950s: https://github.com/scalatest/scalatest/compare/3.0.x...adriaanm:3.0.x

**Comment by lrytz** [comment]
oh wow, the change in val sig infer can be that heavy..?

**Comment by milessabin** [comment]
More data points from shapeless (SBT 0.13.13-RC in all cases),

```
With 2.11.8
cold: compile: 33s    test:compile: 121s
 hot: compile: 13s    test:compile: 101s

With 2.12.0-R2
cold: compile: 34s    test:compile: 129s
 hot: compile: 17s    test:compile: 207s <==

With 2.12.0-RC2 and -Xsource:2.11
cold: compile: 38s    test:compile: 131s
 hot: compile: 13s    test:compile: 113s
```

The cold times are pretty much consistent between 2.11.8 and 2.12.0-RC2, but the hot test:compile times blow out for 2.12.0-RC2 without -Xsource:2.11.

**Comment by retronym** [comment]
@milessabin Could you please post a gist of how you came to the 207s number? I tried:

```
% sbt -Dsbt.profile=2.12.x ++2.12.0-RC2  test:compile test:clean update test:compile  test:clean update test:compile
```

with https://github.com/milessabin/shapeless/commit/d0a8f512ea0bff2a7d686e4644088da662048f2

But didn't observe the `test:compile` tasks slowing down.

**Comment by adriaanm** [comment]
I'll try to figure out what's going on today. (With the valsiginfer overhead)

**Comment by milessabin** [comment]
@retronym hmm ... just attempted to reproduce that for you and failed. For reference, this is what I did: https://gist.github.com/milessabin/0ad6b15d2f750754c2bda565828eab14.

**Comment by adriaanm** [comment]
I collected some numbers at https://docs.google.com/spreadsheets/d/1pwwvsuq0qctqxYoJ5EE9b6w8vW_AyrMSzTgn-zGxrnI/edit

(The shas in the sheet refer to https://github.com/scalatest/scalatest/compare/3.0.x...adriaanm:bench?expand=1)

Not sure what to make of this

**Comment by adriaanm** [comment]
The total timings indicate val sig inference has less than 9% overhead in these timings. I think I may have been picking up measurement noise by doing everything in the same sbt session...

**Comment by retronym** [comment]
@adriaanm One optimization that we could (should?) add would be to exclude private vals from valsiginfer.

Scalatest could modify its test source generator to add explicit return types for the most common vals it generates that exercise `valsiginfer`: https://gist.github.com/29d385e14de84e337f7a2f932db5580f

**Comment by retronym** [comment]
@milessabin Incidentally, I believe you are suffering from https://issues.scala-lang.org/browse/SI-6149 in compiling shapeless tests. One solution to this might be to make error string creation disabled by a Context flag, which would be set during `typedImplicit1`. If no successful implicit was actually found, we could then re-typecheck the failed candidate under normal mode to produce the error message.

**Comment by retronym** [comment]
I've taken a look at the bottleneck in `scalatest-test/test:compile`. 

30% of the time in my profile (6 minutes of parser/namer/typer)  is spent creating names:

``` scala
  private var existentialIds = 0
  protected def nextExistentialId() = { existentialIds += 1; existentialIds }
  protected def freshExistentialName(suffix: String) = newTypeName("_" + nextExistentialId() + suffix)
```

As called from `AsSeenFromMap`:

``` scala
    /** Creates an existential representing a type parameter which appears
      *  in the prefix of a ThisType.
      */
    protected def captureThis(pre: Type, clazz: Symbol): Type = {
      capturedParams find (_.owner == clazz) match {
        case Some(p) => p.tpe
        case _       =>
          val qvar = clazz freshExistential nme.SINGLETON_SUFFIX setInfo singletonBounds(pre)
          _capturedParams ::= qvar
          debuglog(s"Captured This(${clazz.fullNameString}) seen from $seenFromPrefix: ${qvar.defString}")
          qvar.tpe
      }
    }
```

This stems from the way that `hashCode` for `Name`, which, I guess for reasons of efficiency computation (or maybe just perceived efficiency) only takes the first, last, and mid characters into account.

The names we're generating (e.g. `_1234.type`) are a pathological case for this, they all land in 10 buckets which get awfully crowded.

I've seen this before but never got around to benchmarking that a better hashcode doesn't slow anything down in "normal" cases. I think the time is nigh for that.

I should note that this is existing 2.11 behaviour, not a perf regression in 2.12.

It would also be worth avoiding generating a globally increasing procession of these names, but rather use a separate counter for each `AsSeenFromMap`, or something similar. This would promote more name recycling.

**Comment by retronym** [comment]
Here's a potential fix for the pathological name table hash distribution: https://github.com/scala/scala/pull/5474

> It improves the compilation time of ScalaTest tests from 487s to 349s (0.71x).

**Comment by DarkDimius** [comment]
Note that Dotty maintains an invariant that we don't have duplicate names in our name-table, which means that we can use reference comparison for equals and default hashcode inherited from `Object`.

**Comment by retronym** [comment]
My first attempt to benchmark this for small programs showed no change (795ms->797ms) for `better-files`, and a 2% slowdown (1645ms -> 1678ms) for `scalap`. However, the results seem a little noiser on my laptop (even with TurboBoost disabled) than i was used to on my desktop where I've done previous benchmarking, so I'm not sure I have enough warmup time or forks to say whether or not that 2% is just noise.

I plan to re-run the benchmarks, and also compare profiles before/after to see is `hashValue` is starting to show up.

**Comment by milessabin** [comment]
@retronym I took a look at [SI-6149](https://issues.scala-lang.org/browse/SI-6149) and it didn't have a significant effect on the inductive implicit benchmarks that I've been working with. That doesn't mean that it's not worth pursuing at all, but the effect is smaller than we might have hoped.

**Comment by SethTisue** [comment]
this seems stale, but reopen if not
