### ISSUE TITLE
Document branching strategy in README

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#247]
Target oldest branch you would like your feature to end up in. We merge forward from older release branches (e.g., 2.11.x) to new ones (e.g. 2.12.x). We also have shorter-lived release branches (e.g. 2.12.0), which are reserved for RC-cycles of major releases. They will be merged into the corresponding .x branch, but not the other way around.

When backporting a fix, make sure to indicate this in the PR title / commit message, so that we can skip this PR when merging forward (by definition of "backport", it'll already be in the target branch of the merge).

**Comment by milessabin** [comment]
Is there any flexibility in this policy?

From my PoV it has been a lot easier to target 2.12.x and then backport rather than the other way around.

**Comment by adriaanm** [comment]
Sure, backporting is fine with me, as long as we agree on a convention to clearly denote those PRs, to make sure we skip them while merging forward.

(This ticket is a draft for the addition to the README, happy to further refine it.)

**Comment by milessabin** [comment]
Perfect ... happy to go with any title/message convention that works for you.

**Comment by adriaanm** [comment]
Sure! This ticket was a draft for the policy doc that should result. I'm
happy for either direction as long as we have a convention to indicate
backports should not be merged forward.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/9283
