### ISSUE TITLE
scala-compiler.jar contains scala-asm jar

### ISSUE THREAD

**Issue by szeiger** [scala/scala-dev#254]
As reported on scala-internals: https://gist.github.com/xuwei-k/95ad69e65975e40cb32530ac04463f91#file-2-12-0-L29

**Comment by szeiger** [comment]
We deliberately put the file there: https://github.com/scala/scala/blob/2.12.x/build.sbt#L396

It's not clear to me why but either I'm having a deja-vu or I investigated the same problem before. The reason why it's not in M5 is that `integrate/bootstrap` back then still used ant.

**Comment by lrytz** [comment]
I think we want to include the content of asm.jar, which is indeed happening (i just checked `scala-compiler.jar` of RC2), but not asm.jar itself. I'm pretty sure this is an oversight.

**Comment by szeiger** [comment]
That would have been the next thing for me to check: Do the contents go into the JAR? If so, how? (It wasn't obvious to me from the build definition). If not, do we still need them at all? I'll remove the mapping for the jar and see what happens.

**Comment by lrytz** [comment]
The asm classfiles do go in, and we certainly need them to be in for the compiler to work.

**Comment by szeiger** [comment]
I suspect it's because we pass the `products in Compile in packageBin` to bnd both as the classpath and the resources. For directories it doesn't matter because all files get added individually either as classes or resources but for JARs you end up with the classes plus the JAR as a resource.
