### ISSUE TITLE
enable `-Dscala.color` in shell scripts

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#256]
We should enable color output in the shell scripts so that programmatic launching still gets the plain old version, but users by default get the nicer experience.

**Comment by dwijnand** [comment]
To enable it globally for sbt console you can create a `~/.sbt/0.13/colour.sbt` with:

``` scala
initialize ~= (_ => if (ConsoleLogger.formatEnabled) sys.props("scala.color") = "true")
```

**Comment by retronym** [comment]
Note that some environments still call the scripts that don't really want colorization, e.g. emacs, sublime.

**Comment by retronym** [comment]
http://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe

**Comment by gourlaysama** [comment]
PR: scala/scala#5663 :)
