### ISSUE TITLE
Scala org teams list could use an audit

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#265]
https://github.com/orgs/scala/teams could use a round of work:

* remove "team" from team names, for easier mentioning
* clarify "Community Maintainers" vs "Team Modules", and "Team Scala" vs "Team Core Scala" vs "Team Lightbend"
* probably reduce the overall number of teams
* prune people who we haven't seen in a while, in case their accounts get hacked or whatever

etc. not everything needs to make complete sense, but raising the average sensicality would be good

goals:
  - [ ] the team names should make for convenient @-mentioning, probably need three teams (admins, committers, reviewers -- anything else?)
  - [ ] keep teams fresh by keeping only members that have merged a PR in 6 months (based on `git log --merges`)
  - [ ] add a team for community reviewers that have commit access (so they can review), but they should hold off on merging PRs until they have some reviewing, coding and maintenance experience under their belt before being promoted to the team that merges PRs

**Comment by SethTisue** [comment]
also this blatant power grab shall not stand: 
<img width="482" alt="screen shot 2016-11-15 at 1 38 05 pm" src="https://cloud.githubusercontent.com/assets/161079/20325264/c988b356-ab38-11e6-825b-8d9c9ae0f72d.png">

**Comment by adriaanm** [comment]
right now:
 
```
$ g shortlog -s --merges  --since="12 months" 2.11.x 2.12.x 2.13.x | sort -n | tail -20 
     1	Iulian Dragos
    10	Vlad Ureche
    31	Stefan Zeiger
    73	Jason Zaugg
    86	Seth Tisue
   127	Lukas Rytz
   184	Adriaan Moors
```

```
$  g shortlog -s --no-merges  --since="12 months" 2.11.x 2.12.x 2.13.x | sort -n | tail -20
     4	Viktor Klang
     5	Jakob Odersky
     5	Philippus Baalman
     6	Kenji Yoshida
     7	Daniel Barclay
     7	Iulian Dragos
    10	Performant Data LLC
    13	Miles Sabin
    13	Simon Ochsenreither
    15	Felix Mulder
    16	Dale Wijnand
    17	Sébastien Doeraene
    19	Pap Lőrinc
    25	Janek Bogucki
    34	Stefan Zeiger
    49	Seth Tisue
    89	A. P. Marki
   109	Lukas Rytz
   128	Adriaan Moors
   129	Jason Zaugg
```

**Comment by SethTisue** [comment]
Adriaan did a round of work on this recently 👏

> remove "team" from team names, for easier mentioning

done

> clarify "Community Maintainers" vs "Team Modules", and "Team Scala" vs "Team Core Scala" vs "Team Lightbend"

situation improved. not sure if "done", but good enough for this round, anyway

> probably reduce the overall number of teams

done

> prune people who we haven't seen in a while, in case their accounts get hacked or whatever

probably not really "done", but it's something I generally try to keep in mind when I'm looking at a team

>  the team names should make for convenient @-mentioning, probably need three teams (admins, committers, reviewers -- anything else?)

good enough, now, I think

 > keep teams fresh by keeping only members that have merged a PR in 6 months (based on git log --merges)

meh

>  add a team for community reviewers that have commit access (so they can review), but they should hold off on merging PRs until they have some reviewing, coding and maintenance experience under their belt before being promoted to the team that merges PRs

I don't think this is necessary, GitHub lets non-committers review, and the people we've given commit rights to have been good about adhering to our informal norms about what's okay to merge. it's fine

**Comment by SethTisue** [comment]
> > prune people who we haven't seen in a while, in case their accounts get hacked or whatever

> probably not really "done", but it's something I generally try to keep in mind when I'm looking at a team

Made a pass just now and removed some familiar old-timers, as well as names I didn't even recognize who haven't contributed lately.

I doubt anyone will even notice they were removed, but it's always easy to reinstate somebody.
