### ISSUE TITLE
REPL autocompletion hang with long identifiers

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#271]
The fuzzy matching algorithm I implemented performs poorly for candidates that are long (or mabye have many CamelCaseHumps?)

```
scala> (x: thisIsAReallyLongMethodNameWithManyManyManyManyChunks) => tia<TAB> // hangs
```

Existing test cases:

https://github.com/scala/scala/blob/2.12.x/test/junit/scala/tools/nsc/interpreter/CompletionTest.scala

The culpable algorithm: https://github.com/scala/scala/blob/9c5d3f81a667917b6a3aed5098182623c417c137/src/interactive/scala/tools/nsc/interactive/Global.scala#L1187-L1196

**Comment by retronym** [comment]
The algorithm could be looked at as a 2D pathfinding algorithm:

![image](https://cloud.githubusercontent.com/assets/65551/20514867/1dc082a4-b0da-11e6-8024-2dda81c84ee4.png)

**Comment by som-snytt** [comment]
How fortunate I am to have the upcoming American Thanksgiving holiday to learn a thing, or two.
