### ISSUE TITLE
Merge 2.11.x to 2.12.1

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#272]
I'd like this to land in 2.12.1, if possible, but I've targeted the PR for 2.11.x initially.

https://github.com/scala/scala-dev/issues/271

This ticket is a reminder to forward merge before 2.12.1 is built.

**Comment by SethTisue** [comment]
We also need a forward merge in order to get the fix for the bug that deleted all the nightlies.

**Comment by retronym** [comment]
https://github.com/scala/scala/pull/5561
