### ISSUE TITLE
`foo(_): T` doesn't mean `(x => foo(x)): T`, it means `x => (foo(x): T)`

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#274]
stumbled on this while experimenting with SAMs.

```scala
trait SAM { def foo(x: Int): String }
def bar(x: Int): String = x.toString

bar(_): SAM    // error
(bar(_)): SAM    // works
```

**Comment by SethTisue** [comment]
oh, it's just a parser thing, this works:

```
(bar(_)): SAM
```

**Comment by som-snytt** [comment]
This is per spec, as expected or exspected.

The underscore is bound by `Expr`, and `PostfixExpr: CompoundType` means it behaves as described.

Compare `if (_) x else y` and `if (_ == 1) x else y`; or `bar(_): SAM` and `bar(_ + 1): SAM`

**Comment by SethTisue** [comment]
yeah.

**Comment by som-snytt** [comment]
Yeah, baby!

**Comment by adriaanm** [comment]
No?
