### ISSUE TITLE
Pattern matcher emits too many locals, even under -opt

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#278]
Oops, we haven't updated this:

```
protected val debugInfoEmitVars = !settings.optimise.value
```

However, that might have saved us from https://issues.scala-lang.org/browse/SI-9264, which we must solve before fixing this one.

**Comment by retronym** [comment]
For example:

```scala
class Locals { def foo(a: Any) = a match { case (((_, _), (_, _)), (_, z)) => z } }
```

This has longer bytecode and more locals in 2.12.0 -opt

Here's the trees post patmat for 2.11.8/2.12.0 with and without the optimizer enabled: https://gist.github.com/retronym/31f78b8c72d6c4f6e89b34d01717f493

**Comment by SethTisue** [comment]
@retronym this isn't actually a blocker for RC1, is it? could you set the milestone appropriately?

(if it is an RC1 blocker, I'd suggesting transferring it to scala/bug)

**Comment by dwijnand** [comment]
Seems to me like it hasn't been an issue for users.  We do have an internal ticket about reducing tuple allocation, so we might end up improving the state of this indirectly.
