### ISSUE TITLE
extract our ScalaCheck tests from partest's clutches

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#282]
in brave new sbt world, surely there's no reason for our ScalaCheck based tests, in `test/files/scalacheck`, to be run through the intermediary of partest, rather than by sbt directly...?

**Comment by retronym** [comment]
Yeah, totally. All that should be in a regular sub-project. Our only special requirement is the occasionally need to embed the Scalacheck framework itself when we're making lots of binary incompatible changes.

Obviously one migration task would be to segregate the individual test and test-support code into different packages. Another would be to remove any reliance on comparing stdout against a checkfile.

... looks like there aren't any checkfiles (or.flags files) in there, so it should be easy enough.

**Comment by SethTisue** [comment]
I wasn't around for the discussion around the first decision to in-source, but in-sourcing seems so... what's the word... distasteful, to me, before doing it again for 2.13, I would be interested in discussing alternatives (or at least understanding why they were already considered and rejected, is there a record somewhere?), especially now that we've exited Ant-world and frolic all day in the green lands of sbt

**Comment by retronym** [comment]
@SethTisue completed this task a while ago
