### ISSUE TITLE
Document remote debugger use 

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#288]
Adriaan wrote this somewhere and I squirreled it away:

>Thanks for your interest in digging in here! We use sbt to build and IntelliJ to debug the compiler. I’ve attached a screenshot of how I have IntelliJ debugging set up:
>As you can see, we use remote debugging, and launch the compiler from the sbt shell as follows:

```
> set javaOptions in compiler := List("-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8002")
[info] Defining compiler/*:javaOptions
[info] The new value will be used by compiler/*:runner, compiler/compile:run::runner and 4 others.
[info] 	Run `last` for details.
[info] Reapplying settings...
[info] *** Welcome to the sbt build definition for Scala! ***
[info] Check README.md for more information.
> scalac -uniqid /Users/adriaan/Library/Preferences/IdeaIC2016.2/scratches/scratch_14.scala
[info] Running scala.tools.nsc.Main -usejavacp -uniqid /Users/adriaan/Library/Preferences/IdeaIC2016.2/scratches/scratch_14.scala
Listening for transport dt_socket at address: 8002
```
>Here, you can launch the debug session as setup in my screenshot.
> Happy to help further, though I should add a disclaimer that specialization is a pretty tricky part of the compiler! Good luck!

this should be in the scala/scala repo README. or if it's already documented somewhere else, the README should link to it.

**Comment by adriaanm** [comment]
http://scala-lang.org/contribute/hacker-guide.html#implement

**Comment by SethTisue** [comment]
The `scalac` task forks, so that's why it's possible to customize `javaOptions`.

In a different scenario, where you want to attach a debugger to the normal compiler running in a normal sbt build, you have to pass the `-agentlib...` stuff to sbt itself as it starts.

**Comment by joroKr21** [comment]
These days if you use the sbt shell in Intellij to compile your project, it literally has a button to debug :hugs:

**Comment by SethTisue** [comment]
@retronym notes:

> BTW, recent builds of IntelliJ can attach a debugger to JVMs that weren’t started with the debug enabled. “Run” -> “Attach to process”

**Comment by dwijnand** [comment]
Personally I don't do it either of those ways.  I run `qscalac` and prefix it with `dbg` when I need to debug:

```bash
export DEBUG_OPTS='-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005'

qscalac() { $(git root 2>/dev/null || echo /d/scala)/build/quick/bin/scalac "$@" ; }
dbg() { JAVA_OPTS="$JAVA_OPTS $DEBUG_OPTS" "$@" ; }
```

So I can do things like:

```bash
$ sbt-client compiler/compile && dbg qscalac foo.scala
```

and then attach to the process.

> > BTW, recent builds of IntelliJ can attach a debugger to JVMs that weren’t started with the debug enabled. “Run” -> “Attach to process”

I thought I'd heard about that... TIL.

**Comment by SethTisue** [comment]
closing since we don't like to leave would-be-nice documentation improvement tickets open indefinitely. documentation can always be better

**Comment by som-snytt** [comment]
That is also why I've been closing stale tickets against my New Year's Resolutions.
