### ISSUE TITLE
"request reviewer" feature not working in scala/scala repo?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#289]
e.g. I tried to add Rex as a reviewer on PR 5522, but nothing happened

also reported by @janekdb on Gitter

if the problem doesn't fix itself, I guess we should take it up with GitHub support

**Comment by SethTisue** [comment]
(once we get this sorted out, it would be nice to add a little statement to the README encouraging use of the reviews feature)

**Comment by lrytz** [comment]
for me it worked some times, sometimes not. no clear pattern, i saw it working on my PRs, but also on others.

**Comment by SethTisue** [comment]
this has been working for me lately — optimistically closing

**Comment by janekdb** [comment]
I am not seeing the option on https://github.com/scala/scala/pull/5642

![missing-review-gear](https://cloud.githubusercontent.com/assets/1123855/22285274/cd3e5aa0-e2e2-11e6-8028-4ae7e3bd8579.png)

**Comment by SethTisue** [comment]
weird, I see it:

<img width="778" alt="screen shot 2017-01-25 at 10 54 02 am" src="https://cloud.githubusercontent.com/assets/161079/22304524/9f8ff42e-e2ec-11e6-80ba-c4d10b48c4bf.png">

**Comment by gourlaysama** [comment]
I also can't request a review, apparently (for scala/scala#5663).

The doc says that PR authors can always request from a reviewer, but there seems to be a minimum set of permissions one must have in order to do that, like being a collaborator, or whatever the equivalent is with organization-level permissions...

**Comment by janekdb** [comment]
I asked a human at GitHub to look at this.

**Comment by janekdb** [comment]
GitHub folk said,

> Hi Janek,
> 
> You currently need write access to a repository to request a review.
> 
> I can pass your feedback onto the team to consider for future though.
> 
> Thanks
> Stacey
> 
> On this PR which I am the author of I cannot request a reviewer,
> 
> https://github.com/scala/scala/pull/5642
> 
> According to the GitHub help pages I should be able to do this.
> 
> https://help.github.com/articles/about-pull-request-reviews/
> Pull request authors and repository owners and collaborators can also request a pull request review from a specific person.
> 
> I have notified the Scala team of this problem. They reported that the configurations on their repos appeared to be correct: https://github.com/scala/scala-dev/issues/289
> 
> Thanks,
> Janek

**Comment by SethTisue** [comment]
thanks, Janek, for pursuing this. I've invited you to https://github.com/orgs/scala/teams/team-scala, so at least you'll be able to use this feature now. (in general, we've been adding more community folks to that team in recent months, after a team discussion about it.)

**Comment by janekdb** [comment]
Glad to be part of the crowd!
