### ISSUE TITLE
Change in addition of synthetic Serializable parent to objects with "companion" type alias

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#290]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/694/consoleFull

```
Found 2 binary incompatibilities (11 were filtered out)
=======================================================
 * the type hierarchy of object
   scala.concurrent.forkjoin.package#ThreadLocalRandom is different in current
   version. Missing types {scala.Serializable,java.io.Serializable}
 * the type hierarchy of object
   scala.concurrent.forkjoin.package#ForkJoinTask is different in current
   version. Missing types {scala.Serializable,java.io.Serializable}
```

**Comment by SethTisue** [comment]
note that we merged a MiMa version bump for 2.11 at https://github.com/scala/scala/pull/5590 , but I don't think the bump has been merged onto 2.12 yet

**Comment by adriaanm** [comment]
Looks like a mima bug, maybe in reading pickled info? Both version of the class implement Serializable according to cfr. `public static class package.ForkJoinTask. implements Serializable {`

**Comment by adriaanm** [comment]
I'll open a ticket

**Comment by retronym** [comment]
```scala
    def typedModuleDef(mdef: ModuleDef): Tree = {
      // initialize all constructors of the linked class: the type completer (Namer.methodSig)
      // might add default getters to this object. example: "object T; class T(x: Int = 1)"
      val linkedClass = companionSymbolOf(mdef.symbol, context)
      if (linkedClass != NoSymbol)
        linkedClass.info.decl(nme.CONSTRUCTOR).alternatives foreach (_.initialize)

      val clazz     = mdef.symbol.moduleClass
      val typedMods = typedModifiers(mdef.mods)
      assert(clazz != NoSymbol, mdef)
      val noSerializable = (
           (linkedClass eq NoSymbol)
        || linkedClass.isErroneous
        || !linkedClass.isSerializable
        || clazz.isSerializable
      )
      val impl1 = newTyper(context.make(mdef.impl, clazz, newScope)).typedTemplate(mdef.impl, {
        typedParentTypes(mdef.impl) ++ (
          if (noSerializable) Nil
          else {
            clazz.makeSerializable()
            List(TypeTree(SerializableTpe) setPos clazz.pos.focus)
          }
        )
      })

      val impl2  = finishMethodSynthesis(impl1, clazz, context)

      if (settings.isScala211  && mdef.symbol == PredefModule)
        ensurePredefParentsAreInSameSourceFile(impl2)

      treeCopy.ModuleDef(mdef, typedMods, mdef.name, impl2) setType NoType
    }

```

My recent change to `companionSymbolOf` is the likely culprit.

**Comment by retronym** [comment]
Compilation of:

```scala
object p1 {
  type A
  object A 
}
```

Changed in https://github.com/scala/scala/pull/5550, because we no longer treat `object A` as having a companion class, which for reasons unbeknownst is an input in the logic about whether or not the typer adds `scala.Serializable` as a synthetic parent.

If we want to retain the bugfix in the compiler, we can workaround by explicitly adding the marker interface, or by whitelisting the change as benign. More conservatively revert the change and defer until 2.13.x.

**Comment by som-snytt** [comment]
There doesn't seem to be an `:aha:` emoji.

It's surely traumatic to separate companions like twins and orphaned kittens, so if one is serialized, the other is too; I might need a default ctor arg, another reason it would be nice to have those stashed as statics.

Thx Seth for the heads up; I paid back by answering a newbie on SO.
