### ISSUE TITLE
MiMa forward compatibility checking in scala/scala is broken

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-dev#292]
Reference https://github.com/scala/scala/pull/5623#issuecomment-270470158

Methods added to `<:<` and `=:=` aren't being caught.

**Comment by dwijnand** [comment]
(Opened the issue here under the assumption that it's a scala/scala sbt setup mistake rather than a MiMa bug. Could be wrong about that.)

**Comment by SethTisue** [comment]
Adriaan opened https://github.com/typesafehub/migration-manager/issues/158 on the opposite assumption :-)

**Comment by dwijnand** [comment]
Apparently I'm blind.. it was right there:
![image](https://cloud.githubusercontent.com/assets/344610/21690184/0db999fa-d36b-11e6-967e-bca7d9123110.png)

**Comment by adriaanm** [comment]
:-)
