### ISSUE TITLE
shapeless regression on 2.12

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#293]
Shapeless (most recently) was green in https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1083, while this failed: https://scala-ci.typesafe.com/view/All/job/scala-2.12.x-integrate-community-build/1156/ while building the same shapeless sha (https://github.com/scala/community-builds/commit/6d935d4f6208654b65cc2b79b18a077d04ff18fe). 

Ergo: we broke it.

**Comment by SethTisue** [comment]
ticket: https://github.com/milessabin/shapeless/issues/663 /cc @milessabin

**Comment by SethTisue** [comment]
this is now scala/bug#10154
