### ISSUE TITLE
Intermittent failure in Scalacheck suite (scalacheck/duration.scala)

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#296]
Thanks to @rorygraves for this report:

Looking at the test failure - its unrelated

```
[info] ! Division of Duration by Long.on overflow edge cases: Exception raised on property evaluation.
[info] > Exception: org.scalacheck.Gen$Choose$IllegalBoundsError: invalid bounds: low=9223372036854775799, high=-9223372036854775797
```

I did some investigation and the failure occurs [here](https://github.com/scala/scala/blob/2.12.x/test/scalacheck/duration.scala#L32)

A value of 1 or -1 fails the choose on line 35.
I don't have time to raise the proper bug report right now - but thought I would highlight it.

**Comment by Ichoran** [comment]
It's a very strange way to choose an interval anyway.  A trivial fix would be to change the instances of `Long.MaxValue` to `(Long.MaxValue - 10)` or just to change `- 10` and `+ 10` to `- 20` and `+ 0`.  But I haven't dug enough to understand the point of the code so I'm hesitant to recommend it.

**Comment by l0rinc** [comment]
Isn't the problem an overflow for very small `a`, i.e.`Long.MaxValue / 1 + 10`?

**Comment by rorygraves** [comment]
@paplorinc As far as I can see it only fails for 1 and -1  - We could:
   * Exclude -1 and 1 (we exclude 0 already)
   * Follow @Ichoran suggestion and you -20 and 0 rather than -10,+10
   * Sort the two values to make choice accept them.
I don't have a strong opinion - I'm happy to PR a version once we are happy with which approach to take.

**Comment by SethTisue** [comment]
seen again today at https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/4124/consoleFull

**Comment by SethTisue** [comment]
and at https://github.com/scala/scala/pull/5592

this has been so common lately, it makes me wonder whether a ScalaCheck failure even failed the build  before https://github.com/scala/scala/pull/5661. (not that it matters now, just idle curiosity)
