### ISSUE TITLE
Try to move dealiasing from Uncurry to Erasure info transform

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#297]

**Comment by retronym** [comment]
Seems feasible, see the [first commit](https://github.com/scala/scala/commit/c28009c56f5890af51100a9e77514db65023c274) of https://github.com/scala/scala/compare/2.12.x...retronym:topic/uncurry-without-dealias?expand=1

**Comment by dwijnand** [comment]
You did try, it was a can of worms: https://github.com/scala/scala/pull/5722#issuecomment-324529318
