### ISSUE TITLE
2.11.x regression: scala.collection.IndexedTest failing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#301]
seen at both of:

* https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-bootstrap/838/
* https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-windows/533/

something to do with the recent collections optimizations...?

**Comment by dwijnand** [comment]
IndexedTest comes from https://github.com/scala/scala/pull/5664

**Comment by dwijnand** [comment]
And the build log of the commit introducing the test: https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/2229/consoleFull

Possibly due to 2.11 pr validation running sbt, but 2.11 integrate bootstrap running ant?

**Comment by retronym** [comment]
The JUnit test reports don't seem to be included in the file pattern Jenkin's uses to collect build artifacts, but from the [workspace](https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-bootstrap/ws/build/junit/TEST-scala.collection.IndexedTest.txt/*view*/) we see:

```scala
Testsuite: scala.collection.IndexedTest
Tests run: 13, Failures: 0, Errors: 13, Skipped: 0, Time elapsed: 0.022 sec

Testcase: checkTakeAll took 0.002 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkTakeNeg took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkTakeEmpty took 0.001 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkTakeNormal took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkTakeTooBig took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkSliceNormal took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkEquals took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkSliceToTooBig took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkSliceAll took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkSliceEmpty took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkSliceFromNegAndToTooBig took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkSliceFromNeg took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

Testcase: checkIndexedAccess took 0 sec
	Caused an ERROR
null
java.lang.InstantiationException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
```

**Comment by retronym** [comment]
I think we need to mark the abstract base class `IndexedSeq` with `@Ignore` to make sure the Ant Junit runner doesn't try to run it: http://stackoverflow.com/a/15640958/160378

**Comment by SethTisue** [comment]
thanks, I'll take it from here.

**Comment by SethTisue** [comment]
this is reproducible locally with `ant test.junit`

**Comment by SethTisue** [comment]
the `@Ignore` trick still produces output such as:

```
    [junit] Running scala.collection.IndexedTestImpl.MutableIndexedSeqTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.024 sec
```

so it's ok, but not the greatest.

I'll see if I can find another way — maybe only put the `@RunWith` annotation on the concrete classes

**Comment by SethTisue** [comment]
> maybe only put the @RunWith annotation on the concrete classes

meh, that didn't work. I'll go with the `@Ignore` thing, with a comment. the ant build is not long for this world anyway, and in the sbt build using `@Ignore` this way doesn't result in any extra noise.

**Comment by SethTisue** [comment]
PR: https://github.com/scala/scala/pull/5695
