### ISSUE TITLE
clean up github teams

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#309]
- [ ] the team names should make for convenient @-mentioning, probably need three teams (admins, committers, reviewers -- anything else?)
  - [ ] committers that haven't merged any PRs in 6 months may lose their commit privileges (based on `git log --merges`)
  - [ ] add a team for community reviewers that have commit access (so they can review), but they should hold off on merging PRs until they have some reviewing, coding and maintenance experience under their belt before being promoted to the team that merges PRs

**Comment by SethTisue** [comment]
an older ticket is https://github.com/scala/scala-dev/issues/265
