### ISSUE TITLE
process to document job failures and avoid duplicate detective work

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#311]
We should avoid having to diagnose why a jenkins job failed more than once. The first to diagnose should use the 'Edit Build Information' feature to describe the issue, linking to an issue if needed

**Comment by SethTisue** [comment]
hey, I had no idea this Jenkins feature even existed.

I will totally use this from now on.

super nice how the note shows right up in the list of runs.

**Comment by SethTisue** [comment]
I've been doing this pretty consistently (on community build failures mainly), finding it super helpful just as notes to myself, and for assessing overall recent health. hope others are finding it useful as well.

**Comment by lrytz** [comment]
yes, thanks!
