### ISSUE TITLE
update CI scripts for their output to be less verbose

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#312]
when all goes well, the console output should be minimal, with the full logs being stored as artifacts

especially for CI jobs, it should be immediately obvious what the failures are (which tests failed, etc)

**Comment by dwijnand** [comment]
Does this include dbuild?

Because whenever something fails in the community build the log goes absolutely bananas.

I opened an issue and documented how (imo) it should be fixed in https://github.com/typesafehub/dbuild/issues/194.

**Comment by adriaanm** [comment]
Definitely! Thanks for logging that issue.

**Comment by dwijnand** [comment]
I definitely agree with the sentiment.  But I don't think we'll budget time to making this all nice, we'll probably spend time here and there fixing the most impactful issues.

**Comment by SethTisue** [comment]
Warning elimination is helping some.

In our CI, partest now runs in "terse" mode, and that has helped:

```
# starting 1697 tests in pos
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
.........................................
```

Lately I haven't really been feeling any pain around this.

**Comment by dwijnand** [comment]
One pain that I've found is that partest does a nice "you can fix this by running with `--update-check` on the failing tests like so..." and gives you the command (for back when partest was a bash script).  With `testAll` you don't get that at the end, which is annoying (because that's normally what I need to go fix).
