### ISSUE TITLE
compiler-compat

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-dev#316]
I think with some coordination and effort between the Scala team and direct compiler API users (sbt, paradise, probably ensime, etc) we could do something which would benefit both sides.

What I'm thinking is if we created a compiler-compat project (ala macro-compat), which was blessed by the compiler team, then the tools community would have a tool they could trust/request features/etc, and the compiler team could refactor their APIs with more ease by putting the necessary shims in compiler-compat.

For instance, here are a few examples of Scala maintaining legacy APIs for sbt's sake:

https://github.com/scala/scala/search?l=Scala&p=6&q=sbt&type=Code&utf8=%E2%9C%93

I'm not sure who, or what team, would "own" such a project or who would be the official "maintainers", but I'm sure we can figure those details out. I'm happy with both owning and not owning.

WDYT?

(I wouldn't be surprised if this idea is as old as the hills..)

**Comment by fommil** [comment]
+1 we have so many *BackCompat mixins and implicit classes in ensime

**Comment by sjrd** [comment]
FTR: https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala
The shims used by the Scala.js compiler plugin.

**Comment by milessabin** [comment]
If I were starting macro-compat anew one option I might consider would be to use scalafix to rewrite (from new API to old API) rather than using annotation macros.

**Comment by fommil** [comment]
scala.meta (and hence scalafix) doesn't run on scala 2.10

**Comment by dwijnand** [comment]
> If I were starting macro-compat anew one option I might consider would be to use scalafix to rewrite (from new API to old API) rather than using annotation macros.

Virtual source files! I like it the idea. I'm in.

> scala.meta (and hence scalafix) doesn't run on scala 2.10

Don't need it to be scala 2.10 to setup build infrastructure to run it.

**Comment by fommil** [comment]
don't you need scala.meta to work on scala 2.10 to be able to generate 2.10 files though?

**Comment by jvican** [comment]
> don't you need scala.meta to work on scala 2.10 to be able to generate 2.10 files though?
  
Yes, I think so.

**Comment by milessabin** [comment]
How much effort would be involved in adding 2.10 support to scala.meta?

**Comment by dwijnand** [comment]
Lots, from when I looked about a year ago: https://github.com/scalameta/scalameta/issues/295

**Comment by fommil** [comment]
again... if sbt was to move onto scala 2.12 then tooling and libraries don't need to support it anymore ;-)

**Comment by milessabin** [comment]
@dwijnand that's about porting scala.meta as a whole to 2.10 which, I agree, sounds like a lot of work.

But for this, surely all we need is support for 2.10.x syntax as a language dialect, and only on the output side at that, since surely the point of this is that we be able to write new code using modern syntax/semantics and generate code with old syntax for consumption by an old compiler.

**Comment by dwijnand** [comment]
scala.meta already supports Scala 2.10 as a language dialect, as well as sbt's dialect of Scala: https://github.com/scalameta/scalameta/blob/v1.6.0/scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala#L100-L129

What Sam's talking about is being able to natively call Scalafix within Ensime, which currently must support 2.10.

**Comment by milessabin** [comment]
@dwijnand Sam's original question was,

> don't you need scala.meta to work on scala 2.10 to be able to generate 2.10 files though?

From what you've just said and pointed to, I think the answer to that is "no".

**Comment by dwijnand** [comment]
You're right. Missed that portion. No, it's no necessary. As evidenced by scalafmt formatting sbt build files.
