### ISSUE TITLE
In the scala build "sbt package" fails

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-dev#317]
## steps

Run `package`

## problem

```
[error] (compiler/compile:packageBin) java.util.zip.ZipException: duplicate entry: repl-jline.properties
```

## expectation

I expect it not to fail.

I expect it to successfully produce artefacts for all the projects aggregated by the root project in the build.

My basis for this expectation is the definition of the `package` key:

> Produces the main artifact, such as a binary jar.  This is typically an alias for the task that actually does the packaging.

(http://www.scala-sbt.org/release/sxr/sbt/Keys.scala.html#sbt.Keys.package)

## workaround

Run `dist/mkPack`, as mentioned in the README under "Core commands" of the sbt build:

> * `dist/mkPack` creates a build in the Scala distribution format in build/pack

## notes

This problem isn't new. It's been mentioned almost a year ago: https://github.com/scala/scala/pull/5032#issuecomment-195519328.

I agree with what @lrytz says:

> we should fix that, since it violates common expectations. could be by just printing a doc message on `sbt package`, or by re-wiring it to `dist/mkPack`.

The duplication comes from `repl-jline.properties` being mapped from both

* `build/quick/classes/repl-jline/repl-jline.properties` and
* `build/quick/classes/repl-jline-embedded/repl-jline.properties`

**Comment by paulp** [comment]
Isn't it enough just to add something like `package := (mkPack in dist).value`? It would be a lot more work to document than to fix.

**Comment by dwijnand** [comment]
That's my backup plan. That solution only moves the problem: it fixes `package` (ie. `root/package`), but `compiler/package` is still broken. I expect _that_ to create scala-compiler.jar.

If I can't solve the fundamental problem I'll PR the simple re-wire.

**Comment by dwijnand** [comment]
https://github.com/scala/scala/pull/5747
