### ISSUE TITLE
provide test infra for testing/benchmarking garbage creation and memory consumption

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#321]
through mx bean?

use in compiler benchmarking, collections benchmarking and perhaps in test suite

ensure it's reusable for other projects

**Comment by retronym** [comment]
https://github.com/scala/scala/pull/5848 adds support to scalac 2.12.3 for measuring per-phase allocation, cpu metrics.

In general, we recommend use of the built in profilers of JMH.
