### ISSUE TITLE
Themes for Scala 2.13

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#324]
The 2.13 release of Scala will focus on the following themes:

  - [compiler performance](https://github.com/scala/scala-dev/labels/t%3Aperformance)
  - [simplifying the collections](https://github.com/scala/scala-dev/labels/t%3Acollections)
  - [modularizing the standard library](https://github.com/scala/scala-dev/labels/t%3Amodularize)
  - [user-friendliness](https://github.com/scala/scala-dev/labels/t%3Afriendliness)

Detailed plans are concretizing as issues under the labels linked above. We welcome your feedback on the roadmap as a whole on this issue, as well as more in-depth discussions on the various issues linked above.

We intend to shorten the development cycle a little compared to 2.12, with the first 2.13 release candidate slated for the end of Q1 2018. In 2017, we will release quarterly 2.13 [milestones](https://github.com/scala/scala/milestones) so you can get a good sense of the library changes. While Scala 2.11 will come to a halt with 2.11.9 in Q1 2017, we will maintain 2.12 with regular minor releases throughout 2017.

In collaboration with the Scala Center, as outlined in [SCP-007: Collaborative redesign and implementation of Scala 2.13's collections library](https://github.com/scalacenter/advisoryboard/blob/master/proposals/007-collections.md) and [Stefan's blog post](http://scala-lang.org/blog/2017/02/28/collections-rework.html), the collections library rework effort has kicked off at https://github.com/scala/collection-strawman. Our goal is to simplifying usage and improve performance, with a smooth migration path from the current collections. Please [join](https://github.com/scala/collection-strawman) and help shape one of the defining parts of Scala!

In tandem, the modularisation effort of Scala 2.11 will continue as part of the [Scala Platform process](https://www.scala-lang.org/blog/2016/11/28/spp.html) to foster innovation in our eco-system while maintaining a stable core. The core consists of the collections and the other standard types, such as `Option`, `TupleN`, `Either` and `Try`.  Ultimately, we'd like provide even stronger binary compatibility guarantees for the core, with a vibrant complement of modules that evolve more quickly (offering only backwards compatibility).  [Discuss this theme]( https://github.com/scala/scala-dev/issues/323).

Scala 2.13 is a library release, which means the language itself won't change. However, we continue to invest heavily in the implementation, with a single goal: the make the compiler faster. The first phase of this work involves benchmarking infrastructure, to guide our progress towards a faster compiler. After that, we will attack slowness on all fronts with all available tools. In addition to YourKit and other JVM profilers, which we have been using intensively over the years, we now have a JMH benchmarking harness for the compiler. We are also investigating lower-level performance (cpu caches, memory access patterns, JIT profiles, etc). We are eager to hear your ideas at the compiler performance theme issue. Please head over to https://github.com/scala/compiler-benchmark for the benchmarks and the issue tracker, or [discuss this theme here](https://github.com/scala/scala-dev/issues/322).

Finally, there are [many more things](https://github.com/scala/scala-dev/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.13+label%3Awishlist) we'd like to include in 2.13. Let us know if you'd like to work on one of these. We're always happy to help!

**Comment by SethTisue** [comment]
Where's the "discuss this theme" for friendliness? /cc @robinske

**Comment by zaxebo1** [comment]
for scala 2.13:
 IMHO **Either** ammonite shell should be part of the standard scala as official REPL, 
              **Or** official scala platform REPL shell should be enhanced to the level of ammonite repl/shell

ref: 
http://ammonite.io/#Ammonite-REPL
http://ammonite.io/#Ammonite-Shell

**Comment by SethTisue** [comment]
@zaxebo1 see https://github.com/scala/scala-dev/issues/325

**Comment by jvican** [comment]
> Where's the "discuss this theme" for friendliness? /cc @robinske
  
I opened https://contributors.scala-lang.org/t/towards-better-error-messages-in-scalac/1470/4 to discuss error messages.

**Comment by matanox** [comment]
Is there any way of observing what has been implemented in 2.13 from the above list of themes?

**Comment by adriaanm** [comment]
Good point, we should post back here more regularly with updates. We are focussing on compiler performance and the collections rework. Modularization has seen some modest improvements, but needs more work (some PRs are referenced in the issue that tracks the theme). The REPL has undergone some refactoring to provide better separation from compiler and the UI, and a GSOC mentor has stepped up in https://github.com/scala/scala-lang/pull/825

**Comment by adriaanm** [comment]
Another quick update: the new collections have been merged! See https://contributors.scala-lang.org/t/scala-2-13-progress-report/1840 for more info

**Comment by SethTisue** [comment]
2.13 is now feature-frozen
