### ISSUE TITLE
regression: 2.13 failing bootstrap (scala-xml + scala version number issue)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#334]
at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-bootstrap/136/artifact/logs/builds/*view*/ we see:

```
sbt.ResolveException: unresolved dependency: org.scala-lang.modules#scala-xml_2.13.0-pre-6af9749;1.0.6: not found
```

attn @lrytz

**Comment by lrytz** [comment]
fixed by https://github.com/scala/scala/pull/5768
