### ISSUE TITLE
Provide descriptive names as alternatives to the most commonly used symbolic method names in Scala Collections for 2.13

### ISSUE THREAD

**Issue by mhalttu** [scala/scala-dev#335]
As outlined in http://docs.scala-lang.org/style/naming-conventions.html the use of symbolic method names should be avoided. 

I suggest implementing descriptive alternatives to all the symbolic method names used in the Scala Collections API. I understand that this would add more methods to the API, but I strongly believe it would make the API more accessible for people without an extensive functional background.

As an example, `Map` already now provides `updated` method that is almost synonymous to `+`.

Similarly `++` in `Seq` (or its super class) could be called `concat`
As another example `:+` in `Seq` could be called `append`

**Comment by szeiger** [comment]
https://github.com/scala/collection-strawman would be a better place for this ticket

**Comment by mhalttu** [comment]
Thanks, I'll create a new one there and close this one!
