### ISSUE TITLE
optimizer: re-write List.apply to ::

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#341]
This seems to show up in benchmarks: https://github.com/scala/scala/pull/5797, https://github.com/scala/scala/pull/5785/commits/dbefe29463bf257e2d70155ef87c20fa8b13dbfa

**Comment by rorygraves** [comment]
Could this be fixed by creating multiple apply methods to special case the low numbers e.g.:
```
object List {
  override def apply[A](a: A): List[A] = a :: Nil
  override def apply[A](a:A, b: A): List[A] = a :: b :: Nil
  override def apply[A](a: A, b: A,c : A,  xs: A*): List[A] = a:: b :: c :: xs.toList
```
rather than an optimiser change?

**Comment by lrytz** [comment]
Right, that sounds more reasonable than a special case for List.apply in the optimizer. The optimizer could try to fix it more generally by inlining and eliminating the `WrappedArray`.

**Comment by retronym** [comment]
I've thought about the overload idea (more generally for all collection companions), but a problem is that overloads can hamper with backwards source compatibility and type inference.

I think I've tried to implement the rewrite to `::` at one point, but I can't find the branch.

There is huge tower of indirection behind `List.apply` that the inliner would have to see through. It might be preferable to add a custom, direct implementation.

**Comment by lrytz** [comment]
It can also be a lint/rewrite rule in scalafix

**Comment by dwijnand** [comment]
> There is huge tower of indirection behind List.apply that the inliner would have to see through.

Isn't that quest complete already given the `List()` -> `Nil` rewrite in the optimizer?

**Comment by lrytz** [comment]
> Isn't that quest complete already given the List() -> Nil rewrite in the optimizer?

This is not in the optimizer but a special-case in the typer checker...

```
$ qs -Xprint:all -e "List()"
[[syntax trees at end of                    parser]] // scalacmd2336964510525375174.scala
...
        List()
...
[[syntax trees at end of                     typer]] // scalacmd2336964510525375174.scala
...
        scala.collection.immutable.Nil
...
```

**Comment by lrytz** [comment]
https://github.com/scala/scala/blob/v2.12.1/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L3576-L3585

**Comment by jrudolph** [comment]
More generically, all vararg usages of `GenericCompanion.apply` would probably benefit from an optimization that would rewrite

`Seq(1,2,3,4)` (or anything else that implements `GenericCompanion`)

to

```scala
{
  val builder = Seq.newBuilder[Int]
  builder += 1
  builder += 2
  builder += 3
  builder += 4
  builder.result()
}
```

**Comment by SethTisue** [comment]
@retronym should this stay open?

**Comment by retronym** [comment]
I think we can close this, and use a new ticket if we try to extend the idea to other factories.
