### ISSUE TITLE
Investigate trailing comma impl's lack of applyBracePatch usage

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-dev#347]
From https://github.com/scala/scala/pull/5779#discussion_r107541490

> By the way, when looking at the implementation again, I noticed that the only other use of afterLineEnd is predicated on !applyBracePatch (presumably for the IDE). Should we do that here too?

and

> Regarding the implementation, I'm not up to speed on the IDE's use of the parser, but it looks related to brace patching:
>
> > return true if subsequent end of line handling should be suppressed.
>
> It's overridden in scala.tools.nsc.ast.parser.Scanners.UnitScanner#applyBracePatch according to IntelliJ.

**Comment by dwijnand** [comment]
@adriaanm Reckon this issue is worth keeping? I don't understand how concerning it might be.

**Comment by adriaanm** [comment]
We can always reopen if it turns out to be an issue
