### ISSUE TITLE
scala-dist-smoketest fails in 2.13.x, because parallel collections

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#356]
https://scala-ci.typesafe.com/job/scala-2.13.x-release-smoketest/26/consoleFull:

```
[error] (run-main-0) java.lang.NoClassDefFoundError: scala/collection/Parallelizable
java.lang.NoClassDefFoundError: scala/collection/Parallelizable
	at scala.swing.Publisher.$init$(Publisher.scala:32)
```

fyi @lrytz. I will fix today or tomorrow

**Comment by SethTisue** [comment]
probably this will go away now that https://github.com/scala/scala/pull/5810 is merged? I don't know what Lukas noticed that prompted that PR, but maybe it was this or something like it

here's a new release-main job to see if that's the case: ~~https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/159/consoleFull~~ https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/160/consoleFull

**Comment by SethTisue** [comment]
that job didn't even get that far, because bootstrap is failing because of some OSGi thing; Lukas is working on that, I believe

**Comment by SethTisue** [comment]
we can return to this after https://github.com/scala/scala/pull/5830 is merged

**Comment by lrytz** [comment]
> that job didn't even get that far, because bootstrap is failing because of some OSGi thing; Lukas is working on that, I believe

yes, that should be on top of the queue tomorrow (below caring for sick family members though..)

**Comment by SethTisue** [comment]
bootstrap is fixed now; let's see how https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/164/ does

UPDATE: run 168 was green!
