### ISSUE TITLE
"Reference to uninitialized value" warning not produced for more complicated reference patterns

### ISSUE THREAD

**Issue by cnestor** [scala/scala-dev#367]
Hey guys! Not sure how hard this would be to fix, but I thought I would bring it up.

```scala
//produces compiler warning
class C1 {
  val x = y
  val y = 1
}

//no warning :(
class C2 {
  val x = getY
  val y = 1
  def getY = y
}

//no warning either :(
trait T {
  val y: Int
  val x: Int = y
}

class C3 extends T {
  val y = 1
}

```

This is a really easy thing to do accidentally if you're moving things around and it can lead to a class that throws a NullPointerException whenever it is instantiated.

Related - https://github.com/scala/scala-dev/issues/221
IMO it would be better to produce an error than a warning in general, especially since classes/strings/collections/misc non-Int values default to null, which seems to run very counter to the spirit of Scala. ¯\\_ (ツ) _/¯

**Comment by SethTisue** [comment]
this has been an area of active discussion over the years — you might look for related tickets in scala/bug. it is a difficult design and implementation problem. I doubt anything further will change in this area in Scala 2. not sure what the current status over in lampepfl/dotty is

**Comment by arpit1543** [comment]
I have experienced the same Error while compiling the code.
All i did was just moved around the code and error was gone.

**Comment by dwijnand** [comment]
If you want, this PR in Dotty: https://github.com/lampepfl/dotty/pull/7789 is a proposal for an experimental `-Ycheck-init` to check that initialisation is safe.
