### ISSUE TITLE
Scala 2.12.1 `scala` script did not check for JAVA_HOME

### ISSUE THREAD

**Issue by raymondtay** [scala/scala-dev#368]
The problem i saw when trying to start the REPL using Oracle JDK 1.8 on macOS Sierra is that it threw an error:
```
$ scala
cat: /release: No such file or directory
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.
```

Tracing the `scala` script (after deflating it locally the path is `$HOME/scala-2.12.1/bin/scala`, seems like no check was being done on `JAVA_HOME` before attempting to read the file `release`. Maybe it happens for OSX only, idk. Here's the affected code:

```
  java_release="$(cat $JAVA_HOME/release | grep JAVA_VERSION)"
  if [[ ! "$java_release" =~ JAVA_VERSION=\"1\. ]]; then
    # Java 9 removed sun.boot.class.path, and the supposed replacement to at least see
    # the appended boot classpath (jdk.boot.class.path.append) is not visible.
    # So we have to pass a custom system property that PathResolver will find.
    classpath_args+=("-Dscala.boot.class.path=$TOOL_CLASSPATH")
  fi
```

The immediate _fix_ i need for my local OSX installation is to put the following _check_ before the previous code block, just for correctness sake.
```
  # Note that the version numbers go 1.7, 1.8, 9, 10, ...
  if [[ -z $JAVA_HOME ]]; then
    echo "You need to set JAVA_HOME."
    exit
  fi
```

**Comment by xuwei-k** [comment]
https://github.com/scala/scala/pull/5588

**Comment by raymondtay** [comment]
thanks @xuwei-k for that information, closing this issue now.
