### ISSUE TITLE
migrate scala-dev issues to scala/bug

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#369]
while JIRA was shut down but scala/bug wasn't up yet, we invited people to open issues here instead. those issues should now be moved to scala/bug.

**Comment by adriaanm** [comment]
while we're at it, I'd also like to rename this repo to just `dev`, and use `scala/dev#NNN` to reference tickets (let's leave SI-NNNN and SD-NNN behind us now).

Whenever I think of decommissioning our JIRA, I am reminded of [this](https://www.youtube.com/watch?v=N9wsjroVlu8).

**Comment by SethTisue** [comment]
meh, I think it's fine to migrate individual issues as needed

**Comment by SethTisue** [comment]
especially since GitHub now has the "Transfer issue" feature 💯

**Comment by SethTisue** [comment]
GitHub has "Transfer issue" now, so this was easy to go ahead and take care of. I ran my eyes over all the tickets from around April 2017 and relocated a number of them.
