### ISSUE TITLE
regression: 2.12 failing bootstrap (run/t5717.scala)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#377]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/933/consoleFull

**Comment by SethTisue** [comment]
@lrytz https://github.com/scala/scala/pull/5835 ?

**Comment by lrytz** [comment]
It's probably an interplay of scala/scala#5835 and https://github.com/scala/scala/pull/5820/commits/7a6dc1abbfc9afda27623dd43424c252dcec8088
