### ISSUE TITLE
Automate bumping version in modules using templatecontrol

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#378]
See https://github.com/playframework/templatecontrol

Maybe also investigate other means to keep the admin/ directory in synch across our repos? (Submodules?)

**Comment by dwijnand** [comment]
Fixed by https://github.com/fthomas/scala-steward

**Comment by SethTisue** [comment]
other changes that helped:

* switching off our bespoke publishing stuff and onto sbt-ci-release
* using `https://github.com/scala/scala-dev/blob/scala-dev/travis/default.yml` to standardize our Travis-CI configs

sbt-scala-module continues to play a role in keeping things standardized as well.
