### ISSUE TITLE
the display way of Tab Auto completion

### ISSUE THREAD

**Issue by yinshurman** [scala/scala-dev#380]
in the REPL, enter a Tab will display all the available names imported in the scope which makes a lot troubles in some case,for example,when  pasting codes with tab as indent  from  editors like  vim even in the :paste mode ,the screen if full of unexpected names.
by the way ,the auto completion by  Tab direct print all the names in the screen makes it hard read  on the console.Can't you just display it another way ? For example, like IPython' way.

**Comment by adriaanm** [comment]
Hi, and thanks for the report!

While the JIRA->GitHub Issues migration was in process, we were temporarily accepting tickets here in scala/scala-dev, but now that the scala/bug repo is up and running, this is no longer the first place to go with a new issue

If you're sure you have a bug here, please open it in https://github.com/scala/bug; if you're not sure and want opinions first, https://contributors.scala-lang.org

PS: Apologies if you were sent here by outdated documentation. If so, could you let us know which page needs updating?
