### ISSUE TITLE
tuple2ToZippedOps from Predef.scala yielding a too strong global implicit conversion

### ISSUE THREAD

**Issue by kamilkloch** [scala/scala-dev#382]
Global implicit conversions are tricky. Define
```scala
class A extends Seq[Int] {
    def length: Int = 0
    def apply(idx: Int): Int = 0
    def iterator: Iterator[Int] = Iterator.empty
  }

object A {
  implicit class ATupleOps(x: (A, A)) {
    def zipped: Unit = println("zipped")
  }
}
```

Now,
```sbt
scala> (new A, new A).zipped
res0: scala.runtime.Tuple2Zipped[Int,Seq[Int],Int,Seq[Int]] = scala.runtime.Tuple2Zipped@d3128b35
```

but
```sbt
scala> import A._
import A._

scala> (new A, new A).zipped
zipped
```

In other words, `ATupleOps.zipped` residing in the companion object of `A` is shadowed by the global `tuple2ToZippedOps` defined in `Predef.scala`. 

How about moving `tuple2ToZippedOps` and `tuple3ToZippedOps` from `Predef.scala` to the companion object of `TraversableOnce`, or similar?

**Comment by SethTisue** [comment]
hi, and thanks for the report!

while the JIRA->GitHub Issues migration was in process, we were temporarily accepting tickets here in scala/scala-dev, but now that the scala/bug repo is up and running, this is no longer the first place to go with a new issue

if you're sure you have a bug here, please open it in https://github.com/scala/bug; if you're not sure and want opinions first, https://contributors.scala-lang.org

**Comment by SethTisue** [comment]
P.S. if there was a link somewhere that inappropriately led you here, do you remember where it was?

**Comment by kamilkloch** [comment]
I found the link on github & JIRA issue tracker, both have been updated now.
