### ISSUE TITLE
sanely apply “critical” and “quickfix” labels in scala/bug

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#384]
there are a lot of issues with bad labels in scala/bug, but the two most important that I know of would be to cut down on the excessive numbers of tickets with one of these labels. these are high-visibility labels, "critical" because of the name, "quickfix" because it's used by newcomers, e.g. at open source sprees

for "critical", probably we should have zero or nearly zero such tickets; I suspect most of the tickets currently so labeled are just that way because in some past bug tracker at some past time it was a default

for "quickfix", I think it's mostly because all "minor" priority JIRA tickets were imported with "quickfix". not sure whether it's worth going back to JIRA to address it, or better to just bite the bullet and go through the tickets one at a time (there are ~500)

at the time this is addressed, an update to the scala/scala README would be good, adding at least _some_ text about how we use labels, would be good too

/cc @smarter who called attention to this on scala/contributors Gitter recently

**Comment by som-snytt** [comment]
Alternatively, just add a label, `insane`.

**Comment by SethTisue** [comment]
maybe a `triaged2017` label, with built-in obsolescence

**Comment by SethTisue** [comment]
@larsrh writes [on Twitter](https://twitter.com/larsr_h/status/870340831898730498):

> @SethTisue there are a couple of tickets in scala/bug that I think are erroneously marked "quickfix". Who takes care of labels?

who takes cares of labels? everybody and nobody on the Scala team, and everybody and nobody in the community

see above for how the "quickfix" label got this way

if there just a handful of tickets you think should be relabeled, just comment on the tickets and a repo admin will take care of it.

if you (or anyone reading this who is known to the Scala team) wants to tackle a bigger bout of relabeling, or help with this on an ongoing basis, let us know and either 1) we can up your access temporarily or indefinitely and you can do it, or 2) you can send us a list of ticket numbers and we'll do it with a little script

**Comment by smarter** [comment]
Can we just rename the quickfix label to minor?

**Comment by som-snytt** [comment]
An automatic job that labels "quickfix", then after three months updates to "slowfix", then six months later reverts to "backlog". That's in addition to the classic script which says, "2.12.3 is about to be released, updating fixby to 2.12.4" etc. Also, I miss the one about "kicking the can down the road" or however it went.

**Comment by smarter** [comment]
> Can we just rename the quickfix label to minor?

I still think this needs to be done, the current situation is likely to scare away many potential contributors.

**Comment by SethTisue** [comment]
> Can we just rename the quickfix label to minor?

I agree that would be better than the current situation.

But, what do you think about simply deleting the label? I think that might be even better.

(Note that the "critical" label no longer exists. I don't know when that happened.)

**Comment by smarter** [comment]
Deleting would be fine too yeah

**Comment by SethTisue** [comment]
I'll see what the team thinks.

**Comment by adriaanm** [comment]
I'm fine with deleting the label. In general, we should reduce noise and make it easy to get started contributing!

**Comment by SethTisue** [comment]
if we delete (I will unless new objections are raised soon), I'll also post to contributors.scala-lang.org and ask for community help identifying easy issues. I guess by recreating the label... or maybe `good-first-issue` as a label name? I've seen @jvican using that lately. Jorge, is that a standard choice elsewhere in open-source-land? for a while we were using "spree", but I don't think it's the best choice because the meaning won't be clear to many people (unless they are actually participating in an open source spree)

**Comment by hrhino** [comment]
I [recall](https://user-images.githubusercontent.com/15943089/31588172-37d2b4d8-b1e6-11e7-9e3c-335fe1ad0574.png) that using `good first issue` as a label (spelled thus) makes Github suggest them to new contributors, which would probably be a good thing.

**Comment by dwijnand** [comment]
yes "good first issue" and "help wanted" are a GitHub thing/standard

https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

:+1: for apply that to scala issues

**Comment by SethTisue** [comment]
okay, I deleted the quickfix label and put out a call for help with `good-first-issue` on https://contributors.scala-lang.org/t/help-wanted-identifying-good-first-issues-in-scala-bug/1571

thanks @smarter for nagging :-)

**Comment by SethTisue** [comment]
let's have any further discussion on the Discourse thread (and/or Gitter, with all the pros and cons of the ephemerality of chat in mind...)

**Comment by jvican** [comment]
> I've seen @jvican using that lately. Jorge, is that a standard choice elsewhere in open-source-land? for a while we were using "spree", but I don't think it's the best choice because the meaning won't be clear to many people (unless they are actually participating in an open source spree)
  
Spree should only be used for those tickets that are cherry-picked for sprees, so I agree that the decision made here is the good one. :smile:
