### ISSUE TITLE
Speed up HashMap by avoiding invokeinterface on hot paths

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#389]
Consider copy/paste inheritance of `HashTable.{improve,index,findOrAddEntry,addEntry0,findEntry)` from `trait HashTable` into `class HashMap` to avoid `invokeinterface`.

I noticed these are reported heavily in the profiler as callers of `itable stubs`. See https://wiki.openjdk.java.net/display/HotSpot/InterfaceCalls

![image](https://cloud.githubusercontent.com/assets/65551/26228806/18162502-3c80-11e7-86b3-45af28987808.png)

**Comment by retronym** [comment]
My [first attempt](https://github.com/scala/scala/compare/2.12.x...retronym:faster/mutable-hashmap) at this: reduces the time/op of the `put` operation by 0.8x:

**Comment by fwbrasil** [comment]
@retronym would you mind sharing which tool you used to generate the image on the ticket description? I'm debugging a difference in the rate of itable stub calls in Scala 2.11 and 2.12

**Comment by retronym** [comment]
That was a screenshot from Oracle Performance Studio.

async-profiler and JITWatch are my go to tools at the moment. I’ve making
it more convenient to run JITWatch on our JMH benchmarks
https://github.com/scala/scala/pull/7294

**Comment by dwijnand** [comment]
Probably not relevant anymore after https://github.com/scala/scala/pull/7348.
