### ISSUE TITLE
Tone down range position errors from fatal error to a positioned warning

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#390]
Suggestion from a customer trying to implement code coverage in a large codebase using a compiler plugin that enabled range positions. Makes sense to me.

/cc @adriaanm in case you're in range-pos land in the REPL adventures.

**Comment by adriaanm** [comment]
Good idea -- I'm not there yet, but will keep in mind.

**Comment by jvican** [comment]
I agree this is desirable. It could help Scalameta and Scalafix too (/cc @xeno-by @olafurpg), as well as tooling using range positions for auxiliary features.

**Comment by olafurpg** [comment]
This would be nice. The Scalameta Semantic API, which Scalafix uses, requires -Yrangepos. I regularly hit on assertion errors when trying out -Yrangepos on random projects. A warning would be preferable.

**Comment by SethTisue** [comment]
> The Scalameta Semantic API, which Scalafix uses, requires -Yrangepos

#472 will interest you, then

**Comment by SethTisue** [comment]
@hrhino is interested in `-Yrangepos` now...

**Comment by SethTisue** [comment]
this isn't a blocker for 2.12.5, is it? I've moved it to the 2.12.x milestone
