### ISSUE TITLE
disable 0-ary eta expansion 

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#391]
2.12.3 ticket: #196

**Comment by adriaanm** [comment]
This should set us on a path to fix the wart in https://github.com/lampepfl/dotty/issues/2570 
(do eta-expansion even when the expected type is not known, except for 0-ary functions, where you must do it manually -- the default is to apply a zero-ary function to an empty argument list)

**Comment by SethTisue** [comment]
PR: https://github.com/scala/scala/pull/6475
