### ISSUE TITLE
Document issue labels in scala/bug

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-dev#394]
Relates to and generalises on https://github.com/scala/scala-dev/issues/384 ("sanely apply “critical” and “quickfix” labels in scala/bug").

I couldn't find any guidelines as to whether I should label https://github.com/scala/bug/issues/10361 (value class of Nothing) as "quickfix" given https://github.com/scala/bug/issues/9240 (value class of Unit) is label as such.

**Comment by NthPortal** [comment]
I believe @SethTisue has been removing quickfix from everything, and has possibly even removed the label
