### ISSUE TITLE
bump pickleformat minor version

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#395]
e.g. dotty would like to distinguish 2.11 from 2.12 to interoperate with the trait encoding

**Comment by DarkDimius** [comment]
Yes, please :-)

**Comment by SethTisue** [comment]
@adriaanm still relevant? something to get in to 2.13.0-RC1?

**Comment by dwijnand** [comment]
Better safe than sorry (adding it to the RC1 milestone)

**Comment by smarter** [comment]
the pickle format is 5.2 in 2.13 and 5.0 in 2.12, so it's already different (and it doesn't really matter for dotty, because we only target one version of scalac at a time)
