### ISSUE TITLE
Release 2.13.0-M2

### ISSUE THREAD

**Issue by szeiger** [scala/scala-dev#397]
Milestone: https://github.com/scala/scala/milestone/60

Target date: July 3, 2017

### Before the release
- [x] Notify community on https://contributors.scala-lang.org/c/announcements
- [x] Create next milestone, move the "Merge to 2.13.x" description to it (default for new PRs)
- [x] Close the milestone
- [x] Triage scala/bug and scala/scala-dev tickets that target [version]
- [x] Check PRs assigned to the milestone, also check WIP
- [x] Check merged PRs for the next milestone in this branch, and assign them to this milestone.
- [x] Check module versioning
- [x] Merge in older release branch
- [x] Merge 2.12.x to 2.13.x

### Release notes
- [x] PRs with release-notes label must have excellent title & description (title will be pasted literally in release note bullet list)
- [x] Draft release notes (to be published once GitHub tag is pushed)
  - https://github.com/scala/scala/releases/tag/untagged-2c5680a52e09790a0485
- [x] Prepare PR to https://github.com/scala/scala-lang/ (using scala/make-release-notes): https://github.com/scala/scala-lang/pull/721

### Actual release
- [x] Announce start of release process, point to release note PRs for feedback
- [x] Close the scala/bug milestone, create next, move pending issues
- [x] Close the scala-dev milestone, create next, move pending issues
- [x] Double check [`version.properties`](https://github.com/scala/scala/blob/2.13.x/versions.properties), maybe create a PR with updates

### Stage the release
- [x] Run the [build job](https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/), specify `SCALA_VER_BASE` and `SCALA_VER_SUFFIX`: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/293/
  - [x] Note the scala/scala@NNNNNN commit built by integrate-bootstrap job (on jenkins page): 08ea73a21f72fe831d0aab92c19249c6c2b88c6e
  - [x] Create tag locally: `git tag -s -m "Scala [version]" v[version] [sha]`, 
  - [x] Note the scala/scala-dist@NNNNNN commit built by package-unix job (on jenkins page): 00250054eb18e3b67c22ede8b5202a24ed61cdfa
  - [x] Create tag locally: `git tag -s -m "Scala [version]" v[version] [sha]`, 
  - [x] Staging repo to be promoted after tag is cut (see log of the boostrap job): orgscala-lang-1429
- [x] Sanity check jar/pom in https://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-compiler/2.N.M/ (and a module)
- [x] Announce release is staged at https://oss.sonatype.org/content/repositories/staging/ on https://contributors.scala-lang.org/c/announcements

### Point of no return
- [x] Push scala/scala tag: `git push https://github.com/scala/scala.git v[version]`
- [x] Push scala/scala-dist tag: `git push https://github.com/scala/scala-dist.git v[version]`
- [x] Promote staging repos: `st_stagingRepoPromote [scala-repo]`, `st_stagingRepoPromote [modules-repo]`

### Check availability
- [x] Check release on sonatype: https://oss.sonatype.org/content/repositories/releases/org/scala-lang/scala-compiler/
- [x] Check the release on maven central: http://central.maven.org/maven2/org/scala-lang/scala-compiler/
- [x] Check the release on maven search (takes longer): http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.scala-lang%20v%3A[version]

### When everything is on maven central
- [x] Create PR to update `versions.properties` (new file generated by the bootstrap job) and the `baseVersion` in `build.sbt`: https://github.com/scala/scala/pull/6028
- [x] Pre-announce the release on https://contributors.scala-lang.org/c/announcements
- [x] Check that the API docs are published
  - http://www.scala-lang.org/api/[version]/

### Announcements
- [ ] Scala Users discourse https://users.scala-lang.org
- [ ] Tweet from [@scala_lang](https://twitter.com/scala_lang)

### Release modules
For binary incompatible releases, release modules that are not built during the scala/scala bootstrap (or ask maintainers to do so)
- [x] https://github.com/rickynils/scalacheck
- [x] https://github.com/scala/scala-parallel-collections
- [x] https://github.com/scala/scala-parser-combinators
- [x] https://github.com/scala/scala-swing
- [ ] https://github.com/scala/pickling
- [x] https://github.com/scala/async
- [x] https://github.com/scala/scala-java8-compat

**Comment by adriaanm** [comment]
Because the release-website-update-api job is still part of the release-main flow, the api links will be updated before the tag is pushed to github, which means the source links are broken in the mean time. Last time, I fixed this by creating a branch with the same name as the tag, but that has its own downsides. Maybe we should remove the update-api job from the release flow?

**Comment by xuwei-k** [comment]
scalaz-core, scalaz-effect and scalaz-iteratee released (JVM only)
- https://oss.sonatype.org/content/repositories/releases/org/scalaz/scalaz-core_2.13.0-M2/
- https://oss.sonatype.org/content/repositories/releases/org/scalaz/scalaz-iteratee_2.13.0-M2/
- https://oss.sonatype.org/content/repositories/releases/org/scalaz/scalaz-effect_2.13.0-M2/
