### ISSUE TITLE
scala build fails with None.get on compiler/compile.

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-dev#399]
around line 405 in build.sbt

```scala
Seq((dependencyClasspath in Compile).value.find(_.get(moduleID.key) == Some(asmDep)).get.data) ++
```

I have coursier enabled as a global plugin

**Comment by retronym** [comment]
Hmmm, this was supposed to be fixed in https://github.com/scala/scala/pull/5399. Which branch are you using?

**Comment by MasseGuillaume** [comment]
I was trying out a fix from olaf:
https://github.com/olafurpg/scala/blob/unused-terms-position-point/build.sbt#L405

**Comment by dwijnand** [comment]
Closing as probably stale.  Also scala/scala#5971 mentioned this might be caused by coursier, which may also be a solved problem.
