### ISSUE TITLE
Scaladoc fails to cross-link

### ISSUE THREAD

**Issue by nrinaudo** [scala/scala-dev#400]
There used to be a time where, provided the right metadata was found in a dependency's pom file, scaladoc was capable of cross-linking documentation - and, I believe, inheriting documentation.

For example:

```scala
import com.foo.Foo

/** Custom [[Foo]]! */
class Bar {
  // ...
}
```

Scaladoc used to be capable of linking `[[Foo]]` to its external documentation, and to have all `Foo` members not overridden by `Bar` inherit their documentation from `Foo`.

This appears to not work anymore - is it a regression, does it work in a different way now, or is it simply not supported anymore?

**Comment by ashawley** [comment]
> and to have all `Foo` members not overridden by `Bar` inherit their documentation from Foo.

Did you mean to write `class Bar extends Foo`?

**Comment by ashawley** [comment]
With respect to linking without the full classpath, see scala/bug#3695.  Doesn't look like it ever worked.

**Comment by ashawley** [comment]
Within the same package, inheritance obviously works.  I don't think inheritance could work between external packages.  Not sure how it could work, unless there was an exported representation for docs.  Doesn't seem like sources.jar or javadoc.jar would be sufficient.

**Comment by SethTisue** [comment]
I think this ticket came in during the window when JIRA was down but before scala/bug existed. can someone please open a scala/bug ticket instead...?

**Comment by SethTisue** [comment]
(...sorry for the migration-induced runaround...)
