### ISSUE TITLE
Refactor fix for serializability of lambdas capturing static enclosing module

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#401]
scala/scala#5782 substituted `This(enclosingStaticModuleClass)` with `Ident(enclosingStaticModuleClass.sourceModule)` eagerly creation of the lambda implementation method in `uncurry`. I think it would be more principled to have changed the `Delambdafy` to deal with this, but I didn't have time to pursue this idea.

**Comment by dwijnand** [comment]
The idea has been recorded.  But given Jason found it hard to get right, probably not worth continuing to track this.
