### ISSUE TITLE
let's delete the "critical" label in scala/bug

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#406]
https://github.com/scala/bug/labels/critical

none of us have used this label for years... if it was _ever_ even really used in any consistent way

rather than painstakingly attempting to reapply it in some sane way, I suggest we just delete it.

**Comment by som-snytt** [comment]
Or only apply it to people.

**Comment by SethTisue** [comment]
LOL

**Comment by SethTisue** [comment]
nuked
