### ISSUE TITLE
Deprecate Tuple[23]Zipped.invert, rename to Tuple[23]Zipped.transpose

### ISSUE THREAD

**Issue by kamilkloch** [scala/scala-dev#413]
Method `invert` defined in `Tuple[23]Zipped` object has an unfortunate name - `transpose` fit much better the result:
```scala
@ (Seq(1, 2, 3), Seq('a', 'b')).invert 
res4: Seq[(Int, Char)] = List((1, 'a'), (2, 'b'))
```
I propose to deprecate `invert` and replace it with `transpose`.
The topic already been discussed in scala/scala#5870

**Comment by SethTisue** [comment]
`Tuple[23]Zipped` are deprecated in 2.13.x
