### ISSUE TITLE
Byname implicits parameters with recursive dictionaries

### ISSUE THREAD

**Issue by milessabin** [scala/scala-dev#419]
- [x] Initial implementation &mdash; https://github.com/scala/scala/pull/6050
- [x] Spec update
- [x] SIP
- [x] ~~Integration with [inductive implicits heuristics](https://github.com/scala/scala-dev/issues/421)~~ &mdash; replaced by [polymorphic implicit pruning](https://github.com/scala/scala/pull/6580)
- [ ] Coordination with Dotty &mdash; in progress

From the initial PR,
> This is an implementation of byname implicit parameters with recursive dictionaries, intended as a language-level ... replacement for shapeless's Lazy type. ... implicit arguments can be marked as byname and at call sites will be eligible as parameters in recursively nested positions within their own implicit expansions.

**Comment by SethTisue** [comment]
@milessabin what milestone should this be on?

**Comment by milessabin** [comment]
I'd completely forgotten this ticket ... sorry.

It was merged for 2.13.0-M5, so the milestone is already past.

**Comment by milessabin** [comment]
There are a couple of bugfix PRs in the queue which are targeted at RC1,
+ https://github.com/scala/scala/pull/7199
+ https://github.com/scala/scala/pull/7368
