### ISSUE TITLE
Prototype of shapeless implemented in terms of minimal portable macros

### ISSUE THREAD

**Issue by milessabin** [scala/scala-dev#422]
- [ ] Release of Typelevel Scala incorporating https://github.com/scala/scala-dev/issues/419, https://github.com/scala/scala-dev/issues/420 and https://github.com/scala/scala-dev/issues/421 &mdash; in progress
- [ ] Port core of shapeless to new language features and [scalamacros](https://github.com/scalamacros/scalamacros)
- [ ] Coordination with @xeno-by on scalamacros

The combination of literal types, byname implicits and inductive implicit heuristics eliminates many of the macros currently in shapeless.

This ticket involves porting the remaining macros (principally `Generic`, `LabelledGeneric` (and related) and `Typeable`) to the new [scalamacros](https://github.com/scalamacros/scalamacros) and reducing their surface area as far as possible to evaluate the extent to which scalamacros for Scala/Dotty can substitute for Scala macros. At the end of this process we should have a clear idea of how much more work would be needed in terms of additional scalamacros features and/or language-level primitives.

**Comment by dwijnand** [comment]
I believe this became `scala.compiletime` package in Dotty (https://dotty.epfl.ch/docs/reference/metaprogramming/inline.html).
