### ISSUE TITLE
Jenkins regression: 2.12.x-integrate-windows has been failing for weeks

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#425]
probably something trivial. @adriaanm said he'd look into it

https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/

**Comment by adriaanm** [comment]
I `rm -rf`ed everything under `y:/workspace`. Funny thing, delete in explorer or in "power"shell didn't work because of filenames over 260 chars. `rm` didn't care
