### ISSUE TITLE
deprecate named argument v assignment confusion

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#426]
This is just too confusing. Could we require`foo(bar = 1)`

**Comment by lrytz** [comment]
Yeah, this is basically planned, I probably should have just done it for 2.12.. https://groups.google.com/forum/#!topic/scala-internals/MujIVZgbwEM
I'll put it on my list for 2.13.

**Comment by adriaanm** [comment]
Thanks, I remembered discussing this, but couldn't find the ticket.

**Comment by xeno-by** [comment]
Nice! Recently we realized that we need to remove `Term.NamedArg`, because the parser can't really tell assignments and named args apart, but it'd be great to reinstate it. /cc @olafurpg
