### ISSUE TITLE
Release Scala 2.13.0-M3

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#431]
Milestone: https://github.com/scala/scala/milestone/65

### Before the release
- [X] Notify community on https://contributors.scala-lang.org/c/announcements
- [X] Create next milestone, move the "Merge to 2.13.x" description to it (default for new PRs)
- [x] Close the milestone
- [x] Triage scala/bug and scala/scala-dev tickets that target [version]
- [x] Check PRs assigned to the milestone, also check WIP
- [x] Check merged PRs for the next milestone in this branch, and assign them to this milestone.
- [x] Check module versioning
- [x] Merge in older release branch
- [x] Merge 2.12.x to 2.13.x

### Release notes
- [x] PRs with release-notes label must have excellent title & description (title will be pasted literally in release note bullet list)
- [x] Draft release notes (to be published once GitHub tag is pushed)
  - https://github.com/scala/scala/releases/tag/untagged-???
- [x] Prepare PR to https://github.com/scala/scala-lang/ (using scala/make-release-notes): 

### Actual release
- [x] Announce start of release process, point to release note PRs for feedback
- [x] Close the scala/bug milestone, create next, move pending issues
- [x] Close the scala-dev milestone, create next, move pending issues
- [x] Double check [`version.properties`](https://github.com/scala/scala/blob/2.13.x/versions.properties), maybe create a PR with updates

### Stage the release
- [x] Run the [build job](https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/), specify `SCALA_VER_BASE` and `SCALA_VER_SUFFIX`: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/
  - [x] Note the scala/scala@NNNNNN commit built by integrate-bootstrap job (on jenkins page): 
  - [x] Create tag locally: `git tag -s -m "Scala [version]" v[version] [sha]`, 
  - [x] Note the scala/scala-dist@NNNNNN commit built by package-unix job (on jenkins page): 
  - [x] Create tag locally: `git tag -s -m "Scala [version]" v[version] [sha]`, 
  - [x] Staging repo to be promoted after tag is cut (see log of the bootstrap job): 
- [x] Sanity check jar/pom in https://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-compiler/2.N.M/ (and a module)
- [x] Announce release is staged at https://oss.sonatype.org/content/repositories/staging/ on https://contributors.scala-lang.org/c/announcements

### Point of no return
- [x] Push scala/scala tag: `git push https://github.com/scala/scala.git v[version]`
- [x] Push scala/scala-dist tag: `git push https://github.com/scala/scala-dist.git v[version]`
- [x] Promote staging repos: `st_stagingRepoPromote [scala-repo]`, `st_stagingRepoPromote [modules-repo]`

### Check availability
- [x] Check release on sonatype: https://oss.sonatype.org/content/repositories/releases/org/scala-lang/scala-compiler/
- [x] Check the release on maven central: http://central.maven.org/maven2/org/scala-lang/scala-compiler/
- [x] Check the release on maven search (takes longer): http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.scala-lang%20v%3A[version]

### When everything is on maven central
- [x] Create PR to update `versions.properties` (new file generated by the bootstrap job) and the `baseVersion` in `build.sbt`: https://github.com/scala/scala/pull/6296
- [x] Pre-announce the release on https://contributors.scala-lang.org/c/announcements
- [x] Check that the API docs are published
  - http://www.scala-lang.org/api/[version]/

### Announcements
- [ ] Scala Users discourse https://users.scala-lang.org
- [x] Scala Contributors discourse https://contributors.scala-lang.org
- [x] Tweet from [@scala_lang](https://twitter.com/scala_lang)

### Release modules
For binary incompatible releases, release modules that are not built during the scala/scala bootstrap (or ask maintainers to do so)
- [x] https://github.com/rickynils/scalacheck
- [x] https://github.com/scala/scala-parallel-collections
- [x] https://github.com/scala/scala-parser-combinators
- [x] https://github.com/scala/scala-swing
- [x] https://github.com/scala/scala-java8-compat
- [x] https://github.com/scala/scala-async
- ~~[ ] https://github.com/scala/pickling~~

**Comment by adriaanm** [comment]
Target date is now Jan 15, 2018. M3 has been delayed from its original Q3 2017 deadline because more work was needed on making sure the compiler bootstraps with the new collections.

**Comment by adriaanm** [comment]
Staging! https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/501/console

**Comment by adriaanm** [comment]
Successful run: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/504/console
  - `cd ~/git/scala &&  git tag -s -m "Scala 2.13.0-M3" v2.13.0-M3 cf9d508fcfe6fc6c7246727fcc50340cd0135262`
  - `cd ~/git/scala-dist && git tag -s -m "Scala 2.13.0-M3" v2.13.0-M3 
 00250054eb18e3b67c22ede8b5202a24ed61cdfa`
  - `st_stagingRepoPromote orgscala-lang-1463`

**Comment by gourlaysama** [comment]
Scala-parser-combinators has been [released][1] with 2.13.0-M3 support.

[1]: https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.0

**Comment by SethTisue** [comment]
once ScalaTest is out, I think we could release scala-java8-compat and then announce more broadly. (hopefully by then we'll have Akka, Shapeless, and specs2, too. async, pickling, scala-swing aren't blockers either.)

**Comment by milessabin** [comment]
I'm fairly close to getting shapeless built. There's a regression due to what looks like a bug in https://github.com/scala/scala/pull/5999 (embarrassing, because that's one of mine) but I can work around it and it won't be a showstopper.

**Comment by milessabin** [comment]
shapeless 2.3.3 now built and published for 2.13.0-M3.

**Comment by SethTisue** [comment]
https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md is looking pretty good now. I suggest we wait just a liiiittle longer before doing a second round of publicity, hoping that Akka publishes (https://github.com/akka/akka/issues/24507); Friday's a bad day to announce anything anyway

**Comment by SethTisue** [comment]
updated https://contributors.scala-lang.org/t/scala-2-13-0-m3-is-on-maven-central/1548/2

tweeted https://twitter.com/scala_lang/status/973376143901511681
