### ISSUE TITLE
fix all scala org builds with Travis and openjdk6 to build/test/publish with right JDK

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#435]
gory details at https://github.com/travis-ci/travis-ci/issues/8199#issuecomment-327246053

we were bitten by this at https://github.com/scala/scala-xml/issues/168

**Comment by SethTisue** [comment]
PRs sent to a number of scala org repos and a couple lightbend/typesafehub org repos as well

**Comment by lrytz** [comment]
i got bitten by this too (https://twitter.com/lrytz/status/908329315045187584).. thanks for checking other repos.

**Comment by SethTisue** [comment]
np. and thank you @dwijnand and @ashawley for raising the alarm
