### ISSUE TITLE
Drop procedure syntax

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#438]
Already deprecated, see https://github.com/scala/bug/issues/7605

**Comment by olafurpg** [comment]
Here's a one-liner to replace ProcedureSyntax with `: Unit =`

```
coursier launch ch.epfl.scala:scalafix-cli_2.12.3:0.5.3 -- -r ProcedureSyntax mydirectory
```

**Comment by smarter** [comment]
Is this really something that has to wait for 2.14? Is there a promise that syntactically valid 2.12 code is also syntactically valid 2.13 code?

**Comment by adriaanm** [comment]
2.13 is a library release. No changes to the language except under -Xsource:2.14

**Comment by SethTisue** [comment]
this no longer makes sense to do in Scala 2, after https://www.scala-lang.org/2019/12/18/road-to-scala-3.html

**Comment by eed3si9n** [comment]
Should -Xsource:2.14 be renamed to -Xsource:3.0 since 2.14 is now an alternate history?

**Comment by Jasper-M** [comment]
`-Xsource:3` already exists and includes everything that is `-Xsource:2.14`.
