### ISSUE TITLE
Upgrade to JLine 2.14.1

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#44]
I tried 2.13.0, and hit [this bug](https://github.com/jline/jline2/issues/208) (since fixed).

I also found we needed to disable automatic insertion of " " after completion:

```
    getCompletionHandler match {
      case clch: CandidateListCompletionHandler =>
        // Without this, `"".toChar<TAB>` expands to ``"".toCharArray <CURSOR>` in JLine 2.13
        clch.setPrintSpaceAfterFullCompletion(false)
        // New in JLine 2.13, completion results can be ANSI decorated, but will be stripped before being entered into the buffer
        // Turning this on to foster experimentation!
        clch.setStripAnsi(true)
      case _ =>
    }
```

**Comment by retronym** [comment]
Worth keeping an eye on on the corresponding "upgrade jline" ticket for `groovysh` : https://github.com/apache/incubator-groovy/pull/93

**Comment by xuwei-k** [comment]
https://issues.scala-lang.org/browse/SI-9762

**Comment by retronym** [comment]
https://github.com/scala/scala/pull/5129
