### ISSUE TITLE
Limit package declarations to one per compilation unit

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#440]

**Comment by milessabin** [comment]
I've found this useful for tests ... I suspect I'm not the only one.

**Comment by adriaanm** [comment]
I’m primarily aiming at dropping the incremental package declarations like:
package com; package foo; package bar;

Multiple scoped ones in one file, not sure if they pose a tooling problem.

**Comment by Sciss** [comment]
I use those [throughout](https://github.com/Sciss/Lucre/blob/4545c469b298680ef14102a0230fe74eb39a61ce/core/src/main/scala/de/sciss/lucre/stm/impl/ObjImpl.scala#L14) - [my](https://github.com/Sciss/ScalaColliderSwing/blob/3229839acb1a58414597afc70946397f9c091791/core/src/main/scala/de/sciss/synth/swing/j/JServerStatusPanel.scala#L14) - [code](https://github.com/Sciss/SoundProcesses/blob/d1e60c419866d4c2271148f9befbe33868ca62c1/core/src/main/scala/de/sciss/synth/proc/graph/impl/ActionResponder.scala#L14) - [base](https://github.com/Sciss/Mellite/blob/8d5b020f45b762bb89ddbb11a7e227635d42ba37/src/main/scala/de/sciss/mellite/gui/impl/grapheme/GraphemeCanvas.scala#L14) TBH.

**Comment by hrhino** [comment]
I've found it very convenient to do similar things:

```scala
package com.foo.baz
package internal
```

and now all of the (external) declarations in `com.foo.baz` are in scope. Obviously I can just say

```scala
package com.foo.baz.internal
import com.foo.baz._
```

but it feels more like `internal` is _part_ of `com.foo.baz`, which is subjectively nice.

**Comment by dwijnand** [comment]
> Multiple scoped ones in one file, not sure if they pose a tooling problem.

What's the benefit in the compiler of dropping them?

**Comment by adriaanm** [comment]
It's not really a problem for the compiler, but a code formatter needs to consider this when rewriting imports. With all these tickets, I'm trying to reopen the discussion and pretend we were about to add those features, and ask ourselves, with the benefit of hindsight, is the added convenience worth the complexity?

**Comment by som-snytt** [comment]
I guess the answer was yes.

It's definitely useful to open a ticket to delete a feature and see how many people come out of the woodwork to defend it.
