### ISSUE TITLE
Drop `forSome`, restrict existentials to wildcards

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#443]
See: dotty

**Comment by dwijnand** [comment]
How do you rewrite these?
* `Parser[Seq[ScopedKey[T]] forSome { type T }]`
* `Initialize[Task[T]] forSome { type T }`
* `Seq[Initialize[M[T]] forSome { type T }]`

**Comment by Sciss** [comment]
Just

 - `Parser[Seq[ScopedKey[_]]]`
 - `Initialize[Task[_]]`
 - `Seq[Initialize[M[_]]]`

?

**Comment by dwijnand** [comment]
No `Parser[Seq[ScopedKey[_]]]` is "a parser of a sequence of any type of scoped keys".

`Parser[Seq[ScopedKey[T]] forSome { type T }]` is "a parser of a sequence of scoped keys of the same type".

**Comment by Sciss** [comment]
I don't think there is any semantic difference. These types are the same to Scala:

```scala
// Scala 2.12
trait ScopedKey[A]

trait Foo {
  def bar: ScopedKey[Seq[_]]
  
  def baz(x: ScopedKey[Seq[T] forSome { type T }]): Unit
  
  def test() = baz(bar)  // no prob
}
```

**Comment by dwijnand** [comment]
`Seq[T] forSome { type T }` is equivalent to `Seq[_]`

`Seq[ScopedKey[T]] forSome { type T }` is not equivalent to `Seq[ScopedKey[_]]`, it's a subtype:

```scala
Welcome to Scala 2.12.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> trait ScopedKey[A]
defined trait ScopedKey

scala> (null: Seq[ScopedKey[_]]): (Seq[ScopedKey[T]] forSome { type T })
<console>:13: error: type mismatch;
 found   : Seq[ScopedKey[_]]
 required: Seq[ScopedKey[T]] forSome { type T }

       (null: Seq[ScopedKey[_]]): (Seq[ScopedKey[T]] forSome { type T })
            ^

scala> (null: Seq[ScopedKey[T]] forSome { type T }): Seq[ScopedKey[_]]
res1: Seq[ScopedKey[_]] = null
```

**Comment by Sciss** [comment]
Well I can do the other direction:

```scala
// Scala 2.12
trait ScopedKey[A]

trait Foo {
  def bar: ScopedKey[Seq[T] forSome { type T }]
  
  def baz(x: ScopedKey[Seq[_]]): Unit
  
  def test() = baz(bar)  // no prob
}
```

So I don't see how you're going to have any trouble with the removal of `forSome`.

**Comment by adriaanm** [comment]
Yes, you lose some precision or concision if all you have is wildcards.  Given `type SeqWithKeysOfType[T] = Seq[ScopedKey[T]]`, you recover the type you lost as `SeqWithKeysOfType[_]`

**Comment by dwijnand** [comment]
Nice, thanks.

Also expressible as the type lambda `({ type SeqWithKeysOfType[T] = Seq[ScopedKey[T]] })#SeqWithKeysOfType[_]`.

**Comment by smarter** [comment]
> Yes, you lose some precision or concision if all you have is wildcards. Given type SeqWithKeysOfType[T] = Seq[ScopedKey[T]], you recover the type you lost as SeqWithKeysOfType[_]

Dotty disallows this exactly because it would require the type system to support full existential types to work:
```scala
scala> type ScopedKey[T] 
scala> type SeqWithKeysOfType[T] = Seq[ScopedKey[T]] 
// defined alias type SeqWithKeysOfType = [T] => Seq[ScopedKey[T]]
scala> val x: SeqWithKeysOfType[_] = null 
1 |val x: SeqWithKeysOfType[_] = null
  |       ^^^^^^^^^^^^^^^^^^^^
  |unreducible application of higher-kinded type [T] => Seq[ScopedKey[T]] to wildcard arguments
```

**Comment by SethTisue** [comment]
out of scope for Scala 2
