### ISSUE TITLE
Drop DelayedInit

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#444]
Deprecation: https://github.com/scala/bug/issues/5479

Special-case App trait instead?

**Comment by dwijnand** [comment]
I think the twin Dotty ticket here is https://github.com/lampepfl/dotty/issues/559.

**Comment by SethTisue** [comment]
thread in `DelayedInit`'s defense: https://contributors.scala-lang.org/t/scala-3-delayedinit/1902

**Comment by SethTisue** [comment]
I think this is out of scope for Scala 2.
