### ISSUE TITLE
Build all community build projects with new collections

### ISSUE THREAD

**Issue by szeiger** [scala/scala-dev#450]
As proposed by @retronym it should be possible to create all dependencies in a community build with a scala-library containing the old collections library and use those to recompile everything with a new scala-library with the new collections. This would obviously not result in usable artifacts due to compatibility issues but it could make it possible to test for compilation issues without first having to upgrade all dependencies of a project.

**Comment by SethTisue** [comment]
@szeiger I think we should just wait until the new collections land in scala/scala, and at that point start dealing with community build failures. wdyt?

**Comment by SethTisue** [comment]
the action's at https://github.com/scala/community-builds/issues/710
