### ISSUE TITLE
2.13.x failing bootstrap; unused-import change?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#453]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-bootstrap/587/artifact/logs/builds/*view*/

```
[error] /home/jenkins/workspace/scala-2.13.x-integrate-bootstrap/scala-partest/src/main/scala/scala/tools/partest/nest/Runner.scala:21: Unused import
[error] import ClassPath.{ join, split }
```

**Comment by ashawley** [comment]
Time to release a new scala-xml? :-)

Actually, I guess it's a problem for scala-partest, too

**Comment by SethTisue** [comment]
the scala-xml build prints tons of warnings during bootstrap, but it doesn't fail because `-Xfatal-warnings` isn't enabled. but scala-partest does have it enabled. (I think it was me who enabled it?)

perhaps we could modify the bootstrap script to explicitly disable `-Xfatal-warnings` when building modules during bootstrap. having it in regular builds is good, but it's probably too fragile and annoying when bootstrapping.
