### ISSUE TITLE
recent 2.13 changes broke a bunch of community build projects

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#454]
notably scala-js, scalaz, and shapeless.... but also scala-gopher, scallop, twirl, and twotails

the last run where pretty much everything was green was: scala/scala@8084591 (https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/858)

the first run where everything broke was: scala/scala@ca07e6c (https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/859)

most or maybe all of this is probably the result of scala/scala@a992c8352b9f309ec0a3d807425786dc21dd6284 ("Change default Xsource to 2.13")

in some cases there are multiple compile errors, but here's an incomplete sample of the error messages:
* scala-js, twirl: type mismatch  (maybe eta expansion related?)
* shapeless: ambiguous implicit values
* scalaz: multiple errors including ambiguous implicit values
* scallop: overloaded method args needs result type
* twotails: not found: type AssignOrNamedArg
* scala-gopher: assignments in argument position are no longer allowed since Scala 2.13

**Comment by sjrd** [comment]
FTR, the Scala.js compile error points to https://github.com/scala-js/scala-js/blob/fb69707b60018f65a4cb23a9a9722e2b8bd6f06a/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/CollectionsOnCheckedListTest.scala#L50-L53

which calls the method `testOnFirstPositionOfIterator` defined at https://github.com/scala-js/scala-js/blob/7640e858efbf8dbf52c99ca8a82cfb2350836e02/test-suite/shared/src/test/scala/org/scalajs/testsuite/utils/CollectionsTestBase.scala#L74-L76

It's pretty clear that it is related to eta expansion, indeed.

**Comment by SethTisue** [comment]
* I fixed a few projects myself (genjavadoc, utest, ...)
* failing projects were removed en masse in scala/community-builds#673 to get the build green for 2.13.0-M3
* Miles will look at Shapeless in the next week or so
* scala-js fix is nearly done, ticket is https://github.com/scala/community-builds/issues/674
* I made a scalaz ticket at https://github.com/scalaz/scalaz/issues/1629

**Comment by SethTisue** [comment]
the new collections have landed, which means everything is back to square one. if any of these problems still exist, we'll encounter them again as we grow the 2.13 build again.
