### ISSUE TITLE
Drop postfix operators

### ISSUE THREAD

**Issue by Jasper-M** [scala/scala-dev#462]
[Somewhere in the Scala documentation about postfix notation:](http://docs.scala-lang.org/style/method-invocation.html)

> This may result in unexpected compile errors at best, and happily compiled faulty code at worst. Although the syntax is used by some DSLs, it should be considered deprecated, and avoided.

I personally don't know of any DSLs which can't live without postfix ops. On the other hand I've seen a lot of people become confused when their code stops compiling because of the poor interaction with semicolon inference. It's "hidden" behind an import/flag, but then again so are a couple of actually useful features, so people tend to just ignore that and try to use it anyway.
Why don't we just actually deprecate and drop it, while we're busy dropping things, and make Scala a little bit less confusing?

**Comment by SethTisue** [comment]
Sounds good to me. I suggest starting a contributors.scala-lang.org thread to garner support (or gauge opposition).

**Comment by Jasper-M** [comment]
https://contributors.scala-lang.org/t/lets-drop-postfix-operators/1457

**Comment by som-snytt** [comment]
Ask on contributors, get a [contribution](https://github.com/scala/scala/pull/6559).

The PR just makes the feature flag required, as suggested by Séb.

So glad the fad of "drop ALL the dots!" has faded. I guess dotty brought them back.
