### ISSUE TITLE
2.13: regression in handling of unary `+` on numeric literals

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#465]
in very recent 2.13.x nightlies,

```
scala> (+0): Byte
        ^
       error: type mismatch;
        found   : Int(0)
        required: Byte
```

as `Byte`, so also `Short` and `Char`. this code has been accepted since Scala 2.8 (the version that introduced weak conformance). Dotty also accepts it.

note that while an initial `-` is part of the syntax for numeric literals, `+` is not (SLS 1.3). `+0` parses as `0.unary_+`. `(0.unary_+): Byte` gives the same error (and was accepted in previous Scala versions).

@sjrd this was uncovered by Scala.js's test suite, via the community build 🏅

@milessabin I haven't bisected to pinpoint when this regressed, but I bet this has to do with one of your [recent changes to ConstantFolder](https://github.com/scala/scala/commits/2.13.x/src/compiler/scala/tools/nsc/typechecker/ConstantFolder.scala) made as part of SIP-23 (PR scala/scala#5310)

[SLS 6.24](http://scala-lang.org/files/archive/spec/2.12/06-expressions.html#constant-expressions), "Constant Expressions", gives plenty of wiggle room here:

> Constant expressions are expressions that the Scala compiler can evaluate to a constant. The definition of "constant expression" depends on the platform

regardless, I think it would be peculiar if `+0` weren't covered, given that `0 + 0` is covered (`(0 + 0): Byte` still compiles)

**Comment by Jasper-M** [comment]
`unary_+` has always been weird apparently:
```scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_152).
Type in expressions for evaluation. Or try :help.

scala> final val a = -0
a: Int(0) = 0

scala> final val b = 2 + 3
b: Int(5) = 5

scala> final val c = +0
c: Int = 0
```

**Comment by milessabin** [comment]
Yup, this is probably down to me.

**Comment by milessabin** [comment]
Dumb question, but why is this here rather than scala/bug?

**Comment by SethTisue** [comment]
roughly speaking,

scala/bug is a permanent historical record of bugs that made it into stable releases; end users are expected to look there. 

scala-dev is a place for the core team, and associates and regulars such as yourself, to temporarily track work-in-progress and ephemeral issues

I’ll be the first to admit to the distinction isn’t always clear-cut.

**Comment by milessabin** [comment]
Fixed in https://github.com/scala/scala/pull/6416.

**Comment by som-snytt** [comment]
Also http://scalapuzzlers.com/#pzzlr-041 which has held up nicely.
