### ISSUE TITLE
2.13.0-M3 release notes should explain -Xsource:2.13 situation

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#469]
I’d like to call it a day. maybe y’all Europeans could take care of this when you wake up and after you've eaten your crumpets or sausages or whatever you eat for breakfast

https://github.com/scala/scala/releases/tag/v2.13.0-M3 should explain the situation with `-Xsource:2.13` not having been enabled, inadvertently, in M1 and M2, and what language changes (dating back to the 2.12.x branch, so not just 2.13 PRs) are now enabled as a result

**Comment by adriaanm** [comment]
Updated, and documented changes in 2.13 in https://github.com/scala/scala-dev/issues/470. Could someone else make a list for 2.12 some time?

**Comment by milessabin** [comment]
Crumpets are for _tea time_ ...
