### ISSUE TITLE
2.13 regression: named-argument calls generate redundant extra bytecode

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#476]
(discovered while upgrading [Fortify SCA for Scala](https://developer.lightbend.com/docs/fortify/latest/) to 2.13.0-M3)

for code like:

```
  def foo(a: Int, b: String): Unit = {}
  foo(b = "ha", a = 9)
```

I'm seeing (in my compiler plugin with runs after mixin):

```
          Block( // tree.tpe=Unit
            // 2 statements
            ValDef( // val x$3: String("ha")
              <artifact>
              "x$3"
              <tpt> // tree.tpe=String("ha")
              "ha"
            )
            ValDef( // val x$4: Int(9)
              <artifact>
              "x$4"
              <tpt> // tree.tpe=Int(9)
              9
            )
            Apply( // def foo(a: Int,b: String): Unit in class DefaultNamed, tree.tpe=Unit
              DefaultNamed.this."foo" // def foo(a: Int,b: String): Unit in class DefaultNamed, tree.tpe=(a: Int, b: String)Unit
              // 2 arguments
              9
              "ha"
            )
          )
```

note that `x$3` and `x$4` are unused.

in 2.12, the final `Apply` call instead references `x$3` and `x$4` rather than inlining their values.

@lrytz this seems like your territory... can you shed any light on what changed here? once these trees hit the back end they do result in additional bytecode:

```
  public void bar();
    Code:
       0: ldc           #28                 // String ha
       2: astore_1
       3: bipush        9
       5: istore_2
       6: aload_0
       7: bipush        9
       9: ldc           #28                 // String ha
      11: invokevirtual #30                 // Method foo:(ILjava/lang/String;)V
      14: return
```

note the doubled `ldc`s and `bipush`s. 2.12 doesn't do that:

```
  public void bar();
    Code:
       0: ldc           #28                 // String ha
       2: astore_1
       3: bipush        9
       5: istore_2
       6: aload_0
       7: iload_2
       8: aload_1
       9: invokevirtual #30                 // Method foo:(ILjava/lang/String;)V
      12: return
```

only literals are affected; if I replace `"ha"` or `9` with a method call, we don't end up with two method calls in bytecode. maybe this has something to do with the SIP-23 changes

**Comment by SethTisue** [comment]
note that the 2.12 bytecode is no better overall, since it has extra unnecessary stores and loads instead of extra unnecessary `ldc` and `bipush`

but the point is, if the trees reaching the back end didn't have the redundancy, then we would be emitting just:

```
  public void bar();
    Code:
       : bipush        9
       : ldc           #28                 // String ha
       : invokevirtual #30                 // Method foo:(ILjava/lang/String;)V
       : return
```

**Comment by SethTisue** [comment]
note that the `val`s even arise at all because the order of arguments at the call site doesn't match the order at the definition site. and [SID-1](http://docs.scala-lang.org/sips/completed/named-and-default-arguments.html) says "The argument expressions are evaluated in call-site order"

if I enable `-optimize` the extra bytecode goes away in 2.13, whereas in 2.12, it doesn't! so I take it back, this isn't a regression at all... the situation is improved since 2.12.

**Comment by SethTisue** [comment]
[🎵 Rubber Ducky, you're the one, You make bath time lots of fun 🎵](https://en.wikipedia.org/wiki/Rubber_duck_debugging)

**Comment by lrytz** [comment]
It's quite certainly related to the SIP-23 implementation. The local vals are there in 2.12 as well, and actually used. In 2.13, I assume it's `adapt` (called after type-checking the tree that references the local val) that replaces the reference to the local val with a Literal of the ConstantType value. We could be smarter in names-defaults and avoid the local vals for side-effect free arguments.

**Comment by milessabin** [comment]
Anything I need to look at here? It sounds like we're moving forwards rather than backwards?

**Comment by lrytz** [comment]
Looking in more detail, my previous explanation was wrong; if I write manually

```
{
  val x: 1 = 1
  int2Integer(x)
}
```
then `-Xprint:typer` shows
```
  val x: 1 = 1;
  scala.Predef.int2Integer(x)
```
So the reference to `x` is not inlined.

However, it does happen for reordered arguments:
```
def f(a: Int, b: Int) = 0
f(b = 1, a = 2)
```
`-Xprint:typer`

```
  <artifact> val x$1: Int(1) = 1;
  <artifact> val x$2: Int(2) = 2;
  C.this.f(2, 1)
```

NamesDefaults initially creates a tree `f(x$2, x$1)`. The referneces to `x$1` / `x$2` are created with `gen.mkAttributedRef`, and ultimately `Ident(sym.name) setSymbol sym setType sym.tpeHK`. So the `Ident` trees get constant type and then are replaced in `adapt` / `adaptConstant` by literals.

Maybe you can share your thoughts:
  - Should / could the same be done for user-written code
  - Or do you see a problem / potential issue with replacing references to literal-typed vals/vars by literals?

**Comment by milessabin** [comment]
There's a difference between an explicit literal type (represented by the `LiteralType` subtype of `ConstantType`) and a safely foldable constant type (represented by the `FoldableConstantType` subtype of `ConstantType`) ... values of the former can have side effects which shouldn't be folded or otherwise elided; values of the latter can't have side effects and can be folded and elided.

In your first two examples the explicit literal type `: 1` could only be the result of a users explicit type annotation, so it could have a side effect on the RHS, eg.,

```scala
def foo (x: 1 = { println("Quux") ; 1}) = x
```
That would not be the case in your third example where you have foldable constant types rather than explicit literal types.

So I think that's what's happening in your third example is correct. And I think that what's happening in your first two example is correct, so long as what happens in these two cases is the same,
```scala
def foo (x: 1 = { println("Quux") ; 1}) = x
def bar (x: Int = { println("Quux") ; 1}) = x
```
