### ISSUE TITLE
Range Position validation could be faster

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#487]
When compiling with `-Yrangepos`, the compiler checks post-parser and post-typer ASTs for coherent range positions.

If we're able to turn on range positions by default in 2.13 (#472), we're [planning](https://github.com/scala/scala-dev/issues/390) to turn this off by default and/or demote the error to a warning of some sort.

`-Yrangepos` is used by some batch compiler use cases, e.g. to make `scoverage` work.

The validation could be made somewhat faster with some profiling and tuning. 

In particular:

  - [ ] Reimplement `Tree.children` directly across `Tree`. 
  - [ ] Avoid creating temporary lists in code like `tree.children flatMap solidDescendants` by instead using `Iterator`s.

**Comment by hrhino** [comment]
I have some work on this which I'll toss up as soon as I can, if no one else beats me to it.

**Comment by dwijnand** [comment]
If you need another use case specs2 has instructed for a while now to enable range positions: https://etorreborre.github.io/specs2/website/SPECS2-4.1.0/quickstart.html
