### ISSUE TITLE
Deprecate inheritance for package objects

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#488]
See #441

**Comment by eed3si9n** [comment]
Not sure if you need to do more to support migration, but I sent a PR that deprecates inheritance - https://github.com/scala/scala/pull/6584

**Comment by jvican** [comment]
When this deprecation becomes an error maybe in 2.14.x, we can probably get rid of the extra incremental invalidation in Zinc to handle package object symbol's loading correctly, see test  https://github.com/sbt/zinc/blob/1.x/zinc/src/sbt-test/source-dependencies/pkg-self/test for more information.

**Comment by dwijnand** [comment]
Seth argues that this is for Scala 3 to deprecate (and then remove) as in Scala 2 we don't have a migration story to present to today's users.
