### ISSUE TITLE
Nested objects ACC_FINAL in bytecode?

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#497]

**Comment by SethTisue** [comment]
@adriaanm ping

**Comment by SethTisue** [comment]
@adriaanm move to later milestone?

**Comment by SethTisue** [comment]
@lrytz @retronym do you remember anything about this? if not, maybe we should just close it?

**Comment by lrytz** [comment]
Maybe `class C { object O }` -- `cfr-decompiler C.class` -- `public C$O$ O()` is not final.

It is with Scala 3.

But I don't think we should change it at this point, unless it actually fixes a known issue.
