### ISSUE TITLE
Reduce allocation of StringBuilders in the backend

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#500]
![image](https://user-images.githubusercontent.com/65551/39744260-00e0695a-52e7-11e8-93f5-55890fe821f5.png)

BType => String conversion is very allocation heavy in the backend. A prior attempt to fix this tried to use a cache on `BType`. I think it might be sufficient instead to use a one-element cache of a reusable StringBuilder in the backend for us in `BType.toString`.

It might still make sense to cache the descriptors, but we should do so by making sure we're not redundantly doing the work in `methodBTypeFromSymbol` each time a symbol is referenced.

**Comment by retronym** [comment]
I've sketched out the reusable StringBuilder idea in https://github.com/scala/scala/compare/9766d5d400d71e53615a66016e7899ddd1086c8d...retronym:faster/one-elem-cache

**Comment by mkeskells** [comment]
the cache would need to be threadsafe or a threadlocal. BTypes can be multi-threaded

**Comment by dwijnand** [comment]
Only looking briefly it looks like https://github.com/scala/scala/pull/8480 delivered this.  Thank you, @diesalbla!
