### ISSUE TITLE
2.13 macro annotation test doesn't work on Windows

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#505]
seen at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/559/

```
[error] - macroAnnot/test
[error]   - macroAnnot/scalaInstance failed: java.util.NoSuchElementException: None.get
```

**Comment by adriaanm** [comment]
the fix should be trivial in quickInstnace in the build I have a hardwired path. Could you look into it please?

**Comment by SethTisue** [comment]
sure

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/6619

**Comment by SethTisue** [comment]
(but see https://github.com/scala/scala-dev/issues/506, it looks to me like the tests aren't actually being run on Windows, unless I'm seeing phantoms, or rather not-seeing not-phantoms)
