### ISSUE TITLE
Windows test jobs don't appear to be running JUnit tests

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#506]
at e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/561/console I see the JUnit tests being compiled, but not actually being run

https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/977/consoleFull, same

2.11 seems okay at https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-windows/1004/consoleFull

if this is real, I should check ScalaCheck and other stuff too

**Comment by SethTisue** [comment]
I wondered if this wasn't a Windows bug, but simply a bug in the `testAll` task, which we don't use in our other scripts. But when I run `testAll` locally (on MacOS anyway), the tests run. so idk

**Comment by SethTisue** [comment]
another hypothesis to check: are we running sbt at info level or warn level? because while messing with https://github.com/scala/scala/pull/6621 I think I may have seen that with `-warn`, running (non-partest) tests may be silent. not sure, but note to self for later

**Comment by SethTisue** [comment]
> I think I may have seen that with -warn, running (non-partest) tests may be silent

you might expect to at least get a summary at the end saying how many tests ran, but actually:

```
> junit/test
# WARNING: Unable to attach Serviceability Agent. You can try again with escalated privileges. Two options: a) use -Djol.tryWithSudo=true to try with sudo; b) echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
skipping mrJar() on old JdK
skipping mrJar() on old JDK
[success] Total time: 79 s, completed May 11, 2018 9:53:52 PM
> 
```

here I think the `[success]` at the end comes because the entire command finished, but with `testAll` you wouldn't get that after each part.

**Comment by SethTisue** [comment]
yeah I'm confident now that's all this is. why `scripts/jobs/integrate/windows` even has `--warn` in it at all, I have no idea.

I'm going to close this and just make a note at https://github.com/scala/scala-dev/issues/508 to probably increasing the logging level at the time we move to AppVeyor

/cc @martijnhoekstra

**Comment by martijnhoekstra** [comment]
Sounds likely - I still haven't been able to run the integrate/windows script locally (I probably need cygwin for it, and git decided again I need carriage returns in bash files, making it fail in spectacular ways on git bash and in LSW), but sbt testAll does what it should on Windows in all shells/environments I've tried and have available.
