### ISSUE TITLE
Deprecate class shadowing

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#514]
or should this wait until 2.14? (I think I had a ticket on this already but can't find it.)

**Comment by dwijnand** [comment]
What's meant by class shadowing?

**Comment by adriaanm** [comment]
`class A { class C } ; class B extends A { class C } // A#C is shadowed in B`

**Comment by adriaanm** [comment]
There's a ticket somewhere that shows how we get the two Cs confused. Unsoundness ensues.

**Comment by smarter** [comment]
See https://github.com/lampepfl/dotty/issues/4361

**Comment by smarter** [comment]
Duplicate of https://github.com/scala/scala-dev/issues/156
