### ISSUE TITLE
Re-enable macro annotations tests

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#516]
They were disabled in https://github.com/scala/scala/commit/11902082eb6af00b971aaf16a8eb4d978bc31095

Thinking about it, maybe it's enough to add some unique suffix to the scala version in https://github.com/scala/scala/blob/4ffaf3935388f389d4b9034b7c0957a473cc8e84/build.sbt#L105. It's possible that using `(scalaInstance in bootstrap).value.version` (2.13.0-pre-SNAPSHOT) made sbt compile the compiler-interface against some different scala version using `2.13.0-pre-SNAPSHOT`.

On the other hand, our "model" for the rest of the repository is: sources compiled in the sbt session are compiled with the "starr" compiler, not the one built by the project. Tests that actually test the bootstrapped compiler are in partest. It might be cleaner to follow the same pattern for macro annotation tests, i.e., move them to partest.

**Comment by adriaanm** [comment]
https://github.com/scala/scala/pull/6691
