### ISSUE TITLE
Provide an API for map iteration without Tuples

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#521]
Straw man:

```scala
trait Map {
def foreachEntry[U](f: (K, V) => U) = foreach(f.tupled) // maps could override this.
}
```

I also feel we should make this return true:

```scala
scala> val f= (a: Int, b: Int) => a + b; val f2 = Function.untupled(f.tupled); f eq f2
f: (Int, Int) => Int = $$Lambda$1134/1641214567@26d40c77
f2: (Int, Int) => Int = scala.Function$$$Lambda$1115/1673518027@85ab964
res4: Boolean = false
```

And make it possible to introspect a function to see if it is tupled and get to the wrapped function. That way, we _might_ not need the extra API point at all:

```scala
class HashMap {
  def foreach(f: Function1[Tuple2[K, V], Unit]) = foreachImpl(Function.untupled)
  def foreachImpl(f: Function2[K, V, Unit]) = {f(k1, v1); f(k2, v2); ... }
}
class PerformanceSensitiveClient {
   def c(m: Map[Any, Any]) = {
      m.foreach( {(k: Any: V: Any) => println(k, v)}.tupled }
   }
}
```

We could even imagine desugaring pattern maching anonymous functions like ` { case (k, v) => println(a, b) }: Function1[Tuple2[K, V], Unit]` to the above. We need to make sure there is no binder capturing the tuple itself, and we'd also need to change the way we synthetize the `MatchError` case which does capture the `Tuple`.

What about `Iterator`-s? Could we introduce:

```scala
trait EntryIterator[K, V] extends Iterarator[(K, V)] {
   def hasNext(): Boolean
   override def next(): (K, V) = // slow path for generic code

   // faster path for code map specific iteration.
   def advance(): Unit
   def key: K
   def value: V
}
```

Note: Java `HashMap`-s achieve good iteration performance by iterating over elements of type `Map.Entry`, which is implemented by the nodes in the internal structure of the `HashMap`.

**Comment by retronym** [comment]
@szeiger @julienrf Did this topic come up in the collections rework?

**Comment by julienrf** [comment]
We mention that but did not do anything. Maps operations always take tuples.

**Comment by retronym** [comment]
I agree it would be too big a change to loosen `Tuple2` to `Product2` in the placees it exists. But we still have the possibility to create a map specific `foreachEntry` and/or `MapIterator`.

**Comment by Ichoran** [comment]
I agree that having a detupled variant of `foreach` and maybe a few others would be a good idea for performance.

I'm less sure about `MapIterator`; `next` either has to return a tuple, or the interface would be weirdly non-Iterator-like.  (You'd need an advance/current API instead so you could have currentKey, currentValue; the hasNext/next model doesn't save any allocations.)

**Comment by retronym** [comment]
MapIterator.next could return this typed as Product2 for a natural api that
would be efficient.

**Comment by retronym** [comment]
An implementation of the idea to add a `keyValueIterator: Iterator[Product2[K, V]]`: https://github.com/scala/scala/compare/85e1fefb788bc7b37af50fa10eefa8bb5a68d48b...retronym:faster/collections-empty-iterators?expand=1

**Comment by ijuma** [comment]
> MapIterator.next could return this typed as Product2 for a natural api that
would be efficient.

This would not work for open addressed maps, right?

**Comment by retronym** [comment]
The iterator itself can [contain a mutable tuple](https://github.com/scala/scala/compare/85e1fefb788bc7b37af50fa10eefa8bb5a68d48b...retronym:faster/collections-empty-iterators?expand=1#diff-43417c3d2b66ce19a2d4981ab39c0ae5R643) as the `Product2` implementation. The problem is that the caller must call `_1` and `_2` _before_ calling `.next`, so `keyValuesIterator.map(x => Some(x)).map(_.get._1)` would not work as some users might expect.

I'm leaning towards just adding `def foreachKeyValue(f: Function2)`.

**Comment by ijuma** [comment]
Yeah, `foreachKeyValue` seems like the simplest approach.
