### ISSUE TITLE
immutable.ArraySeq.ofRef#equals incorrect

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#532]
It is based on `equals` rather than `BoxesRuntime.equals`.

```scala
  @SerialVersionUID(3L)
  final class ofRef[T <: AnyRef](val unsafeArray: Array[T]) extends ArraySeq[T] {
    lazy val elemTag = ClassTag[T](unsafeArray.getClass.getComponentType)
    def length: Int = unsafeArray.length
    @throws[ArrayIndexOutOfBoundsException]
    def apply(i: Int): T = unsafeArray(i)
    override def hashCode = MurmurHash3.arrayHash(unsafeArray, MurmurHash3.seqSeed)
    override def equals(that: Any) = that match {
      case that: ofRef[_] => Arrays.equals(unsafeArray.asInstanceOf[Array[AnyRef]], that.unsafeArray.asInstanceOf[Array[AnyRef]])
      case _ => super.equals(that)
    }
  }
```

**Comment by SethTisue** [comment]
ping @szeiger, note this is an M5 blocker

**Comment by NthPortal** [comment]
This should be a fairly simple fix of replacing the call to `Arrays.equals` with one to `BoxesRuntime.equals`, yes?

**Comment by szeiger** [comment]
@NthPortal `BoxesRunTime.equals` doesn't deal with arrays. I think we need to iterate through the arrays manually and compare the values with `==` to be consistent with other `Seq`s. Do you want to give it a try?

**Comment by NthPortal** [comment]
@szeiger I can do that. Should this be put in runtime somewhere (e.g. `BoxesRunTime.arraysEquals`?) to be reusable?

**Comment by NthPortal** [comment]
Also, presumably this problem exists for `mutable.ArraySeq.ofRef#equals` as well?

**Comment by retronym** [comment]
> Should this be put in runtime somewhere (e.g. BoxesRunTime.arraysEquals?) to be reusable?

`BoxesRuntime.arraysEquals` sounds sensible to me. 

> Also, presumably this problem exists for `mutable.ArraySeq.ofRef#equals` as well?

Good catch. What's good for the goose is good for the gander.
