### ISSUE TITLE
Plugin phase assembly performs surprisingly poorly with lots of custom phases

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#538]
- [ ] Review this code: https://github.com/scala/scala/blob/71e76e8c056f0dad2447356847433ad33f3321a6/src/compiler/scala/tools/nsc/PhaseAssembly.scala#L109-L119
 - [ ] Write a unit test to provoke the performance problem

**Comment by SethTisue** [comment]
surprised this would ever actually be a bottleneck?

**Comment by retronym** [comment]
The things you spot while on safari.

**Comment by retronym** [comment]
WIP: https://github.com/retronym/scala/tree/opt/phase-assembly

**Comment by som-snytt** [comment]
Define "lots". Since everyone is surprised, maybe edit the title to say "surprisingly poorly".

**Comment by dwijnand** [comment]
Fixed in scala/scala#8295
