### ISSUE TITLE
Use sbt-header to add apache-2.0 license notice to source files

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#549]
Prior work in akka-land: https://github.com/akka/akka-http/pull/1738 (and others in akka/akka).
Prior work in scala-land: https://github.com/scala/scala/pull/5145

**Comment by jvican** [comment]
This is how we do it in sbt/zinc: https://github.com/scalacenter/zinc/blob/1.x-bloop/project/Header.scala The license message can be tweaked.

**Comment by dwijnand** [comment]
Fixed by https://github.com/scala/scala/pull/7306
