### ISSUE TITLE
jvmWiseLub in the backend could be optimized

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#553]
Wouldn't it be better to walk the superclass chain of both types in reverse (starting from `Object`), and
finding the last common link? That would be `O(N)`, whereas the current implementation looks `O(N^2)`

**Comment by diesalbla** [comment]
Which is the method you are referring to?

**Comment by diesalbla** [comment]
@lrytz I have some ideas for this. Have you started working on this?

**Comment by lrytz** [comment]
No I haven't, so please feel free to give it a go!

**Comment by lrytz** [comment]
Ah, there's PRs already 😄
