### ISSUE TITLE
support bootstrapping without `publishLocal` and restarting sbt

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#568]
currently if you make a change that requires re-STARRing, you have to:

1. `sbt setupPublishCore publishLocal`
2. `sbt -Dstarr.version=...`

it would be nicer if it were like Dotty. @smarter wrote on Gitter:

> that's not very convenient, in Dotty we have both non-bootstrapped and bootstrapped projects in the build, so you can just do `dotty-bootstrapped/test` and it does the full bootstrapping process automatically and it's reasonably fast since there's nothing to publish

Gitter discussion at/around https://gitter.im/scala/contributors?at=5bd0a780271506518d639de4

@szeiger wrote:

> AFAIR there were some sbt problems with his approach originally (memory leaks or classpath mix-up). We're doing it for some new test project now (@adriaanm probably remembers). I don't know how well it works there with the much newer sbt

**Comment by dwijnand** [comment]
Done! https://github.com/scala/scala/pull/9160

**Comment by dwijnand** [comment]
As in: you don't need to manually restart sbt, but it does follow the same path, just that it does it for you: publishLocal and then reload the build state with the new `scalaVersion`.

**Comment by SethTisue** [comment]
Agree that this has improved enough. Cost/benefit to further improvement is unclear/dubious.
