### ISSUE TITLE
Non-bootstrapped serialization tests are failing since scala/scala#7297

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#569]
reported by @milessabin on Gitter

@szeiger:
> Non-bootstrapped serialization tests are failing since scala/scala#7297. We need to re-starr to fix that

references scala/scala#7297 and #562

**Comment by SethTisue** [comment]
@retronym:

> Oh, I think I know what you mean. The serialization tests under `junit/test` only work after a round of bootstrapping.
>Arguably they should be `partest`-s to avoid that problem.
>But a re-STARR is fine with me.

**Comment by milessabin** [comment]
Except that there are partests failing as well ...

**Comment by SethTisue** [comment]
@dwijnand it would be helpful to have your proposed Rosetta Stone of what is compiled with what and runs with what, here

**Comment by retronym** [comment]
My comment was wrong, the distinction between JUnit and `partest --run` would only matter if testing serialization of modules defined in the test case. These failures are occuring in modules defined in `src/library`, which is compiled with `STARR` regardless of the test frameworks. CI tests always re-starr on HEAD before running tests (aka "do a fully bootstrapped build").

**Comment by milessabin** [comment]
Is there anything stopping us re-starring now?

**Comment by lrytz** [comment]
We just need to publish a release to maven (or not?)

**Comment by milessabin** [comment]
Is there anything I can do to help with this ... I like to have `testAll` complete successfully locally before PRing, and it failing makes me anxious :scream_cat:

**Comment by retronym** [comment]
We need to trigger a release build to Maven Central for a recent SHA, and then submit a PR to use that in `version.properties`.

The workaround is to locally use:

```
sbt ';setupPublishCore;publishLocal;generateBuildCharacterPropertiesFile' && sbt -Dstarr.version=$(cat buildcharacter.properties |  grep '^maven.version.number=' | cut -d '=' -f 2) testAll
```

**Comment by SethTisue** [comment]
re-STARR PR from @hrhino https://github.com/scala/scala/pull/7430
