### ISSUE TITLE
multiple PRs are green on Jenkins, red on Travis-CI

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#570]
(list has been edited based on comments below)

* https://github.com/scala/scala/pull/7369
* https://github.com/scala/scala/pull/7133 second-to-last commit
* ~~https://github.com/scala/scala/pull/7368~~ never mind
* https://github.com/scala/scala/pull/7199

**Comment by SethTisue** [comment]
Lukas thought at least one of the PRs might be stack size related, not sure what his evidence is

probably no harm in just adding an `-Xss` to `.jvmopts`, now that we have it? the default stack size is liable to be a bit different on different systems, and is always rather small

>Lukas Rytz [4 hours ago]
>i use 5m locally

**Comment by milessabin** [comment]
https://github.com/scala/scala/pull/7368 was a transient failure due to a failed fetch of a binary artefact from a Lightbend repo ... went green on Travis when rerun.

**Comment by milessabin** [comment]
One step forward, one step back ...

https://github.com/scala/scala/pull/7199 is now failing with a SOE on Travis, after rebasing. In this case at least, the failure is after bootstrapping.

**Comment by retronym** [comment]
Pattern matching is now generating additional null checks. I'm guessing this is an intended consequence of moving it after refchecks.

These extra null checks are doubling the tree depth of the translated patterns, which was already pretty big for some of the high-arity tuple matches in `StandardLiftables`.

I'll dig further.

![image](https://user-images.githubusercontent.com/65551/47630211-420ebf80-db8b-11e8-9651-38e1a6991dcf.png)

**Comment by retronym** [comment]
Okay, that change comes down to a slightly older, intentional change to null handling with extractors: scala/scala#6485

Maybe we should change patmat to emit:

```
if (p5.eq(null) case12()
<next pattern>
```

Rather than:

```scala
if (p5.ne(null)) { <next pattern> } else case12()
```

WIP: https://github.com/scala/scala/compare/2.13.x...retronym:topic/shallower-patmat-ast?expand=1

**Comment by sjrd** [comment]
The Scala.js backend won't be happy at all if you do that. It's very sensitive to the shapes of trees produced by the pattern matcher. The function `genTranslatedMatch` in [`GenJSCode`](https://github.com/scala-js/scala-js/blob/0.6.x/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala) would have to be rewritten.

**Comment by retronym** [comment]
Thanks for the heads up, @sjrd. We'll be make sure to allow time for that re-write, or otherwise, we can make the status quo available under a migration option of some sort.

**Comment by lrytz** [comment]
Just saw the SOE on the most recent merge commit in 2.13.x, which includes the `-Xss1m`
  - https://github.com/scala/scala/commits/2.13.x, 5adfbf1
  - https://travis-ci.org/scala/scala/jobs/451900187

**Comment by SethTisue** [comment]
gah, not sure what to do here, earliest I could look at it or think about it is next week

**Comment by milessabin** [comment]
Is there any reason for not being a bit more generous with heap and stack? I use 3g and 2m respectively for shapeless.

**Comment by lrytz** [comment]
I guess we'd like to understand why this started happening recently and keep some pressure to do something about it. But the cost of having spurious failures over and over again is probably a bit too high. So I'm happy to bump to 2m.

**Comment by SethTisue** [comment]
SGTM. we could leave this ticket open unless or until we decide do something else

**Comment by retronym** [comment]
Want to try https://github.com/scala/scala/pull/7375 first?

**Comment by SethTisue** [comment]
I don't recall seeing this happen recently
