### ISSUE TITLE
plan for having `_` mean placeholder function syntax, `?` mean wildcard / existential

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#576]
currently, `_` means existential quantification at the type level

we would like to use `?` instead, and use `_` for placeholder function syntax at the value and type level

(its use for anonymous higher-order type params remains)

this means we'd need a version of scala where both `_` and `?` are valid for denoting wildcards, but this would mean claiming the `?` identifier as a reserved keyword, which would break kind-projector

at the same time, we'd add support for type lambdas (`[X] => Foo[X]`)

**Comment by SethTisue** [comment]
Martin opened a similar ticket at https://github.com/lampepfl/dotty/issues/5379

**Comment by SethTisue** [comment]
there isn't anything to change we need to change for 2.13, I think? hence, optimistically, 2.14 milestone?

**Comment by SethTisue** [comment]
out of scope for Scala 2
