### ISSUE TITLE
to assist MiMa, 2.12 should emit lambda methods with ACC_SYNTHETIC

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#58]
details at https://github.com/typesafehub/migration-manager/issues/78

@retronym suggests digging through the archives, first, though, to make sure what implications this might have outside the context of MiMa

Java ACC_SYNTHETIC is Scala Flags.ARTIFACT (Flags.SYNTHETIC means something else — it means synthesized by the compiler, but doesn't mean invisible from other sources)

**Comment by bantonsson** [comment]
This might not be necessary since typesafehub/migration-manager#92 will ignore methods containing`$anonfun$` as well as methods marked `ACC_SYNTHETIC`, but it might help other tools to ignore methods that the user shouldn't see.

**Comment by SethTisue** [comment]
the IntelliJ folks might want a heads up on this, e.g. for the IntelliJ debugger. ScalaIDE too, perhaps?

**Comment by SethTisue** [comment]
Jason and I discussed the "implications this might have outside the context of MiMa" and convinced ourselves that we remain comfortable with the change. there was a side discussion about whether the generated methods will even continued to be generated as public, since if not public they would no longer issue for MiMa, but Jason thinks they will stay public though they might become static (with additional explicit `this`-parameter if needed) since we really don't need them to be virtual

in any case, at the same time we make this change we should consider what other methods ought also to be marked ACC_SYNTHETIC for consistency's sake. to consider, for instance:
- lambda-lifted local methods (generated as private so not a MiMA concern — though perhaps the old optimizer would make it public at inlining time? not sure. there's a tension between cross-compilation-unit inlining and making things private) (@retronym expand on this?)
- artifacts of lazy val encoding (compute methods)
- initializers?
- (maybe just take a look at some compiled code and look for public methods with $ in them that aren't currently ACC_SYNTHETIC?)

even things which aren't concerns for MiMa may still be desirable to generate ACC_SYNTHETIC in order to hide them from e.g. IDE auto-completion when Java code calls Scala code

**Comment by SethTisue** [comment]
(mostly tangential, but, some past chapters in the book of ACC_SYNTHETIC: https://issues.scala-lang.org/browse/SI-6821, https://groups.google.com/forum/#!searchin/scala-internals/ACC_SYNTHETIC/scala-internals/0E52ISdzeWg/6p8hxmkY0KgJ, https://github.com/scala/scala/commit/edf94d0baf, https://issues.scala-lang.org/browse/SI-1128)

**Comment by SethTisue** [comment]
haha, what made us think it didn't already?
