### ISSUE TITLE
Deprecate spec-defined and standard-library-defined unicode operators (⇒, ←, →)

### ISSUE THREAD

**Issue by smarter** [scala/scala-dev#585]
From [the spec](https://www.scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html):

> The Unicode operators \u21D2 ‘⇒’ and \u2190 ‘←’, which have the ASCII equivalents => and <-, are also reserved.

And from the [standard library](https://github.com/scala/scala/blob/cac6383e6658dc5956540b76b9b46c3b664774ac/src/library/scala/Predef.scala#L249):
```scala
  def →[B](y: B): Tuple2[A, B] = ->(y)
```

While they're very cute, they're all likely to confuse users for very little benefits. And people who like symbols can simply use a coding font with special ligatures such as [Fira Pro](https://github.com/tonsky/FiraCode) which does a much better job at solving this problem.

(It's also worth noting that → in particular is problematic because it doesn't have the same associativity as `->`: https://github.com/scala/bug/issues/11210)

**Comment by propensive** [comment]
I was casually wondering whether there's an appropriate Unicode character for `|=>`, but just removing these aliases works fine for me, too.

**Comment by ctongfei** [comment]
@propensive You have `U+2907` `⤇`, or a longer one `U+27FE` `⟾`.

**Comment by He-Pin** [comment]
Currently, Akka itself seems using the shorter one by too, For me, the `→` is not easy to type and I  had to find wtf is `→` in the spec. I would be great to remove these shorter things in the standard library especially when someone is the curiosity to wonder there.

**Comment by dwijnand** [comment]
> For me, the `→` is not easy to type

(JFYI, when Akka compiles it'll reformat `->` into `→` so you don't have to type it.)

**Comment by He-Pin** [comment]
@dwijnand I mean if I want to type it:relaxed:

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Galaxy Note8 发送_
