### ISSUE TITLE
Lambdalift ABI stability

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#590]
[This change to lambdalift](https://github.com/scala/scala/commit/69d60cb54d787a90c74de092cc5173e12a1087fb#diff-2f45caef596e9f417399a96ad4a16451) causes the args of lambdalifted local methods to appear in order of usage, rather than  based on the order of type checking (the former is stable across compiler runs, whereas the latter is potentially sensitive to  compilation order, which is why it was changed).

The question is now, how can captured locals be sensitive to compilation order? This change has not caused binary incompatibilities, technically speaking, since these methods are more than private, but it causes perhaps unwanted changes all the same. It will also mean that changing the order of usage of method arguments will result in different byte code.

Reproducer:
```
➜  /tmp ~/scala/scala-2.12.8/bin/scalac -Xprint:lam /Users/adriaan/Library/Preferences/IdeaIC2018.2/scratches/scratch_63.scala
[[syntax trees at end of                lambdalift]] // scratch_63.scala
package <empty> {
  class C extends Object {
    def <init>(): C = {
      C.super.<init>();
      ()
    };
    def meh(): Unit = {
      val x: Int = 1;
      val y: Int = 1;
      ()
    };
    final private[this] def local$1(y$1: Int, x$1: Int): Int = y$1.+(x$1)
  }
}
```

```
➜  /tmp ~/scala/scala-2.12.7/bin/scalac -Xprint:lam /Users/adriaan/Library/Preferences/IdeaIC2018.2/scratches/scratch_63.scala
[[syntax trees at end of                lambdalift]] // scratch_63.scala
package <empty> {
  class C extends Object {
    def <init>(): C = {
      C.super.<init>();
      ()
    };
    def meh(): Unit = {
      val x: Int = 1;
      val y: Int = 1;
      ()
    };
    final private[this] def local$1(x$1: Int, y$1: Int): Int = y$1.+(x$1)
  }
}
```

**Comment by retronym** [comment]
@adriaanm Just to confirm my understanding, this is not reporting a compiliation-order dependent change in bytecode (a violation of compiler determinism), but rather showing that a) things changed between 2.12.7->8  and b) that the order of the captures in the lifted signature is dependent of reference order, not declaration order.

I suppose we could order them by the order that the referenced definitions appear in the tree. This could either be done with a position based sort, or with another pass if we want this to work for trees without positions (e.g. synthesized code where everything is at the same position).

Personally I don't think it is worth it. There is always going to be a tight coupling between the signature of the lifted method and the code from which it is lifted.

**Comment by adriaanm** [comment]
Ok, thanks for looking deeper. I admit I quickly scanned and saw keywords that justified pinging you :-)

**Comment by adriaanm** [comment]
Right, it’s still stable, but it makes it harder to maintain stability at the source level (you’re more likely to move references around and expect the abi to be unaffected).

**Comment by adriaanm** [comment]
Agreed that this can be caught by tooling and remedied manually, and that’s likely sufficient to not change this logic back. 

(I deleted my earlier comment because I had mixed up two issues.)

**Comment by dwijnand** [comment]
> (you’re more likely to move references around and expect the abi to be unaffected).

Personally I feel like the type signature of the "more than private" method that lambda's lift out into isn't "ABI".

I don't think this needs addressing, and probably we can't in 2.13.
