### ISSUE TITLE
enable scalafmt on codebase?

### ISSUE THREAD

**Issue by He-Pin** [scala/scala-dev#593]
I think it would be nice to enable automatically formating on the code base, after that it will be easy to handle alignment and space like things for contributors.
cc @olafurpg

**Comment by da-liii** [comment]
I do not think scalafmt is a good idea.

**Comment by yangbajing** [comment]
Good idea, scalafmt is easier to use than scalariform.

**Comment by He-Pin** [comment]
could take some baby step, which will make contribution easier, scalaz,akka both have this kind of thing ,even sbt now adays.

**Comment by NthPortal** [comment]
I'm not sure this is a good idea. As @SethTisue noted at some point in gitter, there is a lot of bespoke formatting in the codebase.

**Comment by He-Pin** [comment]
> I'm not sure this is a good idea. As @SethTisue noted at some point in gitter, there is a lot of bespoke formatting in the codebase.

Which could be protected with `scalafmt:off` block IIRC.

**Comment by olafurpg** [comment]
@hepin1989 I don't think it's a good idea to spread `scalafmt:off` to large parts of the scala/scala codebase. This repository contains a lot of valuable git history so I share the hesitation to enable Scalafmt.

**Comment by He-Pin** [comment]
@olafurpg That's true, but how about just turn it on for `=` alignment and space insertion, which only change a single line.

**Comment by olafurpg** [comment]
@hepin1989 there's no option to disable line wrapping within `maxColumn`. Scalariform is a better fit if you only want alignment and to fix spaces.

**Comment by He-Pin** [comment]
Let me close this, thank you all. contributors could do a local format first to keep them formatted properly.

**Comment by SethTisue** [comment]
idk, but perhaps the outcome on this might be different over in lampepfl/dotty
