### ISSUE TITLE
PR validation is broken

### ISSUE THREAD

**Issue by NthPortal** [scala/scala-dev#594]
Both of the `validate-main` and `cla` statuses are not reporting (e.g. see scala/scala#7579)

**Comment by adriaanm** [comment]
Thanks for letting us know! I've attempted a fix for a few exceptions I was seeing in the logs, and it appears it's at least partially back. The remaining issue with the CLA checker is probably a certificate issue -- our lightbend.com cert was changed last weekend. https://github.com/scala/scabot/issues/92

**Comment by adriaanm** [comment]
more seems to be broken... I upgraded jenkins because there was another round of CVEs, but now read permission for anonymous users is no longer respected, so you have to log in before you can see a job's status... this could be breaking scabot, although i think it authenticates for each api call

**Comment by adriaanm** [comment]
I've now also upgraded all jenkins plugins. Jenkins restarted ok 😅, and now those pages are showing again in an incognito window.

**Comment by NthPortal** [comment]
Thanks for taking care of this @adriaanm!
