### ISSUE TITLE
compile stdlib & compiler with fatal-warnings / deprecations

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#600]
this will likely require some error filtering, but it would be good to clean house  a little in the warning department

**Comment by som-snytt** [comment]
Maybe Snow White could get all the little forest animals to help.

**Comment by som-snytt** [comment]
I think I hear Snow singing to me [right now](https://github.com/scala/scala/pull/7069#issuecomment-460410688).

**Comment by som-snytt** [comment]
I ought to find time by the weekend for https://github.com/scala/scala/pull/7728.

**Comment by som-snytt** [comment]
In [this attempt](https://github.com/scala/scala/pull/8653) to turn up warnings, deprecations are harmed by early defs, plus everything getting deprecated. The other big style category is unused pattern variables, which I used to think was excessive, but now I think is appropriate: Don't introduce a variable if you don't intend to use it. That's not turned on by -Xlint:unused yet. As a reminder, the escape hatch for that is:
```
case P(x @ _) =>
```

**Comment by SethTisue** [comment]
configurable warnings has just landed, but we won't be able to start using it ourselves until we re-STARR on 2.13.2

**Comment by soronpo** [comment]
I might get in on this action. How is it preferable to submit PRs for this? One big one with separate commit for every silencing? Separate PRs for batches of silencing that differ in type of warning?

**Comment by SethTisue** [comment]
also see what others have to say, but I was vaguely imagining going module by module, with the goal of being able to enable` -Werror` module by module as well. (probably with an easy switch to flip to interactively disable it during development)

**Comment by dwijnand** [comment]
👨‍🎨 let's only enable `-Werror` in CI, where it matters, as it's (IMHO) a needless inhibition during dev to not run tests because of an unused import somewhere.  Whether that's `if CI then add` or `if localDev then remove` I don't mind.

1 PR with a commit per silencing type, IMO.  E.g. commit-1: silence this warning for reason X - here's the warning output before, commit-2: silence this warning for reason Y - here's the warning output before, etc.

**Comment by SethTisue** [comment]
we have now re-STARRed on 2.13.2, so we're free to progress on this now

My own first PR in this area has now been merged: https://github.com/scala/scala/pull/8964 . Further PRs like this from contributors are strongly encouraged!

> let's only enable -Werror in CI, where it matters

This remains an open question. I agree that it at minimum, it ought to be verrrrry easy to be more lenient when doing local development. I'm not sure what I think about what the default ought to be. If during local development all it took to switch to lenient mode were a single command (`yolo`), that might be okay?

To have to remember to switch would admittedly be annoying, but the alternative has its own annoying-ness as well: you submit a PR that was fine locally, and then all of a sudden CI is like, ohhhhh no you don't.

**Comment by NthPortal** [comment]
> To have to remember to switch would admittedly be annoying, but the alternative has its own annoying-ness as well: you submit a PR that was fine locally, and then all of a sudden CI is like, ohhhhh no you don't.

Having experienced this at work, I can say that your PR suddenly failing when it built locally is annoying; at the same time, some build tools (e.g. VSC with Metals) become difficult or frustrating to use when you can't even temporarily have errors. For example, if you lint the various "unused"s, you'll get unused import errors constantly during development.

**Comment by som-snytt** [comment]
Having a PR fail because of `-Werror` is almost as annoying as failing because of bootstrapping.

Similar problem still to solve is transient warnings in REPL. Maybe it will be to show `*` marker on result line to mean warnings, or warning on third attempt.

**Comment by soronpo** [comment]
> Having experienced this at work, I can say that your PR suddenly failing when it built locally is annoying; at the same time, some build tools (e.g. VSC with Metals) become difficult or frustrating to use when you can't even temporarily have errors. For example, if you lint the various "unused"s, you'll get unused import errors constantly during development.

Then perhaps it's possible to make it so that only the official CI will reject a build with warnings.

**Comment by NthPortal** [comment]
> Then perhaps it's possible to make it so that only the official CI will reject a build with warnings.

It is, and that's what we do at work (by default; you can enable fatal warnings locally if you want). It still ends up being annoying either way though.

**Comment by dwijnand** [comment]
* https://github.com/scala/scala/pull/9235,
* https://github.com/scala/scala/pull/9237, and
* https://github.com/scala/scala/pull/9242

Thank you, @NthPortal!

**Comment by SethTisue** [comment]
@NthPortal are there remaining pieces of this that are still undone? if there are additional subprojects that still need work, perhaps we could make a list of them and distribute them to volunteers.

**Comment by NthPortal** [comment]
yes, there are additional sub-projects. They tend to be quite easy to deal with, so I've usually been able to do them with a single commit. I'll try to finish up and push what I've already worked on and make a list of what's left

**Comment by som-snytt** [comment]
That's good, because Seth really meant that you could make a list and then volunteer to do them.

**Comment by NthPortal** [comment]
scala/scala#9304 handles `scalap` and `scaladoc`.

Still TODO:
- modules (in the order that they appear in `build.sbt`)
  - `partest`
  - `tastytest`
  - `specLib`
  - `bench` (maybe)
  - `testkit`
  - `junit`
  - `tasty`
  - `scalacheck`
  - `osgiTestFelix` (?)
  - `osgiTestEclipse` (?)
  - `partestJavaAgent`
- enable warnings (and thus errors) in `doc` stage when fatal warnings are enabled

**Comment by NthPortal** [comment]
that made me laugh @som-snytt, and I'm a little sad you deleted it

**Comment by SethTisue** [comment]
@NthPortal thanks! I've put that in a new ticket (#737)
