### ISSUE TITLE
Reconsider allowing trait extends class?

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#601]
It doesn't actually mean the trait extends the class (just that a subclass of the trait must), and is redundant with having the class in the trait's self type.

**Comment by sjrd** [comment]
Traits extending classes is a very important pattern for Scala.js. With a self type you can't just do `new TheTrait {}` as it won't compile:
```scala
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions for evaluation. Or try :help.

scala> class A
defined class A

scala> trait B { this: A => }
defined trait B

scala> new B {}
<console>:13: error: illegal inheritance;
 self-type B does not conform to B's selftype B with A
       new B {}
           ^

scala> trait C extends A
defined trait C

scala> new C {}
res1: A with C = $anon$1@6c830ebd
```
This is very important in Scala.js as we use traits to define the interface that certain POJOs need to implements, as in:
```scala
trait Point extends js.Object {
  def x: Int
  def y: Int
}
```
where `js.Object` is a `class` from the standard library. It then allows call sites to write
```scala
callFunThatExpectsAPoint(new Point {
  val x: Int = 5
  val y: Int = 6
})
```
which wouldn't be possible if `Point` did not actually *extend* `js.Object`.

We cannot make `Point` a class either, as that breaks the property that `Point`s are POJOs, and then some JavaScript libraries will throw `TypeError`s on purpose for that.

**Comment by Jasper-M** [comment]
It seems to me that all uses of self-types that don't involve cyclic dependencies or type parameters are redundant in some sense. Except that it changes the subtype relationship.

**Comment by adriaanm** [comment]
Fair enough :-)

**Comment by SethTisue** [comment]
another trait-extends-class use case: https://stackoverflow.com/questions/3299776/in-scala-how-can-i-subclass-a-java-class-with-multiple-constructors/3299832#3299832

**Comment by adriaanm** [comment]
Technically we could make self types behave to fully subsume a trait
extending a class by using it as the type to instantiate whenever the
instantiated type otherwise would be abstract

**Comment by dwijnand** [comment]
How does Point being a class make it not a POJO?

**Comment by sjrd** [comment]
Because a POJO's direct prototype must be `Object.prototype`. It's the definition of POJO. If `Point` is a class, the direct prototype of its instances would be `Point.prototype`, not `Object.prototype`.
