### ISSUE TITLE
recent 2.13.x change broke compiler bridge in scala-dist-smoketest

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#602]
at e.g. https://travis-ci.org/scala/scala-dist-smoketest/builds/483980520 we see

```
/tmp/sbt_c8e64c05/xsbt/ExtractAPI.scala:334: error: value isLocal is not a member of ExtractAPI.this.global.Symbol
      !(s.isPrivate && (s.privateWithin == NoSymbol || s.isLocal))
                                                         ^
one error found
```

looks like the relevant commit is scala/scala@5b8f9280de23d29ae960329cffc3a2d9a03f3eae, /cc @joroKr21

**Comment by SethTisue** [comment]
it shouldn't fall only on scala-dist-smoketest to catch this, the community build ought to be catching it too. the community build includes sbt, but sbt has a ton of dependencies and hasn't been ported to 2.13 yet. the community build ought to build the compiler bridge by itself. I'll look into it.

**Comment by SethTisue** [comment]
about whether the community build catches this, https://github.com/scala/community-builds/issues/842

**Comment by joroKr21** [comment]
Should we bring this method back?

**Comment by SethTisue** [comment]
yes please, I think we have to. with an appropriate comment or deprecation message. there are others scattered around the code, `@deprecated("shim for sbt's compiler interface", since = "2.12.0")` and so on

**Comment by joroKr21** [comment]
> `@deprecated("shim for sbt's compiler interface", since = "2.12.0")`

Hmm, I'm not sure if this should be part of the deprecation message or just a comment in the code.

**Comment by joroKr21** [comment]
scala/scala#7682

**Comment by SethTisue** [comment]
keeping open until I've seen scala-dist-smoketest green

**Comment by SethTisue** [comment]
https://travis-ci.org/scala/scala-dist-smoketest/builds/484440499 👍

**Comment by SethTisue** [comment]
thank you Georgi!
