### ISSUE TITLE
Deforest enclosingContextChain

### ISSUE THREAD

**Issue by diesalbla** [scala/scala-dev#604]
I recently [noticed](https://github.com/scala/scala/pull/7732#discussion_r255335630) that, in the code in question, the method `enclosingContextChain: List[Context]` from the `Context` class was called to create a list of contexts that was immediately deconstructed. It seems that, in many other calls to this method, the list is created and immediately consumed, with the unneeded allocation. 

The goal of this issue is to avoid the list allocation of the calls `enclosingContextChain`, either by:  
- Replacing the call to `enclosingContextChain` with a comparison to `NoContext` and a call to `outer`, as was done in that PR, with no deallocation; or
- by changing the type of that method to `Iterator[Context]`, that can be used to iterate through the context chain, with constant allocation (the iterator).

**Comment by RichardMarto** [comment]
I'll be glad to do it.

**Comment by diesalbla** [comment]
So, I was thinking that the problem of the second solution is that it requires an allocation (creating the iterator) for every call. Whereas the first solution requires repeating the recursion with every function, and it would have to be repeated for different data types. 

I was thinking that there could be a third way to implement these functions, and it is by replacing the iterator by its two key functions, `hasNext` and `next`. For instance, 

```Scala
def existsBy[A](pred: A => Boolean)(next: A => Option[A], curr: A): Boolean = 
   /***/
```

The parameters of type function, although themselves objects, need only be allocated once in the whole execution.

**Comment by RichardMarto** [comment]
Sounds good to me.

**Comment by RichardMarto** [comment]
So, I'm trying to implement your third solution, but I'm not sure about how to replace the iterator with his methods. Should return the `hasNext()` and `next()` from `enclosingContextChain()`, change the signature and then replace his usage ?

**Comment by diesalbla** [comment]
@RichardMarto I think the second solution may be good enough. There are other places where one iterator allocation is acceptable.

**Comment by diesalbla** [comment]
On second thoughts, I am not certain if this is a major allocation hotspot for the compilation. May not be worth keeping open.
