### ISSUE TITLE
re-STARR (February 2019)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#605]
it's been quite a while (scala/scala#7430) since we re-STARRed

and the desire for it came up at https://github.com/scala/scala/pull/7069 /cc @som-snytt 

Adriaan suggested re-STARR-ing after the RC1 queue is empty, but I'd like to do it now, also. if nothing goes wrong, then no harm done, and if something does go wrong, we'll have bought ourselves more time to deal with it

**Comment by SethTisue** [comment]
https://travis-ci.org/scala/scala/builds/494065488 triggered with `SCALA_VER_BASE=2.13.0 SCALA_VER_SUFFIX=-M5-1775dba`

**Comment by SethTisue** [comment]
(well it took some fumbling and a few tries, but:)

https://travis-ci.org/scala/scala/builds/494075656 triggered with 

```
env:
- SCALA_VER_BASE=2.13.0 SCALA_VER_SUFFIX=-M5-1775dba
```

**Comment by SethTisue** [comment]
`if (goLookingForTrouble()) findTrouble()`

```
<set>:1: error: not found: value pgpSigningKey
pgpSigningKey in Global := Some(new java.math.BigInteger("C03EF1D7D692BCFF", 16).longValue)
^
[error] Type error in expression
```

**Comment by SethTisue** [comment]
problem with `admin/init.sh`? it does `mkdir -p ~/.sbt/1.0/plugins; cp files/gpg.sbt ~/.sbt/1.0/plugins/`, if that doesn't happen or doesn't work, that would account for `pgpSigningKey` not being recognized

log has:

```
$ (cd admin && ./init.sh)
The command "(cd admin && ./init.sh)" exited with 2.
```

`init.sh` has

```
# don't let anything escape from the sensitive part (e.g. leak environment var by echoing to log on failure)
sensitive >/dev/null 2>&1
```

which probably accounts for why there's no information in the log about what went wrong, precisely

**Comment by SethTisue** [comment]
I think I must be triggering the job wrong, such that `GPG_SUBKEY_SECRET` doesn't end up being set. maybe because my `env:` section just wipes out the `env:` section in `.travis.yml` with the `secure:` entries

**Comment by SethTisue** [comment]
that hypothesis seems confirmed by the following:

at https://travis-ci.org/scala/scala/jobs/455143463 (the job from 
https://github.com/scala/scala/pull/7430), the log has

```
Setting environment variables from .travis.yml
$ export PRIV_KEY_SECRET=[secure]
$ export PRIVATE_REPO_PASS=[secure]
$ export SONA_USER=[secure]
$ export SONA_PASS=[secure]
$ export GPG_SUBKEY_SECRET=[secure]
$ export TRAVIS_TOKEN=[secure]
```

whereas in 
https://travis-ci.org/scala/scala/builds/494075656's log, it just says

```
Setting environment variables from .travis.yml
$ export SCALA_VER_BASE=2.13.0
$ export SCALA_VER_SUFFIX=-M5-1775dba
```

**Comment by SethTisue** [comment]
after some poking around in the log from last time trying to figure out how it might have been triggered (is this information in the Travis web UI somewhere? I don't see it), I think we need to trigger the job like this:

```
before_install:
- export SCALA_VER_BASE=2.13.0 SCALA_VER_SUFFIX=-M5-1775dba
```

https://travis-ci.org/scala/scala/jobs/494095687

**Comment by som-snytt** [comment]
Thanks, Seth! Let's re-STARR on a Friday! I wish I could help beyond going, 🎶 You are my lucky STARR.  A new STARR makes every holiday more festive. Is this for Valentine's or President's Day?

I really needed it because of https://github.com/scala/scala/pull/7350 which crashes unbootstrapped linting.

**Comment by SethTisue** [comment]
STARR light, STARR bright, first STARR I staged tonight: `Closed sonatype staging repos: https://oss.sonatype.org/content/repositories/orgscala-lang-1697` 🕺

**Comment by SethTisue** [comment]
nobody watch this pot or it'll never boil: https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.0-M5-1775dba/

**Comment by SethTisue** [comment]
Bill Clinton called, says he wants a different Starr, too

**Comment by som-snytt** [comment]
I was going to make a pot joke, but you nailed it.

(Edit: I just remembered, "I never inhaled.")

**Comment by adriaanm** [comment]
On a more prosaic note, the Travis InCantation is documented in https://github.com/scala/scala-dev/blob/scala-dev/.github/ISSUE_TEMPLATE/release.md
