### ISSUE TITLE
Proposal: Adopt Scalafmt in the Scala compiler project

### ISSUE THREAD

**Issue by diesalbla** [scala/scala-dev#619]
I have thought of this issue for a while, but this PR https://github.com/scala/scala/pull/7871 brought it to the fore. 

Like all major open source projects, the code of the Scala compiler should have a defined style rule-book that is applied consistently across the codebase. In the case of Scala, we have  the possibility of automatically enforcing several of those style rules, by using the [Scalafmt](https://scalameta.org/scalafmt/) tool. This tool provides: 

- A way to re-format existing code, or code modified by a writer, in accordance to those rules.
- A check in the build, to reject in the CI any new code that do not conform to that style. 

The goal of this issue would be to add into the [Scala project](https://github.com/scala/scala) a `scalafmt` rules, and configure it.

**Comment by OberstK** [comment]
As the one bringing this into the linked PR (even if it’s by accident) I highly support something like this. It’s a given that the linked PR should have been checked more carefully for broad useless format changes like these but enforcing a rule within the project could make the contribution process easier for everyone on my eyes.

Specific personal coding styles aside, it should also not be too hard to at least find a base set of rules everyone can live with in my opinion.

**Comment by Jasper-M** [comment]
Some recent history: https://github.com/scala/scala-dev/issues/593

**Comment by NthPortal** [comment]
I think the general guidelines are "only format lines/sections you change" and "disable option to format on save"

**Comment by hrhino** [comment]
Yes, let's not. As @olafurpg pointed out the first time around (https://github.com/scala/scala-dev/issues/593#issuecomment-446593061), the massive diff would occlude much of the ~16 years of git history in the Scala repo, which is valuable information when searching for the rationale underlying a certain change.

Perhaps this would be defensible if scala/scala were a new or young codebase, but at this point adopting scalafmt will be painful and dubiously gainful.

**Comment by adriaanm** [comment]
In addition to losing history, it's also a source of gratuitous diffs and their resulting merge conflicts. I'm fine with reformatting code you're changing anyway, but minimal patches really simplify the jobs of us maintainers who look at tons of diffs, sometimes with an unfortunately low SNR due reformatting etc.
