### ISSUE TITLE
Scaladoc nightlies not being published?

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#621]
https://www.scala-lang.org/files/archive/nightly/2.13.x/api/2.13.x/ has docs corresponding to https://github.com/scala/scala/commit/81ad83d (Jan 31, 2018). I haven't done any investigation why that is, or if it's even expected?

**Comment by SethTisue** [comment]
duplicate of https://github.com/scala/scala-lang/issues/929 ?

**Comment by lrytz** [comment]
👍

**Comment by eloots** [comment]
@SethTisue What eludes me is if there is a more recent version of the docs and where is it to be found?

**Comment by SethTisue** [comment]
there isn't, that's what the linked ticket is about.

we should still fix that ticket, but for now, RC1 is imminent so you'll be able to consult the RC1 docs quite soon, it's only nightly-build doc publishing that's broken, actual releases like M5 and RC1 aren't affected

in the meantime you can always generate the doc locally by running `sbt doc` in scala/scala, then the root of the doc is `build/scaladoc/library/index.html`
