### ISSUE TITLE
Jenkins 2.11-on-Windows job needs updating for JDK 8

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#631]
https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-windows/ always fails now with

```
y:\jenkins\workspace\scala-2.11.x-integrate-windows\build.xml:504: JDK 1.6 is not supported by this build!
```

**Comment by SethTisue** [comment]
I've assigned myself so that _somebody_ fixes it eventually, but feel free to work-steal it from me :-)

**Comment by SethTisue** [comment]
@adriaanm do you know how the 2.12 and 2.13 jobs are able to get Java 8? I couldn't find it, I feel like I must be missing something obvious

**Comment by adriaanm** [comment]
I suppose it's this: https://github.com/scala/scala/blob/2.11.x/scripts/jobs/integrate/windows#L7

(as you suspected :-))

**Comment by adriaanm** [comment]
I assume the default is Java 8, so removing those (and bumping STARR) should do it. I'll submit a PR

**Comment by adriaanm** [comment]
I ended up just pushing a commit, since this wouldn't be caught by CI anyway: https://github.com/scala/scala/commit/d37ff076906a7bb1e09877654bca77becf3f350e

Testing at https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-windows/1426

**Comment by SethTisue** [comment]
working
