### ISSUE TITLE
Publish testkit 2.13.0

### ISSUE THREAD

**Issue by sjrd** [scala/scala-dev#635]
`"org.scala-lang" % "scala-partest" % "2.13.0"` is published on Maven, but it depends on `testkit`, which was not published due to https://github.com/scala/bug/issues/11529. That issue is being resolved in https://github.com/scala/scala/pull/8056 for future versions, but that doesn't fix it for the already released 2.13.0.

I'd very much like testkit to be published for 2.13.0, because it's required for running the partest suite in the Scala.js build.

Any chance it could be published? Thanks!

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/8056 is merged

**Comment by dwijnand** [comment]
Hey @sjrd.  The change wasn't last minute, so I wonder: how have you been managing to run the partest suite in the Scala.js build so far (in RC2, RC3, etc)?  What's change to make this (as I'm perceiving it from you) urgent?

Asking not because it's a problem, but just to judge the urgency and impact.

**Comment by sjrd** [comment]
> how have you been managing to run the partest suite in the Scala.js build so far

I haven't. We've been partially blind in that respect.

> Asking not because it's a problem, but just to judge the urgency and impact.

It's not urgent, but it would be really nice to eventually get it even for 2.13.0 (even after 2.13.1 is released) so that we can start testing more thoroughly that our compiler plugin does the right thing in all of the corner cases of the 2.13.0 compiler.

**Comment by SethTisue** [comment]
I simply forgot about this ticket. @sjrd are you still interested? if so, I could tackle this

**Comment by sjrd** [comment]
Well I still haven't taken the time to re-set up partest for 2.13.x in Scala.js, so ... I guess it's not urgent.

**Comment by SethTisue** [comment]
Okay. Closing the ticket, but we can always reopen.
