### ISSUE TITLE
CI runs (both Jenkins and Travis) failing, our Artifactory is out of disk space

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#636]
```
[error] (reflect / publish) java.io.IOException: PUT operation to URL https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots;build.timestamp=1560873098981/org/scala-lang/scala-reflect/2.13.1-bin-36746c6-SNAPSHOT/scala-reflect-2.13.1-bin-36746c6-SNAPSHOT.pom failed with status code 413: Request Entity Too Large
```

on jenkins-master, `/dev/xvdk       493G  443G   28G  95% /var/opt/jfrog/artifactory/data`

@eed3si9n found this bit of doc:

> Once disk space used for storage reaches the specified limit, any attempt to deploy a binary is rejected by Artifactory with a status code of  413 Request Entity Too Large and a "Datastore disk space is too high" error is displayed at the bottom of the Maintenance screen.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/artifactory/webapp/#/admin/advanced/storage_summary shows that scala-pr-validation-snapshots is the culprit, it's using 200G+

(and anyway it's better to wipe out PR validation builds than nightlies, wiping out old 2.13.0-pre- nightlies would be no great loss, either. but better to do PR validation builds first)

**Comment by SethTisue** [comment]
"Artifactory supports cleanup by allowing you to write custom User Plugins which you can develop to meet your own specific cleanup requirements" 😱

**Comment by SethTisue** [comment]
poll:

:+1: = just go ahead and delete all 200G+ of old JARs
:-1: = maybe ask @adriaanm first

**Comment by hrhino** [comment]
could a User Plugin be written to remove validation builds from all and only closed PRs? If a PR is merged then there's presumably a nightly containing just or near-just that PR's change. 

Obviously nightlies will also eventually fill up; for them, maybe a sensible policy is to keep all nightlies since the last release on that branch? idk.

**Comment by SethTisue** [comment]
The problem is that I really don't want to mess with writing a Groovy script to implement some sort of selective culling, I would strongly prefer to do something else with my time :-/

>  If a PR is merged then there's presumably a nightly containing just or near-just that PR's change.

indeed, the only difference is the merge commit.

to my knowledge, the nightlies are what everybody actually uses to bisect regressions.

note that "nightly" is a misnomer; they exist for every merge commit. Adriaan calls them "mergely" builds.

**Comment by SethTisue** [comment]
I'm currently using https://scala-ci.typesafe.com/artifactory/webapp/#/artifacts/browse/tree/General/ to manually delete folders under scala-pr-validation-snapshots that are obviously not needed anymore, stuff like scala-partest, scala-testkit (wtf even is that?), scala-library-all, etc. I'll see how much space that frees up.

**Comment by SethTisue** [comment]
Adriaan and Eugene agree that just blowing away everything under scala-pr-validation-snapshots and starting over is fine

I'm finding that just deleting stuff isn't enough in itself to reclaim the actual disk space. consulting https://www.jfrog.com/jira/browse/RTFACT-272 for advice

**Comment by SethTisue** [comment]
first you have to select the trash in the artifact browser and choose "empty trash"

but the space isn't immediately reclaimed.

https://scala-ci.typesafe.com/artifactory/webapp/#/admin/advanced/maintenance offers many attractive looking options like "garbage collection", "prune unreferenced data", and the like. I'll click on all of them! and maybe `sudo systemctl restart artifactory.service` for good measure

**Comment by SethTisue** [comment]
"Garbage Collection" has been spinning for a long time now and is graaaaaaaaaaaadually coughing up disk space. As in, it took something like 30 minutes to cough up, so far, 9GB. I don't even know how long it was because I went to the store to buy salty licorice.

**Comment by SethTisue** [comment]
free space is up to 126G now

first test PR is https://github.com/scala/scala/pull/8155 , we'll see if it's able to upload even though Artifactory is still GCing . else, try again in another 4 hours or so.

**Comment by SethTisue** [comment]
e.g. https://scala-ci.typesafe.com/artifactory/list/scala-pr-validation-snapshots/org/scala-lang/scala-library/ seems to be repopulating

**Comment by SethTisue** [comment]
that's more like it:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdk       493G  286G  185G  61% /var/opt/jfrog/artifactory/data
```

now that we only have the "mergely" builds, we can bisect our way to a culprit PR, but we can't bisect our way to an individual commit within that PR, as pointed out by @hrhino and @retronym. oh well, most of the value is in identifying the PR.

Jason also located a Slack thread where @lrytz had done some scripting to remove unneeded artifacts and free up space.

it wasn't necessary to do the scripting in Groovy, you can go through `curl`. here's his stuff, in case we need it again:

`search.json`
```
items.find({
  "repo": "scala-pr-validation-snapshots",
  "$or": [ { "name": { "$match": "scala-compiler*" } }, {"name": { "$match": "scala-reflect*" } }, { "name": { "$match": "scala-library*" } }, { "name": { "$match": "scala-dist*" } }, { "name": { "$match": "scala-partest*" } }, { "name": { "$match": "scalap*" } } ],
  "created": { "$lt": "2020-01-01" }
})
```

`curl -u 'lukas:SEEEKREET' -X POST "https://scala-ci.typesafe.com/artifactory/api/search/aql" -T search.json > artifacts.json`

in an up-to-date scala 2.13.x checkout, the following tests which of the artifacts correspond to revisions that were actually merged into scala/scala. Builds for those revisions are kept, builds for revisions that never made it are added to `to-delete.txt`.

```bash
n=$(cat artifacts.json | jq -r '.results[] | .path' | uniq | wc -l)
for p in $(cat artifacts.json | jq -r '.results[] | .path' | uniq); do
  n=$((n-1))
  sha=$(echo $p | awk -F'-' '{print $(NF-1)}')
  if git branch --contains $sha | grep 2.13.x > /dev/null; then
    echo "$sha y - $n"
  else
    echo "$sha n - $n"
    echo $p >> to-delete.txt
  fi
done
```

delete stuff -- best do it on `ssh jenkins-master` for performance

```bash
n=$(cat to-delete.txt | wc -l)
for p in $(cat to-delete.txt); do
  n=$((n-1))
  echo "$p - $n"
  curl -u 'lukas:PASSWORDSEKRET' -X DELETE "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/$p"
done
```

After that
  - Empty "Trash Can"
    - `curl -I -u 'lukas:SEEEKREET' -X POST "https://scala-ci.typesafe.com/artifactory/api/trash/empty"`
  - Run artifactory's "Garbage Collection" [20 times (😆)](https://jfrog.com/knowledge-base/why-does-removing-deleting-old-artifacts-is-not-affecting-the-artifactory-disk-space-usage/)
    - `for i in {1..20}; do curl -I -u 'lukas:SEEEKREET' -X POST "https://scala-ci.typesafe.com/artifactory/api/system/storage/gc"; done`
    - wait for it to complete, it runs in the background. check Binaries Size / Artifacts Size in Storage
  - Run "Prune Unreferenced Data"
    - `api/system/storage/optimize`
  - https://jfrog.com/knowledge-base/what-is-the-difference-between-garbage-collector-and-prune-unreferenced-data-processes-in-artifactory/

Other measures
  - Artifacts - Trash Can - right click - Empty
  - Derby database (`/var/opt/jfrog/artifactory/data/derby/seg0`) may be big (67 gigs). Admin - Advanced - Maintenance, run "Compress the Internal Database".
    - Did not work for me. "lock could not be obtained due to a deadlock".
    - Doc says "We recommend running this when Artifactory activity is low, since compression may not be able to complete when storage is busy (in which case the storage will not be affected)."

**Comment by SethTisue** [comment]
> I don't even know how long it was because I went to the store to buy salty licorice.

ah, Stockholm 🇸🇪 . I remember international travel 😞

same problem has recurred: https://github.com/scala/scala-dev/issues/732

**Comment by hrhino** [comment]
The "where is Seth sleeping? 2020 edition" tweet is going to be about as dull as mine would be.

EDIT: I see, now that I look at that tweet, that Dale and Stefan beat me to the joke :/
