### ISSUE TITLE
Release 2.12.9

### ISSUE THREAD

**Issue by eed3si9n** [scala/scala-dev#639]
Variables to be expanded in this template (or export them in a local terminal, so that you can copy/paste the commands below without replacing anything):
- SCALA_SHA=cca78e1e18c55e5b0223b9dfa4ac230f7bc6a858
- DIST_SHA=bc7334d99faf07b83c63066158e256b1606dafe8

Key links:
  - scala/scala milestone: https://github.com/scala/scala/milestone/77
  - scala/bug milestone: https://github.com/scala/bug/milestone/98
  - scala/scala-dev milestone: https://github.com/scala/scala-dev/milestone/27

### previously

https://github.com/scala/scala-dev/issues/582

### N weeks before the release
- [x] Wind down PR queue. There has to be enough time after the last (non-trivial) PR is merged and the next phase. The core of the eco-system needs time to prepare for the final!
- [x] Triage scala/bug and scala/scala-dev tickets
- [x] Create next scala/scala milestone, move the magical "Merge to 2.13.x" description to it (so Scabot uses it as default for new PRs)
- [x] Close the scala/bug milestone, create next milestone, move pending issues
- [x] Close the scala/scala-dev milestone, create next milestone, move pending issues
- [x] Check PRs assigned to the milestone, also check WIP
- [x] Announce expected release date and current nightly "release candidate" (nightly sha-mangled version) at https://scala-ci.typesafe.com/artifactory/scala-integration/ on https://contributors.scala-lang.org/c/announcements

### Release announcement / notes
- [x] Notify community on https://contributors.scala-lang.org/c/announcements
- [x] Review merged PRs, make sure release-notes label is applied appropriately
- [x] PRs with release-notes label must have excellent title & description (title will be pasted literally in release note bullet list)
- [x] Draft release notes (to be published once GitHub tag is pushed)
  - note that GitHub release notes drafts can only be viewed by committers, so use a gist to draft the notes, so the gist can be shared with the community - https://gist.github.com/eed3si9n/ea878634329942e1877a872dc77d9a5d
- [x] On contributors thread, link to release note gist and request feedback
- [x] Prepare PR to https://github.com/scala/scala-lang/ (using scala/make-release-notes which requires a staged release and a pushed tag)
  - `documentation/api.md`
  - `download/index.md`
  - `_config.yml` (update devscalaversion or scalaversion)
- [x] Prepare PR to https://github.com/scala/docs.scala-lang/
  - `api/all.md`

### N days before release
- Announce no more PRs will be merged unless last-minute regressions are found. Re-iterate current nightly sha version for testing.
- [x] Community build
    - won't be anywhere near all green, but we should make sure some nontrivial number of projects are still green
    - run with expected-greens only: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/?
    - also do a full run to see if there are any unexpected greens
- [x] Run scala-collections-laws and evaluate results
    - Rex Kerr (@Ichoran) is the keeper and expert on this
- [x] Windows Jenkins job
    - don't just trust the automated nightly runs, manually trigger a run on the exact SHA
    - https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/1447/
- [x] Check any merged PRs accidentally assigned to the next milestone in this branch, and re-assign them to this milestone
- [x] Merge in any older release branch
- [x] Check module versioning (is everything in versions.properties up to date?)
- [x] On major release, bump PickleFormat version

### Point of no return
- Once sufficient time has passed since last merged PR (1-2 weeks depending on whether it's a maintenance or development branch), and core projects have tried out the candidate nightly, it's time to cut the release!
- [x] Make sure there are no stray staging repos on sonatype
- [x] Trigger a build on [travis](https://travis-ci.org/scala/scala), specify `SCALA_VER_BASE` and `SCALA_VER_SUFFIX` in the custom config
  - config: `before_install: export SCALA_VER_BASE=$SCALA_VER_BASE SCALA_VER_SUFFIX=$SCALA_VER_SUFFIX`)
  - Check the build status on https://github.com/scala/scala/commits/2.13.x
  - Check that the scala/scala job also triggered a following scala/scala-dist job: https://travis-ci.org/scala/scala-dist/builds/?
  - [x] Note the scala/scala commit (the full 40-char sha!)
  - [x] Create the scala/scala tag locally: `git tag -s -m "Scala $SCALA_VER" v$SCALA_VER $SCALA_SHA`
  - [x] Note the scala/scala-dist commit (the full 40-char sha!)
  - [x] Create scala-dist tag locally: `git tag -s -m "Scala $SCALA_VER" v$SCALA_VER $DIST_SHA`
  - [x] Note the repos to be promoted after tag is cut (see travis log)
    - https://oss.sonatype.org/content/repositories/orgscala-lang-1826/
    - https://oss.sonatype.org/content/repositories/orgscala-lang-????
- [x] Sanity check jar/pom
  - https://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-compiler/$SCALA_VER/
  - in particular, if the release was staged multiple times, double check that https://oss.sonatype.org/content/repositories/staging/ has the files from the most recent build
- [x] Check that JARs haven't mysteriously bloated — compare sizes to previous release. We have no other backstop for this.
- Remember, tags are forever, so are maven artifacts (even staged ones, as they could end up in local caches) and S3 uploads (S3 buckets can be changed, but it can takes days to become consistent)
- [x] Push scala/scala tag: `git push https://github.com/scala/scala.git v$SCALA_VER`
- [x] Add release notes to https://github.com/scala/scala/releases/tag/v$SCALA_VER
- [x] Push scala/scala-dist tag: `git push https://github.com/scala/scala-dist.git v$SCALA_VER`
- [x] Trigger two scala-dist jobs on travis (https://travis-ci.org/scala/scala-dist) with custom config. must use full-length SHAs!
  - `before_install: export version=$SCALA_VER scala_sha=$SCALA_SHA mode=archives`: https://travis-ci.org/scala/scala-dist/builds/?
  - `before_install: export version=$SCALA_VER scala_sha=$SCALA_SHA mode=update-api`: https://travis-ci.org/scala/scala-dist/builds/?
- [x] Promote staging repos: `st_stagingRepoPromote [scala-repo]`, `st_stagingRepoPromote [modules-repo]` (or use oss.sonatype.org web UI)

### Check availability
- [x] Check release on sonatype: https://oss.sonatype.org/content/repositories/releases/org/scala-lang/scala-compiler/$SCALA_VER/
- [x] Check the release on maven central: http://central.maven.org/maven2/org/scala-lang/scala-compiler/$SCALA_VER/
- [x] Check the release on maven search (takes longer): http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.scala-lang%20v%3A$SCALA_VER

### When everything is on maven central
- [x] make sure the draft release notes are on GitHub tag: https://github.com/scala/scala/releases/tag/v$SCALA_VER
- [x] Pre-announce the release on https://contributors.scala-lang.org/c/announcements
- [x] On 2.13.0 only: (manually) update the `current` symlink for the API docs
  - https://github.com/scala/scala-dist/blob/2.13.x/scripts/jobs/release/website/update-api#L15
- [x] Check that the API docs are published
  - http://www.scala-lang.org/api/$SCALA_VER/
  - https://docs.scala-lang.org/api/all.html ?
- [x] Merge the scala-lang PR and the docs.scala-lang.org PR
  - [x] wait for them to arrive on the websites and make sure they look okay

### Modules
- [x] build and release scala-collection-compat and other modules (or open tickets asking that the maintainers do so)
    - this work has moved to https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md
- [x] if it's a 2.12.x release, publish macro paradise for the new version
  - https://github.com/scalamacros/paradise/releases/tag/v2.1.0_2.12.9
  - https://repo1.maven.org/maven2/org/scalamacros/paradise_2.12.9/

### Announcements
- [x] Scala Users discourse https://users.scala-lang.org
- [x] add a reply on the same https://contributors.scala-lang.org thread where you announced that the release process was starting
- [x] Tweet from [@scala_lang](https://twitter.com/scala_lang)
- [x] https://gitter.im/scala/scala
    - [x] if you feel like it, say something in https://gitter.im/scala/contributors too
- [x] ask Seth to announce on #scala IRC

### Afterwards
- [ ] Create PR to add/update spec links on scala-lang.org (example: https://github.com/scala/scala-lang/pull/1050)
- [ ] Create PR to update `scala-version` on docs.scala-lang.org (example: https://github.com/scala/docs.scala-lang/pull/1294)
- [x] Create PR to update `versions.properties` (new file generated by the bootstrap job) and the `baseVersion` in `build.sbt` and the MiMa base version and exclusion filters and (if it's a major bump) `spec/_config.yml`
- [x] If it's a major bump, PR an update to `latestSpecVersion` in `spec/_config.yml` on the old branch, so that spec is marked as no longer current
- [ ] Create PR to update https://github.com/lightbend/reactive-platform-docs/blob/master/src/main/paradox/supported-modules/index.md
- [x] Update [WhiteSource](https://github.com/lightbend/scala-team/wiki/Whitesource)

**Comment by eed3si9n** [comment]
scala/scala PR is down to 4 PRs - https://github.com/scala/scala/milestone/77 /cc @retronym, @diesalbla

**Comment by eed3si9n** [comment]
scala/bug down to 3. https://github.com/scala/bug/milestone/98 two related to Saladoc with "help wanted" tag and one about fresh name.

**Comment by eed3si9n** [comment]
scala/scala PR have all been merged. If all goes well 2.12.9-bin-82e3405 is the current candidate. No further PRs will be committed unless there's a last-minute bug fix.

**Comment by SethTisue** [comment]
community build SHA updated, runs on all three JDKs (8/11/12) in progress

**Comment by eed3si9n** [comment]
We might include this - https://github.com/scala/scala/pull/8289

**Comment by eed3si9n** [comment]
ok. New commit SHA is https://github.com/scala/scala/commit/87d43d092060c8dbf216ef2580e116cebea4a828.

Scala 2.12.9-bin-87d43d0 is the current candidate.

**Comment by SethTisue** [comment]
community builds restarted

**Comment by eed3si9n** [comment]
Ran scala-collection-laws:

```
$ git diff
diff --git a/build.sbt b/build.sbt
index e6cb9f6..a05d13a 100644
--- a/build.sbt
+++ b/build.sbt
@@ -2,4 +2,4 @@ name := "collections-laws"

 version := "0.3.2"

-scalaVersion in ThisBuild := "2.12.2"
+scalaVersion in ThisBuild := "2.12.9-bin-87d43d0"
$ sbt -J-XX:MaxMetaspaceSize=1G -J-Xmx6G "tests/runMain tests.generated.collection.Test_All"
....
[info] Running tests.generated.collection.Test_All
Test lines 86, 206 were not used.
103 collections run against suite of 353 tests (18112 total)
[success] Total time: 473 s, completed Aug 1, 2019 11:56:18 AM
```

**Comment by eed3si9n** [comment]
Community Builds
- [x] scala-2.12.x-integrate-community-build (JDK 8) - https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/4762/
- [x] scala-2.12.x-jdk11-integrate-community-build (JDK 11) - https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk11-integrate-community-build/703/
- [x] scala-2.12.x-jdk12-integrate-community-build (JDK 12) - https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk12-integrate-community-build/321/

**Comment by eed3si9n** [comment]
Note to self: previous Travis trigger - https://travis-ci.org/scala/scala/builds/542650556/config

```
before_install: "export SCALA_VER_BASE=2.12.9 SCALA_VER_SUFFIX=\"\""
```

**Comment by eed3si9n** [comment]
New commit SHA is https://github.com/scala/scala/commit/cca78e1e18c55e5b0223b9dfa4ac230f7bc6a858. This is comment change, so we can reuse the result on Community Build of any other testing.

**Comment by eed3si9n** [comment]
https://travis-ci.org/scala/scala/jobs/567895759 failed because scala/scala now uses before_install. trying before_script..

**Comment by eed3si9n** [comment]
`before_script` worked. https://travis-ci.org/scala/scala/jobs/567900531

**Comment by eed3si9n** [comment]
Triggering https://travis-ci.org/scala/scala-dist/builds/568002492:

```yaml
before_install: export version=2.12.9 scala_sha=cca78e1e18c55e5b0223b9dfa4ac230f7bc6a858 mode=archives
```

https://travis-ci.org/scala/scala-dist/builds/568004143

```yaml
before_install: export version=2.12.9 scala_sha=cca78e1e18c55e5b0223b9dfa4ac230f7bc6a858 mode=update-api
```

**Comment by eed3si9n** [comment]
- https://github.com/scala/scala-lang/pull/1063

**Comment by SethTisue** [comment]
@eed3si9n let's close this out...? (I'm about to make a ticket for 2.12.10.)
