### ISSUE TITLE
Build pipelining

### ISSUE THREAD

**Issue by eed3si9n** [scala/scala-dev#643]
This is an epic to track various build pipelining related tasks. This means that in a multi-project builds, a downstream subproject could be compiled immediately after its upstream subprojects have finished typechecking (more precisely, have finished the "pickler" phase), rather waiting for the back end of the the compiler to produce `.class` files.

### infrastructure

The following provides infrastructure to support build pipelining (build tools must support it too).

- [x] Experimental support for build pipelining (https://github.com/scala/scala/pull/7712) `ClassfileParser` is extended to support .sig files, containing just the Scala Pickle (which is usually parsed from the argument of a class file annotation).
- [x] Experimental support for outline type checking (https://github.com/scala/scala/pull/8077) First, we compile all sources with `-Youtline -Ystop-after:pickler`. The first option disables typechecking of the RHS of definitions that have ascribed types. The pickles are then exported and made available to downstream compilation, as is also the case with the `strategy=Pipeline`. The sources for the current projects are then compiled in parallel in chunks, also using the exported pickles on the classpath.

**Comment by SethTisue** [comment]
Closing since the basics are now implemented.
