### ISSUE TITLE
provide guidance to project maintainers on including “latest Scala nightly” in their CI matrices

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#648]
we should figure out how to do this and provide a sample `.travis.yml` that does it. the Scala modules could be a good place to start

**Comment by SethTisue** [comment]
one new possibility here is for projects to scrape a decently current version out of the new `nightly.properties` file this repo now provides: https://github.com/scala/community-builds/blob/2.12.x/nightly.properties

**Comment by SethTisue** [comment]
to make this more concrete, here's what I have in one repo:

```scala
resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
def nightly(branch: String): String = {
  val url = s"https://raw.githubusercontent.com/scala/community-builds/$branch/nightly.properties"
  val props = new java.util.Properties
  props.load(new java.net.URL(url).openStream)
  props.getProperty("nightly").ensuring(_ != null)
}
crossScalaVersions := Seq("2.13.0", "2.12.9", "2.11.12",
  nightly("2.13.x"), nightly("2.12.x"), nightly("2.11.x"))
scalaVersion := crossScalaVersions.value.head
publish / skip := scalaVersion.value.containsSlice("-bin-")
```

but I'm not sure how to write a `.travis.yml` that works with this, any suggestions?

**Comment by dwijnand** [comment]
Add the 3 nightly options to the yaml and make it call a wrapper command that does the lookup and calls ++.

Think `plz 2.12-nightly test`.

**Comment by milessabin** [comment]
FWIW, I've been leaning quite heavily on the `dottyLatestNightlyBuild` task while working on shapeless 3. Something like that for Scala 2 would be very helpful.

**Comment by SethTisue** [comment]
we wanted to do this for Scala.js (context: https://github.com/scala/community-build/issues/1009)

but @sjrd didn't want to modify his main CI matrix since the "latest" aspect would make the builds nonreproducible

so he set up a separate repo https://github.com/scala-js/scala-js-test-scala-nightly — it has a `.travis.yml` that clones the main Scala.js repo and runs the tests against the Scala version from `scala/community-builds/$branch/nightly.properties`

this approach may be of interest to other maintainers as well

**Comment by milessabin** [comment]
I've shamelessly pilfered this for shapeless [here](https://github.com/milessabin/shapeless-test-scala-nightly).

**Comment by SethTisue** [comment]
proposal to add this to sbt: https://github.com/sbt/sbt/pull/5464 cc @martijnhoekstra 

more relevant to interactive use than to typical CI, but scala-runners offers it, https://github.com/dwijnand/scala-runners

**Comment by SethTisue** [comment]
One thing I dislike about my [advice above](https://github.com/scala/scala-dev/issues/648#issuecomment-525923361) is that it forces you to use `script: sbt +test` (note the `+`) rather than controlling the Scala version using `scala:` entries in your matrix. Which is a bit sad because matrix thing is nice (you get a separate job for each version, with its own log) and is pretty standard in Scala OSS.

I guess if you really want the matrix thing, you could rig a thing where instead of controlling the Scala version with `scala:`, you control it with `env: SCALA_VERSION=` matrix entries, and then hook that up to something in the sbt build that overrides the Scala version appropriately if the environment variable is set (including to some magic value such as "2.12.x-nightly").

Or just hope https://github.com/sbt/sbt/pull/5464 lands at some point :-)

**Comment by SethTisue** [comment]
@dwijnand am I imagining it, or did you do a version of this in one of your repos recently? (scala-rewrites?)

**Comment by dwijnand** [comment]
Yeah: https://github.com/scala/scala-rewrites/pull/35

**Comment by SethTisue** [comment]
I'm going to close this ticket as I think the way the Scala 2 ecosystem operates isn't worth changing at this point.

Of course this is very much still a live issue generally, but for Scala 3. (Some considerations may be different in Scala 3 because unlike Scala 2, Scala 3 minor releases are only backwards compatible, not forwards compatible.)

cc @romanowski
