### ISSUE TITLE
default getters for constructor arguments are now static

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#656]
This changes the bytecode encoding in Scala 2.14 -- needs to be coordinated with Scala 3.x

PR: https://github.com/scala/scala/pull/8509

**Comment by SethTisue** [comment]
@lrytz this should be closed as no longer relevant, I think?

**Comment by som-snytt** [comment]
The pattern to coordinate encoding part does seem a bit stale.

Edit: It was the early weeks of a pandemic as yet undetected. Many dreams were deferred.
