### ISSUE TITLE
2.12.x nightly didn't publish, SDKMAN related

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#659]
https://travis-ci.org/scala/scala/jobs/609141328 failed to publish 2.12.11-bin-f389823 , @eed3si9n can you take a look?

**Comment by dwijnand** [comment]
Need to backport https://github.com/scala/scala/pull/8528 to the 2.12.x branch.

**Comment by SethTisue** [comment]
merged the backport; let's see how https://travis-ci.org/scala/scala/jobs/610908180 does

**Comment by SethTisue** [comment]
2.12.11-bin-be7fd51 was successfully published :+1:
