### ISSUE TITLE
memory usage is higher in 2.12 than 2.11?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#66]
see e.g. @sjrd's charts at https://github.com/scala-js/scala-js/issues/2044

@adriaanm writes "I've noticed failures as well in the toolbox run test that checks for memory leaks... while working on my WIP  trait stuff. that looks like something we should investigate before M4"

**Comment by adriaanm** [comment]
I should amend that, and say "before M4, time permitting, but certainly before RC1."

**Comment by sjrd** [comment]
The charts I posted show the memory behavior at run-time, not during compilation. The behavior could come either from regressions in the standard library, or from the code generated by the compiler (as seen right after mixin). The regression can't be related to the runtime performance of the compiler itself.

**Comment by adriaanm** [comment]
Ah, I hadn't caught that -- thanks for clarifying!

**Comment by SethTisue** [comment]
should this remain open?
