### ISSUE TITLE
Travis-CI config doesn't work from forks

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#663]
some contributors might appreciate being able to run PR validation in their forks, for work that isn't ready for the main scala/Scala PR queue

@dwijnand made a brief initial stab at https://github.com/scala/scala/pull/8665 but quickly realized it needed more work

**Comment by lrytz** [comment]
Somewhat related, here is a script that I wrote at some point to do a full bootstrap build locally, using the scripts in the repo: https://github.com/lrytz/scala/commit/25d246de4105843739854ad4120bd071c51bc089. (For local development and testing, I do it differently though. I basically do `sbt setupPublishCoreNonOpt publishLocal` and then `sbt -Dstarr.version=..... dist/mkQuick`.)

Another issue we might run into is time limits. Travis by default gives 50 minutes for public repositories. We got a free upgrade for scala/scala (I think to 90 minutes?) at some point, but that likely doesn't apply to forks. PR builds on travis ususally take 1h to 1h15m.

**Comment by dwijnand** [comment]
I also don't think (and highly doubt) forks reused scala/scala's cache, so it's likely longer.

I think it would be fine if forks only ran non-bootstrapped.

**Comment by lrytz** [comment]
The bootstrap doesn't take much time, it's the test suite.

**Comment by dwijnand** [comment]
Oh I thought tests were run twice, bootstrapped and non-bootstrapped.
