### ISSUE TITLE
partest artifacts for 2.13.x

### ISSUE THREAD

**Issue by soronpo** [scala/scala-dev#667]
As [discussed on gitter](https://gitter.im/scala/contributors?at=5e402c0d62e9db4bf78a1d42), there are currently no partest artifacts published for 2.13.1. I was thinking of using partest in my library since it's a DSL library which relies on compile-time safety and will be easier to test via partest's pos/neg mechanisms.

**Comment by dwijnand** [comment]
I think there's no strong interest or budget in making and supporting partest as a non-internal testing library, so I (respectfully) vote to reject this request.

**Comment by lrytz** [comment]
How is dotty running the partest-like tests (cc @smarter)?

An alternative is to instantiate and run the compiler in a test framework, we do that as well.

**Comment by smarter** [comment]
> How is dotty running the partest-like tests (cc @smarter)?

With this stuff: https://github.com/lampepfl/dotty/tree/master/compiler/test/dotty/tools/vulpix

**Comment by smarter** [comment]
You might be interested in https://github.com/liufengyun/scala-wrench, a test framework written for compiler plugins to support pos/neg/run tests, this could be useful outside of compiler plugins too.

**Comment by SethTisue** [comment]
> I think there's no strong interest or budget in making and supporting partest as a non-internal testing library, so I (respectfully) vote to reject this request.

I agree that we-the-core-team shouldn't take it on, but would you reject a PR that did it?

**Comment by SethTisue** [comment]
I assume the status quo holds here: will not tackle, but would probably accept as contribution.
