### ISSUE TITLE
2.12 lambdas have different `toString`

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#67]
this came up in the community build — somebody (namely @lihaoyi, in fastparse) has tests that assume this style:

``` scala
scala> ((_: Int) * 10).toString
res1: String = <function1>
```

but 2.12 currently does:

``` scala
scala> ((_: Int) * 10).toString
res0: String = $$Lambda$1807/425015667@7bb6ab3a
```

was this an intentional change?

**Comment by retronym** [comment]
It is unavoidable if we use `LambdaMetaFactory`, which doesn't expose a way to provide an implementation of `toString`. (Default methods in interfaces themselves can't override methods in `Object`, either).

We could provide `ScalaLambdaMetafactory` to generate precisely what we want, but the risk is that we will forgo current or future optimizations in HotSpot targetting LMF.

**Comment by SethTisue** [comment]
ah, and now I remember discussing this before. I guess this should go in the release notes.

**Comment by SethTisue** [comment]
it's pretty easy to argue that it's actually desirable, eco-systemically, to be Java compatible here rather than Scala <=2.11 compatible:

``` java
% cat J.java
public class J {
  public static void main(String[] argv) {
    Runnable r = () -> { };
    System.out.println(r);
  }
}
% javac J.java
% java J
J$$Lambda$1/990368553@6d311334
```
