### ISSUE TITLE
Resolve serialization instability in TreeMap

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#674]
https://github.com/scala/scala/pull/8707 introduced a new parent interface to `TreeMap`. This changed the serial version UID with respect to 2.12.10.

/cc @SethTisue 

I will submit a PR to fix this and to add the missing test coverage.

**Comment by sjrd** [comment]
> https://github.com/scala/scala/pull/8707 introduced a new parent interface to `TreeMap`.

Er wait, isn't that kind of change the reason that 2.11.9 or 2.11.10 was not forward binary compatible?

**Comment by retronym** [comment]
Here is @lrytz's summary of why 2.11.9 was binary incompatible: https://github.com/scala/scala/pull/5821#issuecomment-291277427

This case is different because we are not attempting to introduce an override of an public part of the API. `HasForeachEntry` only contains a `private[scala] def foreachEntry` method. So long as calls to the new method are only made from within `scala-library.jar`, I believe compatibility is okay.
