### ISSUE TITLE
make sure sbt works when its own Scala version is set to 2.12.11?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#676]
@eed3si9n @lrytz not sure, is this something we ought to test before shipping 2.12.11?

since sbt might need or want to make it the default at some point

(and, less importantly, users might want to override the default)

**Comment by eed3si9n** [comment]
I could send a wip PR to sbt and let it run the scripted tests.

**Comment by lrytz** [comment]
would be helpful 👍

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/pull/5460
