### ISSUE TITLE
JLine 3: make sure it works with `sbt console` as well as standalone

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#678]
sbt uses JLine 2, so it's not exactly difficult to imagine things going wrong

the primary testing should be against sbt 1, but we also shouldn't break sbt 0.13 unless it turns out to be a too-deep rabbithole

cc @eed3si9n

**Comment by SethTisue** [comment]
at https://github.com/scala/scala/pull/8036#issuecomment-507537480 @dwijnand mentioned "source-breakage of zinc's "console" abstraction of the REPL, which we'd have to address" — what does that mean?

**Comment by dwijnand** [comment]
I'm pretty sure what I meant was "I'm only likely to complain if I see a source-breakage that impacts sbt's `console`".  In the hypothetical.

**Comment by SethTisue** [comment]
some further details in https://github.com/scala/scala/pull/8036#issuecomment-525032971

**Comment by eed3si9n** [comment]
I just tested again using https://github.com/scala/scala/pull/8036/commits/2ef554a28e97098ab66e7b32b213b8f0ef19f867 on Windows 7 VM, and it's still broken.

<img width="898" alt="jline3" src="https://user-images.githubusercontent.com/184683/75992137-891a6c80-5ec5-11ea-99e1-c477e35a25b5.png">

It says "WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)".

More importantly, the prompt doesn't accept "1" or enter key. Nothing shows up. Ctrl-C does work, to exit out. I checked to see Scala 2.13.1 REPL using the same setup and that works fine.

**Comment by lrytz** [comment]
Summarizing what we discussed on Friday

JLine jars
  - JLine 2 (Scala 2.13.1 uses [version 2.14.6](https://search.maven.org/artifact/jline/jline/2.14.6/jar)) has jansi embedded in the jar (not shaded, `org/fusecode` classfiles, binaries in `META-INF/native/`). No dependency on `jansi` or `jna`.
  - JLine 3 ([3.14.0](https://search.maven.org/artifact/org.jline/jline/3.14.0/jar) is the latest) no longer embeds jansi, the jar only has JLine classfiles, no native binaires. There are `optional` dependencies on `jansi` and `jna`.

2.13 jars
  - 2.13.1: pom depends on jline 2.14.6 and jansi 1.12 (both not `optional`). The jansi dependency was added as a side-effect of https://github.com/scala/scala/pull/8209#issuecomment-596123742.
  - 2.13.0: pom depends on jline 2.14.6 (not `optional`)
  - 2.13 compiler jar ships without any integrated / shaded jline or jansi (https://github.com/scala/scala/commit/3de08541f2)
  - the "distribution" (zip archive from the website) ships with the dependencies in the `lib` folder (jline, jansi for 2.13.1)

2.12 jars
  - 2.12.9 / 2.12.10 have `optional` dependencies on jline 2.14.6 and jansi 1.12 (jansi was likely added as a side-effect of https://github.com/scala/scala/pull/8167)
  - 2.12.8 (and probably before) has an `optional` dependency on 2.14.6
  - the distribution for 2.12/8/9/10 have `jline-2.14.6.jar` in the `lib` folder. no `jansi`
  - 2.12.8/9/10 all ship with jline and jansi shaded into the scala-compiler.jar
    - binaries in `META-INF/native/linux64/libjansi.so`
    -  classfiles in `scala/tools/fusesource_embedded/jansi` and `scala/tools/jline_embedded`

It looks like the shaded jline was originally added in https://github.com/scala/scala/pull/4563 (ant build) for 2.11.7. The sbt version of this is https://github.com/scala/scala/commit/9debc84dcd. It seems that the repl would only use the shaded jline as a fallback if jline cannot be found on the classpath. I don't know what was the motivation, but it seems to have something to do with spark.

**Comment by eed3si9n** [comment]
I got a $160 laptop for Windows testing last November, and I finally set it up to do some testing today. On it, it has a recent Windows 10. 

### Scala 2.13.1

```
sbt:hello> show scalaInstance
[info] Scala instance { version label 2.13.1, actual version 2.13.1,
library jars: C:\Users\eugen\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.1\scala-library-2.13.1.jar, 
compiler jar: C:\Users\eugen\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-compiler\2.13.1\scala-compiler-2.13.1.jar,
other jars:
C:\Users\eugen\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\jline\jline\2.14.6\jline-2.14.6.jar,
C:\Users\eugen\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\fusesource\jansi\jansi\1.12\jansi-1.12.jar,
C:\Users\eugen\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-reflect\2.13.1\scala-reflect-2.13.1.jar
}
```

### Scala 2.13.2 (JLine 3 branch)

```
sbt:hello> show scalaInstance
[info] Scala instance { version label 2.13.2-bin-SNAPSHOT, actual version 2.13.2-bin-SNAPSHOT, 
library jars: C:\Users\eugen\.ivy2\local\org.scala-lang\scala-library\2.13.2-bin-SNAPSHOT\jars\scala-library.jar,
compiler jar: C:\Users\eugen\.ivy2\local\org.scala-lang\scala-compiler\2.13.2-bin-SNAPSHOT\jars\scala-compiler.jar,
other jars:
C:\Users\eugen\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\fusesource\jansi\jansi\1.18\jansi-1.18.jar,
C:\Users\eugen\.ivy2\local\org.scala-lang\scala-reflect\2.13.2-bin-SNAPSHOT\jars\scala-reflect.jar,
C:\Users\eugen\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jline\jline\3.14.0\jline-3.14.0.jar,
C:\Users\eugen\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-asm\7.3.1-scala-1\scala-asm-7.3.1-scala-1.jar
}
```

### Dotty 0.23.0-RC1

```
[info] Scala instance { version label 0.23.0-RC1, actual version 0.23.0-RC1,
library jars: 
C:\Users\eugen\.ivy2\cache\ch.epfl.lamp\dotty-library_0.23\jars\dotty-library_0.23-0.23.0-RC1.jar,
C:\Users\eugen\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.13.1.jar,
compiler jar: C:\Users\eugen\.ivy2\cache\ch.epfl.lamp\dotty-compiler_0.23\jars\dotty-compiler_0.23-0.23.0-RC1.jar,
other jars: 
C:\Users\eugen\.ivy2\cache\ch.epfl.lamp\dotty-interfaces\jars\dotty-interfaces-0.23.0-RC1.jar, 
C:\Users\eugen\.ivy2\cache\ch.epfl.lamp\tasty-core_0.23\jars\tasty-core_0.23-0.23.0-RC1.jar, 
C:\Users\eugen\.ivy2\cache\org.scala-lang.modules\scala-asm\bundles\scala-asm-7.3.1-scala-1.jar, 
C:\Users\eugen\.ivy2\cache\org.scala-sbt\compiler-interface\jars\compiler-interface-1.2.5.jar, 
C:\Users\eugen\.ivy2\cache\org.scala-sbt\util-interface\jars\util-interface-1.2.2.jar, 
C:\Users\eugen\.ivy2\cache\org.jline\jline-reader\jars\jline-reader-3.9.0.jar, 
C:\Users\eugen\.ivy2\cache\org.jline\jline-terminal\jars\jline-terminal-3.9.0.jar, 
C:\Users\eugen\.ivy2\cache\org.jline\jline-terminal-jna\jars\jline-terminal-jna-3.9.0.jar, 
C:\Users\eugen\.ivy2\cache\net.java.dev.jna\jna\jars\jna-4.2.2.jar
}
```


```
[error] (run-main-0) java.lang.IllegalStateException: Unable to create a system terminal
[error] java.lang.IllegalStateException: Unable to create a system terminal
[error]         at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:316)
[error]         at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:262)
[error]         at dotty.tools.repl.JLineTerminal.<init>(JLineTerminal.scala:22)
[error]         at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:105)
[error]         at xsbt.ConsoleInterface.run(ConsoleInterface.java:52)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
[error]         at sbt.Console.console0$1(Console.scala:48)
[error]         at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:257)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit code: 1
```

I was hoping that Dotty can run `console` task on Windows, but apparently not.

**Comment by eed3si9n** [comment]
I was hoping that key input not working and "WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)" were specifically a Command Prompt (Cmd) problem, but I am getting the same unfortunately on Windows Terminal as well.

![2020-03-19 14_02_04-Window](https://user-images.githubusercontent.com/184683/77100046-55723300-69eb-11ea-9e81-0bf9f13adf93.png)

**Comment by eed3si9n** [comment]
Got this to work after switching to JNA.

![2020-03-19 16_43_15-Window (2)](https://user-images.githubusercontent.com/184683/77113328-fc14fe80-6a00-11ea-9ef6-fa9083feb700.png)

**Comment by eed3si9n** [comment]
As I wrote on https://github.com/som-snytt/scala/pull/5 I am guessing that Jansi used by sbt itself may be interfering with Jansi that gets loaded from the compiler. Normally these duplicates are resolved by creating a sandbox ClassLoader, but maybe it doesn't exactly work for native libraries loaded into the same process.

I wondering if this would go away if we forked for `console` instead of reusing the same JVM
https://github.com/sbt/sbt/issues/1918

**Comment by SethTisue** [comment]
@eed3si9n changes on https://github.com/scala/scala/pull/8036 LGTY?

**Comment by SethTisue** [comment]
@eed3si9n should we close this, or do you want to do some more testing first?

**Comment by eed3si9n** [comment]
I guess we can close it.
