### ISSUE TITLE
JLine 3: test on Windows

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#679]
initial testing will be on macOS & Linux and they'll probably just work, but then Windows-specific testing will need to be a focus, just crossing our fingers definitely isn't an option :-)

there are already some remarks on this at https://github.com/scala/scala/pull/8036 , including a known problem with the character encoding of `~/.scala_history` and a known `Unable to retrieve infocmp for type msys` problem (not sure whether to further subdivide and open individual tickets on those or not, we can see whether this ticket gets tangled, I guess)

first-line testers can include @martijnhoekstra and @szeiger , but also it's time for me to have my own testing setup, something I've been able to dodge for the past 3 years or so 😁

**Comment by martijnhoekstra** [comment]
when clearing the history, I end up with an unresponsive shell that I can only ctrl-C out of. I haven't dug into whether I can figure out what it's doing or trying to do yet. After I ctrl-C out, everything typed ends up in the calling shell as input.

**Comment by SethTisue** [comment]
we might learn something from @lihaoyi and his crew's experiences at https://github.com/lihaoyi/Ammonite/issues/119

**Comment by SethTisue** [comment]
note that https://github.com/scala/scala/pull/8036 now uses jna instead of jansi

**Comment by martijnhoekstra** [comment]
Neat. A quick drive by on windows 10 MSYS/cmd and scala task in sbt/scala in build/quick/bin gives me working without completion (and a "dumb terminal" notice) on the `scala` task in sbt in cmd, and working with completions everywhere else.

**Comment by SethTisue** [comment]
@martijnhoekstra we made the JNA dependency non-optional again (and merged the PR!) — does that make tab completion work again?

@szeiger this is now ready for you to beat on

**Comment by martijnhoekstra** [comment]
No, still no dice with the scala task in sbt on cmd. 

I suspect roughly nobody does that though. The task works in msys, and the binary works both on cmd and msys.

**Comment by SethTisue** [comment]
I'm going to close this, since the calls for testers have been made (including at https://contributors.scala-lang.org/t/coming-soon-scala-2-12-11-scala-2-13-2/4003/26?u=sethtisue). At this point either we get bug reports or we don't.

**Comment by lrytz** [comment]
> No, still no dice with the scala task in sbt on cmd.

ftr, it worked for me
