### ISSUE TITLE
JLine 3: keep `-Xnojline` as a deprecated alias for `-Xjline:off`, perhaps

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#694]
`-Xnojline` is something that people are especially likely to have an e.g. a shell alias, rather than in a place such as `build.sbt` — for years I had it my own `scala*` shell aliases, since I used `rlwrap` instead — so to simply drop the option might be an annoyance for people who use multiple versions of Scala

wdyt @som-snytt

**Comment by SethTisue** [comment]
eh-may on the ocker-blay

**Comment by dwijnand** [comment]
It's also really ea-say.

**Comment by SethTisue** [comment]
"prio:low" does seem unnecessarily pejorative

**Comment by SethTisue** [comment]
fwiw,

```
~ % dotr -Xnojline
Starting dotty REPL...
bad option '-Xnojline' was ignored
scala>                                                                                              
```

**Comment by SethTisue** [comment]
closing on the assumption https://github.com/scala/scala/pull/8906 will be merged
