### ISSUE TITLE
JLine 3: put an "RC" (a designated nightly) out for testing after worst bugs are fixed

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#695]
we can recommend the usual sbt invocation for adding the resolver and setting `scalaVersion`

but it would be good to include command lines for running it using:

* coursier
* @dwijnand's new thing (EDIT: don't be lazy Seth, link to https://github.com/dwijnand/scala-runners)

**Comment by dwijnand** [comment]
Running my "new thing" (scala-runners) with `-v` will give you how to run the thing with coursier.  For instance:

```
$ scala -v -212x -Yrepl-class-based
[setScalaVersion] arg = '2.12.x'
[addCoursier] arg = '-r'
[addCoursier] arg = 'https://scala-ci.typesafe.com/artifactory/scala-integration'
# Executing command line:
cs
launch
scala:2.12.11-bin-e1e2bfe
-r
https://scala-ci.typesafe.com/artifactory/scala-integration
--
-Yrepl-class-based

https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2020-02-27 13:40:20
Welcome to Scala 2.12.11-bin-e1e2bfe (OpenJDK 64-Bit Server VM, Java 11.0.6).
Type in expressions for evaluation. Or try :help.

scala> :quit
```

**Comment by som-snytt** [comment]
I thought the worst bug right now was coronavirus.

**Comment by SethTisue** [comment]
let's get https://github.com/scala/community-build/pull/1116 through, then announce 2.13.2-bin-bc1cad4 for testing

note that scala/scala#8748 is merged, so `-Yrepl-class-based` is now the default

**Comment by SethTisue** [comment]
* https://contributors.scala-lang.org/t/coming-soon-scala-2-12-11-scala-2-13-2/4003/26
* https://twitter.com/SethTisue/status/1242994093057167365
