### ISSUE TITLE
Eliminate local variables that are only written (never read)

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#7]
Most useful after copy propagation (#25)

Miguel's code: [DeadStoreElimPrim](https://github.com/scala-opt/scala/blob/opt/rebase/src/compiler/scala/tools/nsc/backend/bcode/DeadStoreElimPrim.java) / [DeadStoreElimRef](https://github.com/scala-opt/scala/blob/opt/rebase/src/compiler/scala/tools/nsc/backend/bcode/DeadStoreElimRef.java)

**Comment by lrytz** [comment]
Implemented in https://github.com/scala/scala/pull/4858 / https://github.com/scala/scala/commit/29d772d0655a3a5af79c3d8eca91bb33a82c7194
