### ISSUE TITLE
2.12.x has been failing bootstrap since Nov 10

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#70]
at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/ the last success was https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/207/ (https://github.com/scala/scala/commit/93fa559f62637fc3a49d7b961a1d07cf843b0e6b), first failure was https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/208/ (https://github.com/scala/scala/commit/44ae563d375ba462dff621d7e1c5abad1da825af). (weirdly, there was also a single green build on Dec 5 at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/232/ and then it's red again after that.)

**Comment by SethTisue** [comment]
the meta-cause for how this went unnoticed for so long is https://github.com/scala/scala-jenkins-infra/issues/148 — failure notification emails weren't going out. that is now fixed.

**Comment by SethTisue** [comment]
@lrytz @soc it appears from the timing that https://github.com/scala/scala/pull/4838 is the culprit — can y'all look into it?

**Comment by lrytz** [comment]
So it's a single test failing:

```
  [partest] !!  167 - run/showraw_tree_types_typed.scala        [output differs]

% diff /home/jenkins/workspace/scala-2.12.x-integrate-bootstrap/test/files/run/showraw_tree_types_typed-run.log /home/jenkins/workspace/scala-2.12.x-integrate-bootstrap/test/files/run/showraw_tree_types_typed.check
@@ -4,9 +4,9 @@ Apply[1](Select[2](New[1](TypeTree[1]().setOriginal(AppliedTypeTree(Ident[3](sca
 [3] TypeRef(ThisType(scala.collection.immutable), scala.collection.immutable.HashMap, List())
 [4] TypeRef(SingleType(ThisType(scala), scala.Predef), TypeName("String"), List())
 [5] SingleType(ThisType(scala), scala.Predef)
-Apply[6](Select[7](New[6](TypeTree[6]().setOriginal(AppliedTypeTree(Ident[8](scala.collection.mutable.HashMap), List(TypeTree[9]().setOriginal(Select[9](Ident[10](scala.Predef), TypeName("String"))), TypeTree[9]().setOriginal(Select[9](Ident[10](scala.Predef), TypeName("String"))))))), termNames.CONSTRUCTOR), List())
+Apply[6](Select[7](New[6](TypeTree[6]().setOriginal(AppliedTypeTree(Ident[8](scala.collection.mutable.HashMap), List(TypeTree[4]().setOriginal(Select[4](Ident[5](scala.Predef), TypeName("String"))), TypeTree[4]().setOriginal(Select[4](Ident[5](scala.Predef), TypeName("String"))))))), termNames.CONSTRUCTOR), List())
+[4] TypeRef(SingleType(ThisType(scala), scala.Predef), TypeName("String"), List())
+[5] SingleType(ThisType(scala), scala.Predef)
 [6] TypeRef(ThisType(scala.collection.mutable), scala.collection.mutable.HashMap, List(TypeRef(SingleType(ThisType(scala), scala.Predef), TypeName("String"), List()), TypeRef(SingleType(ThisType(scala), scala.Predef), TypeName("String"), List())))
 [7] MethodType(List(), TypeRef(ThisType(scala.collection.mutable), scala.collection.mutable.HashMap, List(TypeRef(SingleType(ThisType(scala), scala.Predef), TypeName("String"), List()), TypeRef(SingleType(ThisType(scala), scala.Predef), TypeName("String"), List()))))
 [8] TypeRef(ThisType(scala.collection.mutable), scala.collection.mutable.HashMap, List())
-[9] TypeRef(SingleType(ThisType(scala), scala.Predef), TypeName("String"), List())
-[10] SingleType(ThisType(scala), scala.Predef)
```

The test passes in ordinary PR builds.

**Comment by lrytz** [comment]
I'm running the same `ant` command that fails on the CI locally now. The first difference to PR-validation that I see is that the bootstrap does 3 rounds. There are 2 invocations of `ant`
- `ant ... -Dlocker.skip=1 publish` publishes to private-repo, only `quick`
- `ant -Dstarr.version=2.12.0-fb22e2b-nightly -Dextra.repo.url=https://scala-ci.typesafe.com/artifactory/scala-release-temp/ ... nightly publish`, runs both `locker` and `quick`, then the tests

In PR validation there are only two rounds before running the tests.

**Comment by lrytz** [comment]
The test passed on my machine

```
ant -Dstarr.version=2.12.0-fb22e2b-nightly -Dextra.repo.url=https://scala-ci.typesafe.com/artifactory/scala-release-temp/ -Dmaven.version.suffix=-fb22e2b-nightly -Dscala-parser-combinators.version.number=1.0.4 -Dscala-swing.version.number=2.0.0-M2 -Dscala-xml.version.number=1.0.5 -Dpartest.version.number=1.0.9 -Dscalacheck.version.number=1.11.6 -Dscala.binary.version=2.12.0-fb22e2b-nightly -Dupdate.versions=1 -Dscaladoc.git.commit=fb22e2b0a73605d654c153e02d454e5cec21f355 -Dremote.snapshot.repository=NOPE -Dremote.release.repository=https://scala-ci.typesafe.com/artifactory/scala-release-temp/ -Dscalac.args.optimise=-Yopt:l:classpath nightly
[...]
  [partest] ok  648 - run/showraw_tree_types_typed.scala
```

**Comment by lrytz** [comment]
Looking a bit at the tree printer, I'm pretty sure the the failure is spurious. In an interesting way :-) cc @xeno-by - maybe you have a good idea to fix this?

The test:

```
  val tree1 = reify(new collection.immutable.HashMap[String, String])
  val tree2 = reify(new collection.mutable.HashMap[String, String])
  println(showRaw(tb.typecheck(tree1.tree), printTypes = true))
  println(showRaw(tb.typecheck(tree2.tree), printTypes = true))
```

`printTypes = true` shows types of trees as footnotes, for example the tree for `"hi"` is

```
Literal[1](Constant("hi"))
[1] ConstantType(Constant(hi))
```

The `Type` object is passed to [`Footnotes.put`](https://github.com/scala/scala/blob/d16918db010b2805677254e748a617c417df98ec/src/reflect/scala/reflect/internal/Printers.scala#L1155-L1159), which basically has a cache `WeakHashMap[Any, Int]` so that multiple references to the same object get the same reference.

Now if you `showRaw` two trees that happen to have a reference to the same type somewhere, the footnote index while printing the second tree depends on whether the weak map still contains the type or not - if not, a new index is assigned.

The [current check file](https://github.com/scala/scala/blob/d16918db010b2805677254e748a617c417df98ec/test/files/run/showraw_tree_types_typed.check) assumes that the types are still in the map.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/4911

**Comment by SethTisue** [comment]
merged. we'll see what happens with tonight's automatically scheduled run.

**Comment by SethTisue** [comment]
passed! https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/279/

thanks @lrytz
