### ISSUE TITLE
JLine 3: re-enable history timestamping

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#701]
the timestamps were disabled by @som-snytt so that JLine 2 & 3 could share the same history file, but we've gone with using a different history file name for JLine 3 (in order not to run afoul of different character encodings), so we might as well re-enable the timestamps

marked as blocker since if we're going to do it at all, we should do it before release

**Comment by SethTisue** [comment]
done, this is now part of the PR

**Comment by som-snytt** [comment]
Not objecting, but FTR, it's annoying to switch between `scala` and `dotr` and cut/paste instead of up-arrow. Probably that is less of an issue for a latter-day point release of Scala 2, with less side/side comparisons.

**Comment by SethTisue** [comment]
Could Dotty align with what we're doing here, sometime prior to the release of Scala 3?

**Comment by som-snytt** [comment]
i.e. they also have their own history file. If that is what you mean by align. As opposed to malign.

**Comment by SethTisue** [comment]
I see they're using `.dotty_history`, and it has timestamps, so it's good we're now aligned w/r/t timestamps.

As for naming, it wouldn't make sense for Scala 2 to use `.dotty_history`, so it seems fine to me to expect Dotty to eventually change over to what we now have (`.scala_history_jline3`).

**Comment by som-snytt** [comment]
Yes! let doti align with scala 2 for once! Why should scala 2 do all the aligning?
