### ISSUE TITLE
PR validation has been failing (for some weeks) since Scalariform switched from maven to sbt

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#71]
and Scalariform is part of https://github.com/scala-ide/uber-build

example failure: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2026/console

**Comment by SethTisue** [comment]
@sschaef the relevant scripts that may need updating are https://github.com/scala-ide/uber-build/blob/master/uber-build.sh and possibly https://github.com/scala/scala/blob/2.11.x/scripts/jobs/integrate/ide

> Can you please tell me how to run 0.13.x sbt on your Jenkins?

scripts/jobs/integrate/ide receives the right sbt command to use in the `sbtCmd` environment variable, as provided by https://github.com/scala/scala-jenkins-infra/blob/c50554e96637ef9f1e2499dfa1d6caf8e21839ef/attributes/worker.rb#L118

to make local testing easier, in scripts we typically write `${sbtCmd-sbt}` so even if `sbtCmd` isn't set you get a reasonable default.

**Comment by kiritsuku** [comment]
Alright, I'm going to try that out.

**Comment by SethTisue** [comment]
So that Scala PR validation doesn't remain affected, and so there won't be any huge rush on a fix, I'm going to temporarily remove `integrate-ide` from `integrate-main`. You should still be able to test your changes by manually triggering jobs at https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/ (at least, I don't know of any reason that wouldn't work, since I don't have firsthand experience with this Jenkins job in particular, but it's certainly something we routinely do with our other job).

**Comment by dragos** [comment]
@sschaef I guess this involves the uber-build, and there's a [validator](https://github.com/scala-ide/uber-build/blob/master/config/validator.conf) configuration especially for this purpose. I guess that one should pass locally before you need to test it on Jenkins.

Because of these hidden dependencies I'm always wary of build changes, so if this is too much I'd say we go back to maven. Neither refactoring nor scalariform have complicated builds, so the pain will quickly outweight any benefits.

**Comment by kiritsuku** [comment]
Yeah, for the next time I'll remember this. The good side of it is that I understand the build chain better every time better when something breaks.

**Comment by SethTisue** [comment]
one possible consideration: the Scala community build expects sbt. (uh, well maybe dbuild has some maven support? even if it does, I doubt it's actively maintained)

**Comment by dragos** [comment]
@sschaef did you manage to track down the regression? It may be difficult to turn the validation back on, since regressions may creep into Scala

**Comment by kiritsuku** [comment]
Yes it is nearly fixed. I'm going to fix it completely probably today or tomorrow.

**Comment by kiritsuku** [comment]
@SethTisue I fixed the 2.11.x build locally. I can upload my changes but first I would like to understand how exactly scala-ide gets the Scala dependency. Could you show me how the script of this Jenkins job https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/ runs uber-build?

**Comment by SethTisue** [comment]
I guess you figured it out and no longer have a question? but I'll answer anyway, there is a one-to-one correspondence between Jenkins job names and files in `scripts/jobs`, so integrate-ide is just running https://github.com/scala/scala/blob/2.11.x/scripts/jobs/integrate/ide

**Comment by kiritsuku** [comment]
Thanks, that is helpful. I already did a test run but it failed at some other point. Still takes me a little bit longer.

**Comment by kiritsuku** [comment]
The sbt build works now but it can't find the Scala dependency: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2028/console

Maybe the dependency is already gone. Are the Scala dependencies cached or are they removed after a build has been finished?

**Comment by SethTisue** [comment]
@sschaef In that failure log, I don't see sbt looking for the Scala artifacts where it should be, namely on  https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/ (where they are archived indefinitely afaik)

Note that when the integrate/ide script runs uber-build.sh, it sets both `prRepoUrl` and `IDE_M2_REPO` to that URL. (Why two variables with the same value, I don't know.) The relevant lines are https://github.com/scala/scala/blob/c06aed997f5a0c98434d7cec0ebe5f0da3de790e/scripts/jobs/integrate/ide#L24-L27 . So I guess you need to change uber-build.sh so that it passes that information on to sbt?

**Comment by kiritsuku** [comment]
Oh, you are right. I completely oversaw this part. In that case I only have to add them through a resolver.

**Comment by kiritsuku** [comment]
Scala 2.11.x CI is back on green: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2034/

Nevertheless, I had to disable two tests because they fail on Scala Jenkins but not on Scala IDE Jenkins. I'm going to look into that next week. If in the next days I can't find out why the tests are failing, we can let them on ignored status and reactivate scala-ide integration in order to avoid potential breaking changes.

**Comment by SethTisue** [comment]
I re-added `integrate-ide` to `integrate-main` and deployed the change. optimistically closing this ticket. thanks @sschaef!

**Comment by kiritsuku** [comment]
In order to be more safe in future, would you please add me to the email notifications about failed builds on the scala-2.11.x-integrate-ide job? I don't have permissions to add myself. The email is mail@antoras.de

**Comment by SethTisue** [comment]
> would you please add me to the email notifications about failed builds on the scala-2.11.x-integrate-ide job

I don't have manager rights on https://groups.google.com/a/typesafe.com/forum/#!forum/pr-scala-integrate-ide, but I believe @dragos does

**Comment by kiritsuku** [comment]
Haha, that is cool. I didn't know the Scala Jenkins works so differently to the Scala IDE Jenkins. Even more interesting is that so many things can be plugged into Jenkins. Some kind of powerful software.
