### ISSUE TITLE
Wconf improvements

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#710]
Just to write the ideas down somewhere

  * Allow filtering by source line content. Could be useful for unused imports (`@nowarn` is syntactically not possible there).
  * Scala version filter, e.g., `@nowarn("scalaVersion=2.13") ...` to only silence warnings when the Scala compiler version is 2.13.

**Comment by SethTisue** [comment]
I feel like if people want these improvements, they'll tell us. To my knowledge, users seem to be doing fine with what we have already given them.

**Comment by som-snytt** [comment]
or add to dotty ticket and backport...
