### ISSUE TITLE
Travis-CI nightlies failing at `triggerScalaDist`

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#714]
at https://travis-ci.org/github/scala/scala/builds we see it beginning to fail 2 days ago, starting with https://travis-ci.org/github/scala/scala/builds/700915013

the first failed build was after the merge of scala/scala#9076 (and no other PRs were merged since the last green build). but that PR can't be responsible, so something must have changed at Travis-CI's end, or in the wider environment somehow. all nightly builds since then have also failed

this is almost certainly a blocker for releasing of 2.13.3

**Comment by SethTisue** [comment]
the failure logs seem nearly devoid of clues, they just say:

```
$ triggerScalaDist
failed to start job
```

but this is more of a clue than it appears — the error message is specific to https://github.com/scala/scala/blob/d23424cd3aa17f7ad95b81018c70ceed2566962b/scripts/common#L190

so it's the call to https://api.travis-ci.org that's failing

**Comment by SethTisue** [comment]
We are using API v3, but that's the current version according to https://docs.travis-ci.com/api/

https://blog.travis-ci.com has nothing recent relevant

to my knowledge we didn't change anything over at https://github.com/scala/scala-dist

so probably I'll need to modify `scripts/common` to output more diagnostic information to help troubleshoot

**Comment by lrytz** [comment]
"operation requires create_request access to repository" (full log below).

Navigating the travis UI, i realized that I lost admin permission on travis/scala/scala (restart/cancel/trigger builds). I've seen that happening a number of times before, and what fixed it was clicking "Sync account" on https://travis-ci.org/account, and doing a logout-login. That's also the case now, so I have permissions again.

It turns out that our travis scripts use an [API token from my account](https://github.com/scala/scala/blob/d23424cd3aa17f7ad95b81018c70ceed2566962b/.travis.yml#L73):
```
    - secure: "..." # TRAVIS_TOKEN (login with GitHub as lrytz)
```

So yeah, it's fixed now, triggering worked in my test branch. I re-started the build for d23424c at https://travis-ci.org/github/scala/scala/jobs/701711199.

```
$ triggerScalaDist
*   Trying 35.237.114.195...
* Connected to api.travis-ci.org (35.237.114.195) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 594 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.travis-ci.org (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: OU=Domain Control Validated,OU=EssentialSSL Wildcard,CN=*.travis-ci.org
* 	 start date: Tue, 26 Jun 2018 00:00:00 GMT
* 	 expire date: Mon, 24 Aug 2020 23:59:59 GMT
* 	 issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> POST /repo/scala%2Fscala-dist/requests HTTP/1.1
> Host: api.travis-ci.org
> User-Agent: curl/7.47.0
> Accept: */*
> Travis-API-Version: 3
> Authorization: token [secure]
> Content-Type: application/json
> Content-Length: 218
> 
} [218 bytes data]
* upload completely sent off: 218 out of 218 bytes
< HTTP/1.1 403 Forbidden
< Date: Thu, 25 Jun 2020 07:07:31 GMT
< Content-Type: application/json
< Content-Length: 393
< Connection: keep-alive
< Vary: Accept-Encoding
< Strict-Transport-Security: max-age=15724800; includeSubDomains
< X-Endpoint: Travis::API::V3::Services::Requests::Create
< X-OAuth-Scopes: public,private
< Vary: Accept-Encoding
< X-Rack-Cache: invalidate, pass
< X-Request-ID: 7ffe424497c24369023e3c7aba61e6ee
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified, X-Request-ID
< 
{ [393 bytes data]
* Connection #0 to host api.travis-ci.org left intact
failed to start job: {
  "@type": "error",
  "error_type": "insufficient_access",
  "error_message": "operation requires create_request access to repository",
  "resource_type": "repository",
  "permission": "create_request",
  "repository": {
    "@type": "repository",
    "@href": "/repo/409744",
    "@representation": "minimal",
    "id": 409744,
    "name": "scala-dist",
    "slug": "scala/scala-dist"
  }
}403
```
