### ISSUE TITLE
remove Windows-invalid characters from file path in 2.13.x branch

### ISSUE THREAD

**Issue by unkarjedy** [scala/scala-dev#717]
If you do `git pull` on scala repo in branch `2.13.x` on Windows you'll get

```
$ git pull
error: invalid path 'test/tasty/pos/src-3/tastytest_>>>/package.scala'
Updating b91a1445fc..a6e1a6f476
```
Note that `>` character is forbidden in Windows.
I could push the fix myself if I just could `git pull`, `rename`, `git push`, but I can't, cause.... I'm on Windows and `git pull` fails =D
Could you please rename the path to some Windows-friendly name?

**Comment by lrytz** [comment]
cc @bishabosha - does the directory name matter for the test?

**Comment by SethTisue** [comment]
this is also failing our Windows CI runs at https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-windows/ (I'd have noticed sooner, but I was on vacation)

**Comment by SethTisue** [comment]
> does the directory name matter for the test? 

it appears to me that it does not. the directory contains support code for a test. so if that support code still gets picked up, I think we're good..... I think, but Jamie can confirm when he gets back. in the meantime, I'll merge this once it passes CI on both Linux and Windows: https://github.com/scala/scala/pull/9135
