### ISSUE TITLE
PRs skipped when branch merging for 2.13.4

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-dev#721]
branch merge PR: scala/scala#9206

skipped PRs:
- ~scala/scala#9022 scala/scala#9178 `-Ydelamdify:method-ref`~ not worth it
- ~scala/scala#8986 Map.++ optimizations~
- ~scala/scala#9091 reuse empty array instances~ hard cherry-pick (Array and BitSet things have changed in 2.13)
- scala/scala#9102 don't box double.isNaN -> https://github.com/scala/scala/pull/9261

**Comment by NthPortal** [comment]
`Map.++` optimisations are unlikely to be portable to 2.13

**Comment by dwijnand** [comment]
And again https://github.com/scala/scala/pull/9231, skipping:

* ~scala/scala#9216 avoid some LazyVals, prefer AbstractFunction~ hard cherry-pick (HashMap/HashSet and even MurmurHash3 have changed in 2.13)
* scala/scala#9218 ListMap is reverse oriented, so use that for foldRight -> https://github.com/scala/scala/pull/9262
* ~scala/scala#9214 ListMap.last should not generate additional garbage~ hard: IndexedSeqLike and LinearSeqLike have been reworked

Lukas mentioned that ListMap is still a reversed linked list internally, so perhaps those ListMap changes are recoverable.

**Comment by dwijnand** [comment]
Spun out 2 PRs, the rest I've re-skipped.
