### ISSUE TITLE
Regression: scala.reflect.io.ZipArchiveTest consistently fails on Windows

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#724]
first failed run https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-windows/1896/

`[error] Test scala.reflect.io.ZipArchiveTest.URL$u0020archive$u0020works failed: java.nio.file.FileSystemException: y:\jenkins\tmp\junit618511732972925268.zip: The process cannot access the file because it is being used by another process.
[error] , took 0.014 sec`

**Comment by som-snytt** [comment]
I forgot that the fix was buried in the `Using` infrastructure.

https://github.com/scala/scala/blob/v2.13.3/src/testkit/scala/tools/testkit/TempDir.scala#L43

**Comment by som-snytt** [comment]
I wonder why that code doesn't attempt to register a shutdown hook for file deletion in the `isWindows` case.

Also there should be an alias for `isWindows` called `whyWeCantHaveNiceThings`.

**Comment by SethTisue** [comment]
probably fixed by scala/scala#9236, but let's leave this open until that's confirmed over at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-windows/

**Comment by som-snytt** [comment]
Hey, it worked! `fsdow`.

This made me fire up the old cygwin I installed last spring, when pandemic lockdown was a passing thing. Now I have a couple dozen `cygwin64/tmp/junit*` files from April and yesterday.
