### ISSUE TITLE
2.13.4: regression in typer, affecting Shapeless + Cats

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#725]
[in the community build](https://github.com/scala/community-build/pull/1251) I found that both cats and shapeless won't build due to a StackOverflowError in typer (`TypeMaps$SubstSymMap.apply(TypeMaps.scala:782)`):

* https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1991/artifact/logs/cats-build.log
* https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1991/artifact/logs/shapeless-build.log

much of the build is downstream of either cats or shapeless, so it's likely other repos are affected as well

the regression was somewhere between scala/scala@8c86b7d and scala/scala@8b9858e

```
* 8b9858e371 - (HEAD -> 2.13.x, origin/HEAD, origin/2.13.x) Merge pull request #9085 from eed3si9n/wip/deprecate-prefix-unary-nilary (4 days ago) <Lukas Rytz>
* ac19b3452a - Merge pull request #9232 from NthPortal/topic/copyToArray-fixes/PR (4 days ago) <Dale Wijnand>
* 25472e4559 - Merge pull request #9193 from joroKr21/hk-bounds-check (4 days ago) <Lukas Rytz>
* f76aa08a1f - Merge pull request #9234 from NthPortal/topic/SeqView-Sorted-eager (4 days ago) <Lukas Rytz>
* ff3185ae06 - Merge pull request #9233 from Philippus/issue-12180 (5 days ago) <Lukas Rytz>
* 630a95c3a7 - Merge pull request #9231 from dwijnand/merge-in-2.12 (5 days ago) <Dale Wijnand>
* 7189d9830b - Merge pull request #9172 from joroKr21/dealias-subst (5 days ago) <Dale Wijnand>
* ccb7657760 - Merge pull request #9221 from cahilltr/issue-12146 (5 days ago) <Dale Wijnand>
* 8891679079 - Merge pull request #8782 from martijnhoekstra/darn1tuples (7 days ago) <Princess | April>
* 0b1b71a756 - Merge pull request #9096 from ShapelessCat/fix-link-in-rootdoc (7 days ago) <Dale Wijnand>
* a1e2a18995 - Merge pull request #9060 from Lasering/issue/9785 (7 days ago) <Dale Wijnand>
```

@joroKr21 think it might be one of your two?

I guess the next step is to bisect it to find out, but I'm out of time for the day

**Comment by joroKr21** [comment]
This must be scala/scala#9172

Unfortunately I won't have time to try and fix it so I suggest just reverting it and reopening the issues.

**Comment by joroKr21** [comment]
My guess would be some problem with `Id`.
PR: scala/scala#9244

**Comment by dwijnand** [comment]
Let's let Seth confirm with a CB success.
