### ISSUE TITLE
Travis jobs for scala/scala timing out frequently

### ISSUE THREAD

**Issue by NthPortal** [scala/scala-dev#726]
I've noticed Travis jobs for scala/scala timing out frequently, perhaps as much as 1 in 3 times. Is there anything we can do to either get our time limit raised, or to split the main job up into smaller parts that take less time?

**Comment by SethTisue** [comment]
or just (“just”) switch to GitHub Actions (https://github.com/scala/scala-dev/issues/508)

**Comment by som-snytt** [comment]
Maybe it's just pandemic fatigue.

**Comment by NthPortal** [comment]
Do GitHub Actions not have time limits? I'm not super familiar with them

**Comment by dwijnand** [comment]
I think we're not seeing these any more as https://github.com/scala/scala/pull/9268 made the jobs shorter (splitting the jobs).  If they start happening again we're also going to migrate from travis-ci.org to travis-ci.com (#728) and we might even migrate off of Travis CI entirely (#507).

**Comment by xuwei-k** [comment]
> Do GitHub Actions not have time limits?

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

> The maximum number of minutes to let a job run before GitHub automatically cancels it. Default: 360
