### ISSUE TITLE
Test scala.collection.immutable.ListMapTest.foldRightAllocations is flaky

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#727]
example failure: https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/13195/consoleFull  I've seen it repeatedly lately

**Comment by som-snytt** [comment]
The Democrats have folded to the right over allocations of funds, is that related?

**Comment by SethTisue** [comment]
on Windows, too: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/1550/consoleFull
