### ISSUE TITLE
CLA checker fails regularly due to API quota

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#729]
See https://github.com/scala/scala-collection-compat/pull/273#issuecomment-561290746

lightbend.com provides a CLA checker that works with GitHub webhooks.

https://github.com/lightbend/lightbend.com/issues/2369 (private link) is about allowing Scala CLA checking using Lightbend's bot (currently it only supports the Lightbend CLA, should not be a big thing). After that (these are instructions for the Lightbend CLA)

> you should simply need to add a webhook with payload https://www.lightbend.com/contribute/cla/_github-hook and content type as json. Then select individual events only - with PRs being the only thing needed
> Then add the user lightbend-cla-validator with write access
> I think it will work with typesafe-cla-validator, however I’d suggest going with the updated validator

**Comment by SethTisue** [comment]
has anyone seen this recently? I haven't
