### ISSUE TITLE
Release 2.13.4

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-dev#730]
- SCALA_VER_BASE="2.13.4"
- SCALA_VER_SUFFIX=""
- SCALA_SHA=39148e4ec34a5c53443dd1b25ceec2308cd097fe
- DIST_SHA=????????????????????????????????????????
- SCALA_VER="$SCALA_VER_BASE$SCALA_VER_SUFFIX"

Key links:
  - scala/scala milestone: https://github.com/scala/scala/milestones/2.13.4 ([list][PR-list])
  - scala/bug milestone: https://github.com/scala/bug/milestones/2.13.4 ([list][bug-list])
  - scala/scala-dev milestone: https://github.com/scala/scala-dev/milestones/2.13.4 ([list][dev-list])
  - Discourse topic: https://contributors.scala-lang.org/t/coming-soon-scala-2-13-4/4555
  - release notes draft: https://github.com/scala/scala-dev/blob/scala-dev/releases/2.13.4.md

[PR-list]: https://github.com/scala/scala/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+milestone%3A2.13.4
[bug-list]: https://github.com/scala/bug/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A2.13.4
[dev-list]: https://github.com/scala/scala-dev/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A2.13.4

---

### N weeks before the release
- [x] Wind down PR queue. There has to be enough time after the last (non-trivial) PR is merged and the next phase. The core of the eco-system needs time to prepare for the final!
- [x] Triage scala/bug and scala/scala-dev tickets
- [x] Create next scala/scala milestone, move the magical "Merge to 2.13.x" description to it (so Scabot uses it as default for new PRs), move pending PRs
- [x] Create next scala/bug milestone, move pending issues
- [x] Create next scala/scala-dev milestone, move pending issues
- [x] Check PRs assigned to the milestone, also check WIP
- [x] Announce expected release date and current nightly "release candidate" (nightly sha-mangled version) at https://scala-ci.typesafe.com/artifactory/scala-integration/ on https://contributors.scala-lang.org/c/announcements
- [x] Also notify Scala Center advisory board members of the upcoming release, so they can help test if they want (Seth can handle this, if asked)

### Release announcement / notes
- [x] Notify community on https://contributors.scala-lang.org/c/announcements
- [x] Review merged PRs, make sure release-notes label is applied appropriately
- [x] PRs with release-notes label must have excellent title & description (title will be pasted literally in release note bullet list)
- [x] Draft release notes (to be published once GitHub tag is pushed) https://github.com/scala/scala-dev/blob/scala-dev/releases/2.13.4.md
- [x] On contributors thread, link to release note gist and request feedback

### N days before release
- [x] Announce no more PRs will be merged unless last-minute regressions are found. Re-iterate current nightly sha version for testing.
- [x] Community build
  - [x] JDK 8: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk8-integrate-community-build/3900/
  - [x] JDK 11: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2176/
  - [x] JDK 15: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk15-integrate-community-build/1381/
- [x] Windows Jenkins job
    - if there isn't already a nightly run on the exact right SHA (check the log), manually trigger one
    - https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/1576/
- [x] Run test suite (`testAll`) on JDK 11 and 15
  - (Our CI ought to do this, but until we get that set up, it can be done locally.)
- [x] Check any merged PRs accidentally assigned to the next milestone in this branch, and re-assign them to this milestone
- [x] Merge in any older release branch
- [x] Check module versioning (is everything in versions.properties up to date?) ~https://github.com/scala/scala/pull/9294~
- [x] ~On major release, bump PickleFormat version~
- [x] Close the scala/scala and scala/bug milestones

### Point of no return

Once sufficient time has passed since last merged PR, it's time to cut the release!

How long we wait depends on what kind of release it is. For a major release, it might be 1-2 weeks, to give core projects time to try out the preceding release candidate and/or the current candidate nightly. For point releases, assuming we've given the community ahead-of-time warning and kept them appraised of progress on the Discourse thread, and assuming the last changes merged seem sufficiently safe, we might build the next day.

- [x] Make sure there are no stray staging repos on sonatype
- [x] Trigger a custom build on [travis](https://travis-ci.org/scala/scala)
  - Select the correct branch
  - Custom config: `before_script: export SCALA_VER_BASE=2.13.4 SCALA_VER_SUFFIX=""`
  - [x] Check the build status https://travis-ci.org/github/scala/scala/builds/744616633
  - [x] Check that the scala/scala job also triggered a following scala/scala-dist job: https://travis-ci.org/github/scala/scala-dist/builds/744622584
  - [x] Create the scala/scala tag locally: `git tag -s -m "Scala 2.13.4" v2.13.4 39148e4ec34a5c53443dd1b25ceec2308cd097fe`
  - [x] Create scala-dist tag locally: `git tag -s -m "Scala 2.13.4" v2.13.4 4218dfc75b9e2a5310b7abde28d3d6ba8e611601`
  - [x] Note the repos to be promoted after tag is cut (see travis log)
    - https://oss.sonatype.org/content/repositories/orgscala-lang-2229
	- https://oss.sonatype.org/content/repositories/orgscala-lang-2230
	- https://oss.sonatype.org/content/repositories/orgscala-lang-2231
	- https://oss.sonatype.org/content/repositories/orgscala-lang-2232
- [x] Sanity check jar/pom
  - https://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-compiler/2.13.4/
  - in particular, if the release was staged multiple times, double check that https://oss.sonatype.org/content/repositories/staging/ has the files from the most recent build
- [x] Check that JARs haven't mysteriously bloated — compare sizes to previous release. We have no other backstop for this.
- Remember, tags are forever, so are maven artifacts (even staged ones, as they could end up in local caches) and S3 uploads (S3 buckets can be changed, but it can takes days to become consistent)
- [x] Push scala/scala tag: `git push https://github.com/scala/scala.git v$SCALA_VER`
- [x] Add release notes to https://github.com/scala/scala/releases/tag/v$SCALA_VER
- [x] Push scala/scala-dist tag: `git push https://github.com/scala/scala-dist.git v$SCALA_VER`
- [x] Trigger two scala-dist jobs on travis (https://travis-ci.org/scala/scala-dist) with custom config. must use full-length SHAs!
  - `before_script: export version=$SCALA_VER scala_sha=$SCALA_SHA mode=archives`: https://travis-ci.org/github/scala/scala-dist/builds/744628712
  - `before_script: export version=$SCALA_VER scala_sha=$SCALA_SHA mode=update-api`: https://travis-ci.org/github/scala/scala-dist/builds/744628790
- [x] Promote staging repos: `st_stagingRepoPromote [scala-repo]`, `st_stagingRepoPromote [modules-repo]` (or use oss.sonatype.org web UI)

### Check availability
- [x] Check release on sonatype: https://oss.sonatype.org/content/repositories/releases/org/scala-lang/scala-compiler/$SCALA_VER/
- [x] Check the release on maven central: https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/$SCALA_VER/

### When everything is on maven central
- [x] Prepare PR to https://github.com/scala/scala-lang/ (using scala/make-release-notes which requires a staged release and a pushed tag)
  - `documentation/api.md`
  - `download/index.md`
  - `_config.yml` (update devscalaversion or scalaversion)
- [x] Prepare PR to https://github.com/scala/docs.scala-lang/
  - `api/all.md`, `_config.yml`
- [x] make sure the draft release notes are on GitHub tag: https://github.com/scala/scala/releases/tag/v$SCALA_VER
- [x] Pre-announce the release on https://contributors.scala-lang.org/c/announcements
- [x] ~On 2.13.0 only: (manually) update the `current` symlink for the API docs~
  - https://github.com/scala/scala-dist/blob/2.13.x/scripts/jobs/release/website/update-api#L15
- [x] Check that the API docs are published
  - [x] https://www.scala-lang.org/api/2.13.4/
  - [x] https://www.scala-lang.org/api/2.13.x/
- [x] Merge the scala-lang PR and the docs.scala-lang.org PR
  - [x] https://github.com/scala/scala-lang/pull/1181
  - [x] https://github.com/scala/docs.scala-lang/pull/1823
  - [x] wait for them to arrive on the websites and make sure they look okay

### Modules
- [x] ~build and release scala-collection-compat and other modules (or open tickets asking that the maintainers do so)~
    - this work has moved to https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md
- [x] ~if it's a 2.12.x release, publish macro paradise for the new version~

### Announcements
- [x] Scala Users discourse https://users.scala-lang.org
- [x] add a reply on the same https://contributors.scala-lang.org thread where you announced that the release process was starting
- [x] Tweet from [@scala_lang](https://twitter.com/scala_lang)
- [x] https://gitter.im/scala/scala
    - [x] if you feel like it, say something in https://gitter.im/scala/contributors too
- [x] ask Seth to announce on #scala IRC

### Afterwards
- [x] Check the release on maven search (may take a few hours):
  - https://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.scala-lang%20v%3A$SCALA_VER
- [x] ~Create PR to add/update spec links on scala-lang.org~ (example: https://github.com/scala/scala-lang/pull/1050)
- [x] Create a scala/scala PR to update `versions.properties` and the `baseVersion` in `build.sbt`.
  - If it's a major bump, also update MiMa base version, exclusion filters, and `spec/_config.yml`.
- If it's a major bump:
  - [x] Update `latestSpecVersion` in `spec/_config.yml` on the old branch, so that spec is marked as no longer current
  - [x] Ditto for the nightly build and spec links in `_data/footer.yml` and `_data/doc-nav-header.yml` on docs.scala-lang.org
- [x] Create PR to update https://github.com/lightbend/lightbend-technology-intro-doc/blob/master/docs/modules/getting-help/pages/build-dependencies.adoc
- [x] Consider updating https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
- [ ] (Lightbend) Publish scala-fortify-plugin
- [x] (Lightbend) Update [WhiteSource](https://github.com/lightbend/scala-team/wiki/Whitesource)
- [x] (Lightbend) Notify eng-updates
- [x] Close this ticket and close the scala-dev milestone

**Comment by SethTisue** [comment]
Congratulations, Dale, on your first Scala release! 🍻
