### ISSUE TITLE
2.12.13 configurable-warnings backport backported 2.13.1 deprecations

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#731]
at least, I'm guessing this is configurable warnings related

```
~/scala.212 % git grep 2\\.13\\.1
src/compiler/scala/tools/nsc/reporters/Reporter.scala:  @deprecatedOverriding("override doReport instead", "2.13.1") // overridden in scalameta for example
src/compiler/scala/tools/nsc/reporters/StoreReporter.scala:  @deprecated("use the constructor with a `Settings` parameter", "2.13.1")
```

was it intentional to backport these deprecations? if so, the deprecation version should say 2.12.13, not 2.13.1. but is it necessary/desirable to deprecate at all in 2.12.x?

this came up over at https://ci.lightbend.com/view/Fortify/job/scala-fortify-plugin/888/console (Lightbend-only link)

**Comment by som-snytt** [comment]
> (Lightbend-only link)

aka LOL

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/9289
