### ISSUE TITLE
Look at community build exclusions before cutting 2.12.13

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#736]
https://github.com/scala/community-build/blob/390e5695c014335a0c49027f471dc755a29ad6fb/report/Report.scala#L69-L76

- [x] scala-rewrites https://github.com/scala/scala/pull/9297 https://github.com/scala/community-build/pull/1274
- [x] splain https://github.com/scala/community-build/pull/1273
- [x] linter https://github.com/scala/community-build/pull/1273
- [x] scala-refactoring https://github.com/scala/community-build/pull/1273
- [x] scalameta https://github.com/scala/community-build/pull/1275
- [x] zinc/silencer/mdoc/scalafix/scala-rewrites/sbt https://github.com/scala/community-build/pull/1281
- [x] ~scala-refactoring https://scala-ci.typesafe.com/job/scala-2.12.x-jdk8-integrate-community-build/6197/artifact/logs/scala-refactoring-build.log~ flaky

**Comment by dwijnand** [comment]
scala-rewrites needs a Scala SHA update which includes https://github.com/scala/scala/pull/9297, but I've optimistically checked it off for now.

**Comment by dwijnand** [comment]
https://github.com/dwijnand/community-build/tree/2.12.13-CB-fixes
->
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk8-integrate-community-build/6186/

**Comment by dwijnand** [comment]
@retronym this branch https://github.com/dwijnand/scalameta/commit/4b7d013f5c14f81ba5718ad44c52e8e035c63f3c

**Comment by retronym** [comment]
@dwijnand the assertion errors where caused by using an incompatible version of the macro-paradise plugin.

```diff
diff --git a/build.sbt b/build.sbt
index b323e2491..966ad5c06 100644
--- a/build.sbt
+++ b/build.sbt
@@ -674,7 +674,7 @@ lazy val sharedSettings = Def.settings(
   scalaVersion := LanguageVersion,
   crossScalaVersions := LanguageVersions,
   organization := "org.scalameta",
-  addCompilerPlugin("org.scalamacros" % "paradise_2.12.6" % "2.1.0"),
+  addCompilerPlugin("org.scalamacros" % "paradise_2.12.12" % "2.1.1"),
   scalacOptions ++= Seq("-deprecation", "-feature", "-unchecked"),
   scalacOptions.in(Compile, doc) ++= Seq("-skip-packages", ""),
   scalacOptions.in(Compile, doc) ++= Seq("-implicits", "-implicits-hide:."),
```

But even that most-recent version of the plugin is binary incompatible with 2.12.next:

```
java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
	at org.scalamacros.paradise.reflect.ReplIntegration.tellReplAboutExpansion(ReplIntegration.scala:21)
	at org.scalamacros.paradise.reflect.ReplIntegration.tellReplAboutExpansion$(ReplIntegration.scala:20)
	at org.scalamacros.paradise.Plugin.tellReplAboutExpansion(Plugin.scala:8)
	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand(Namers.scala:391)
	at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:339)
	at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:329)
```

The options are to restore compatibility in the compiler or to build a local copy of https://github.com/scalamacros/paradise with 2.12.next.

UPDATE: I see you've restored it in https://github.com/scala/scala/pull/9297

**Comment by dwijnand** [comment]
https://github.com/scalacommunitybuild/scalameta/commit/4b7d013f5c14f81ba5718ad44c52e8e035c63f3c + https://github.com/dwijnand/community-build/commit/64c2041ae73e282ae6b7037308e19cd8f3d27194
= https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk8-integrate-community-build/6192/

**Comment by dwijnand** [comment]
> [info] Project scalameta-------------------: SUCCESS (project rebuilt ok)

**Comment by dwijnand** [comment]
Finally done... 😴
