### ISSUE TITLE
nightly release-package-unix jobs failing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#74]
see e.g. https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-unix/356/console

```
java.lang.RuntimeException: Error tarballing /home/jenkins/workspace/scala-2.11.x-release-package-unix/target/universal-docs/scala-docs-2.11.8-f6bd712-nightly.txz. Exit code: 2
```

perhaps another consequence of https://github.com/scala/scala-dist/pull/154 and/or https://github.com/scala/scala-dist/pull/156

**Comment by SethTisue** [comment]
last green build was Jan 15 https://github.com/scala/scala-dist/commit/8b824c1317c49e098da65bd4bf35db466c330b3b  
first red build was Jan 16 https://github.com/scala/scala-dist/commit/d40dd6f305b99184b53f98325e7a2db93a7159e1

the latter is the merge commit for #156, so that almost certainly must be the source. it included version bumps for both sbt-native-packager and sbt

**Comment by SethTisue** [comment]
if I ssh to jenkins-worker-ubuntu-publish and run `sbt -Dproject.version=2.11.7` followed by `universal-docs:packageXzTarball`, I get:

```
Running with tar /tmp/sbt_7bbb8416/scala-docs-2.11.7.tar scala-2.11.7
tar: Old option 'b' requires an argument.
Try 'tar --help' or 'tar --usage' for more information.
[trace] Stack trace suppressed: run last universal-docs:packageXzTarball for the full output.
[error] (universal-docs:packageXzTarball) Error tarballing /home/jenkins/workspace/scala-2.11.x-release-package-unix/target/universal-docs/scala-docs-2.11.7.txz. Exit code: 2
```

it seems likely this is the cause, and the information about "old option 'b'" being the culprit just isn't showing up in the Jenkins log for some reason

UPDATE:

`universal-docs:packageZipTarball` gives a little bit different error:

```
> universal-docs:packageZipTarball
Running with tar /tmp/sbt_1205a627/scala-docs-2.11.7.tar scala-2.11.7
tar: invalid option -- '/'
Try 'tar --help' or 'tar --usage' for more information.
[trace] Stack trace suppressed: run last universal-docs:packageZipTarball for the full output.
[error] (universal-docs:packageZipTarball) Error tarballing /home/jenkins/workspace/scala-2.11.x-release-package-unix/target/universal-docs/scala-docs-2.11.7.tgz. Exit code: 64
[error] Total time: 4 s, completed Jan 21, 2016 7:02:01 PM
```

**Comment by SethTisue** [comment]
@muuki88 does this ring any bells with you...?

**Comment by SethTisue** [comment]
https://github.com/sbt/sbt-native-packager/pull/666 is the culprit, I think. `tar` is supposed to be invoked with `-pcvf`, but isn't being invoked with any flags at all:

```
> universal-docs:packageXzTarball::universalArchiveOptions
[info] List()
```

because since 666, `universalArchiveOptions in packageKey := Nil`, should be `Seq("-pcvf")` IMO (or perhaps include `--force-local` too, I see in other PRs there's been back-and-forth on that). there's a `defaultUniversalArchiveOptions` that has the right value, but for some reason it isn't taking effect.

I should file a bug in the sbt-native-packager repo. I think we can work around it with:

```
set universalArchiveOptions in (UniversalDocs, packageZipTarball) := Seq("--force-local", "-pcvf")
set universalArchiveOptions in (UniversalDocs, packageXzTarball) := Seq("--force-local", "-pcvf")
```

when troubleshooting this, a `rm -rf /tmp/sbt_*` may be necessary from time to time to keep the partition from filling up

**Comment by muuki88** [comment]
@SethTisue this is interesting. Please fill a bug and lets see how we can fix  this.

**Comment by SethTisue** [comment]
a `rm -rf /tmp/sbt_* may be needed from time to time when troubleshooting this in order to avoid filling up the partition

**Comment by SethTisue** [comment]
> Please fill a bug

https://github.com/sbt/sbt-native-packager/issues/731

**Comment by SethTisue** [comment]
worked around it for now with https://github.com/scala/scala-dist/pull/159

**Comment by SethTisue** [comment]
yay, last night's automatic run succeeded https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-unix/362/consoleFull
