### ISSUE TITLE
resolve t10680 (exhaustivity test on Enumeration)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#752]
can you take a look @dwijnand?

```
% ls test/**/*10680*
test/files/neg/t10680.check  test/files/pos/t10680.scala
```

the `.check` file is orphaned, should it just be removed?

I feel like I read some ticket recently about `scala.Enumeration` not being subject to exhaustivity checking, but now I'm not sure where or what it was

**Comment by som-snytt** [comment]
I hit the button because I couldn't take it anymore.

https://github.com/scala/scala/pull/9323

**Comment by dwijnand** [comment]
Thank you!
