### ISSUE TITLE
spec build on travis failing

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#757]
https://github.com/scala/scala/commits/2.13.x

https://travis-ci.org/github/scala/scala/jobs/749156669

at the end:

```
...
139896437875136:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:537:
```

**Comment by SethTisue** [comment]
keeping ticket open until we are sure it's fixed. waiting on https://travis-ci.org/github/scala/scala/builds/749278427
