### ISSUE TITLE
scala-dist artifact was renamed to scaladist

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#758]
https://github.com/scala/scala/pull/9377 (camel (not kebab) case project names) changed the name of the `scala-dist` artifact to `scaladist`

https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scaladist/

the downstream jobs on travis / appveyor then failed, see status on https://github.com/scala/scala/commit/c362e07035dcc70ef713cc9c26228670b055fb8c

**Comment by SethTisue** [comment]
thanks for tracking that down

https://github.com/scala/scala/pull/9385

**Comment by SethTisue** [comment]
keeping ticket open until we are sure it's fixed. waiting on https://travis-ci.org/github/scala/scala/builds/749278427
