### ISSUE TITLE
Move `travis.yml/default.yml` off sbt-extras, onto official launcher

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#766]
As per discussion on https://github.com/scala/scala-dev/issues/765

Yes, there is a risk that somebody's repo will actually be expecting sbt-extras, but I think we should just rip that bandaid off, there is no "good time" to rip it off.

Motivation: sbt-extras is not the standard, and the proliferation of multiple launch scripts (there's a coursier one now, too) is bad for the community. I think we should discourage use or perception of sbt-extras as a de facto default. The official script should be the de facto default. It's fine for sbt-extras to exist as a power-user alternative for those who want it. (And if sbt-extras has some feature that is really so commonly needed, that feature should be ported to the official one.)

**Comment by SethTisue** [comment]
Well, I know that Eugene and I are in the strongly-pro-official-launch-script camp and @dwijnand... isn't necessarily. I guess we've already talked about this multiple times in multiple contexts... but, Dale, do you want to make an argument that's particular to this context?

**Comment by dwijnand** [comment]
As far as I can see there's no difference in context here so the arguments remain the same.

**Comment by SethTisue** [comment]
PR: #781 

At this point I'm pretty sure I'm the one actually maintaining most of the repos where this is actually used, so I'd like to go forward with this.
