### ISSUE TITLE
include a subset of the community build in merge validation

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#768]
The full community build is too expensive to run on every merge, but we may want to select a key subset (currently that's basically the IDE using uber-build instead of dbuild).

**Comment by SethTisue** [comment]
now it would be GitHub Actions, most likely :-)

the community build stuff may well eventually move off Jenkins, but until it does, I don't think this is worth tackling.

I'm even tempted to close this, since it's actually fixed in Scala 3; their community build is part of PR validation

**Comment by dwijnand** [comment]
I'm against this, as it's a huge cost.  Fixes in coverage should be addressed internally to the repo, with the community build running out of band as a safeguard.  I.e. the status quo (except with more internal addressing).

**Comment by SethTisue** [comment]
The other reason to close it is: it's very rarely the core projects that fail.
