### ISSUE TITLE
2.12.x bootstrap regression: stability test fails

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#77]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/284/consoleFull shows:

```
test.stability:
[exec] Binary files build/quick/classes/compiler/scala/tools/nsc/util/StackTracing$class.class and build/strap/classes/compiler/scala/tools/nsc/util/StackTracing$class.class differ
```

the rev tested was https://github.com/scala/scala/commit/90ee1b871236402f8543bf424a4f38d909598b3a
the last green rev was https://github.com/scala/scala/commit/1081e718f8f8e174dbf615e42b157e187d3d3886

@lrytz all of the commits in that range are yours; it appears the culprit is https://github.com/scala/scala/pull/4858 , so, assigning this ticket to you

**Comment by lrytz** [comment]
thanks for reporting! will take a look.
