### ISSUE TITLE
Investigate warnings produced by Scala 3 compiler when compiling 2.13 standard library

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#775]
With an eye towards eventually enabling fatal warnings.

For example, at https://github.com/scala/bug/issues/12408 Lukas observed that compiling the collections gives a bunch of  "the type test for ... cannot be checked at runtime" warnings.

* Some warnings could be things we should simply silence with `@unchecked` or the like
* Some warnings could be false negatives in 2 (opportunities to make Scala 2 emit warnings in more situations where it should)
* Some warnings could be Scala 3 emitting false positives
* Some warnings could indicate actual quality problems in the standard library

**Comment by som-snytt** [comment]
The deprecated case class issue is already lodged at https://github.com/lampepfl/dotty/issues/11022

**Comment by som-snytt** [comment]
The deprecation in `scala.io.Position` companion is explained at https://github.com/lampepfl/dotty/issues/12706

**Comment by lrytz** [comment]
https://github.com/scala/bug/issues/12439 covers the remaining `unchecked` warnings

`@nowarn` support (https://github.com/lampepfl/dotty/pull/12857) will handle most deprecations that Scala 3 issues.

**Comment by dwijnand** [comment]
> [scala/bug#12439](https://github.com/scala/bug/issues/12439) covers the remaining `unchecked` warnings
