### ISSUE TITLE
String concat with primitive: use the non-boxing overload of StringBuilder.append

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#78]
Currently, `"a" + 1` produces

```
new StringBuilder()
  .append((Object)"a")
  .append((Object)BoxesRunTime.boxToInteger((int)1))
  .toString()
```

Boxing is added in erasure.

Should be handled by the optimizer.

Discussion here: https://github.com/scala/scala/pull/4737.

**Comment by lrytz** [comment]
Also check if we can do something about string interpolation. `s"a${1}"` produces

```
new StringContext((Seq)Predef..MODULE$.wrapRefArray((Object[])new String[]{"a", ""}))
  .s((Seq)Predef..MODULE$.genericWrapArray((Object)new Object[]{BoxesRunTime.boxToInteger((int)1)}));
```

**Comment by soc** [comment]
See https://issues.scala-lang.org/browse/SI-9571.
I'd prefer dealing with the s-interpolator by making it a macro instead.

**Comment by lrytz** [comment]
fixed in the backend (not the optimizer) in https://github.com/scala/scala/pull/4944
