### ISSUE TITLE
Test failure on JDK 17

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#790]
https://github.com/scala/scala/runs/3739318271 shows 

```
!!  931 - run/t2318.scala                           [output differs]
% diff D:\a\scala\scala\test\files\run\t2318.check D:\a\scala\scala\test\files\run\t2318-run.log--- t2318.check
+++ t2318-run.log
@@ -1,1 +1,2 @@
+warning: two deprecations; re-run with -deprecation for details
 bar
##### Log file 'D:\a\scala\scala\test\files\run\t2318-run.log' from failed test #####

warning: two deprecations; re-run with -deprecation for details
bar
bar
```

**Comment by som-snytt** [comment]
It's already besprinkled.

`// SecurityManager is deprecated on JDK 17, so we sprinkle `@deprecated` around`

Also, filtered
```
// java: -Ddummy=fresh_jvm_needed_to_test_security_manager
// filter: WARNING.*
// for now, ignore warnings due to reflective invocation
```

**Comment by SethTisue** [comment]
My new PR is for 2.12. But yes, I forgot that already included a version of this in the 2.13 PR https://github.com/scala/scala/pull/9677

**Comment by SethTisue** [comment]
I'll update the PR so that 2.12 does it exactly the way 2.13 does, to reduce future merge conflicts. Thanks for the heads up.

**Comment by lrytz** [comment]
>  [<img alt="@joroKr21" width="20" height="20" src="https://avatars.githubusercontent.com/u/2218841?s=60&amp;u=cbe3c48f84b451c7509134add9dd70837f44adfc&amp;v=4">](/joroKr21) [joroKr21](/joroKr21) closed this in ` [fbb7794](/joroKr21/scala/commit/fbb77949a9f4522452bbd5f3cb5e0d568e75ffe3) ` [1 hour ago](#event-5385205380)

interesting github feature...

**Comment by som-snytt** [comment]
I've also been bitten by github features. Because you gave me the power.

**Comment by joroKr21** [comment]
I guess the difference is that I haven't changed the default branch in my fork to 2.13 🤔

**Comment by som-snytt** [comment]
I don't remember -- insert comic panel -- maybe I accidentally closed a ticket while pushing to my own branch?

I hope the SF Giants go deep enough into the post-season so Brandon Belt can return from his thumb fracture. And I wish San Diego Padres weren't terrible so LA Dodgers could win on the merits.

I also have many hopes for Scala and coding and our world and the people in it.
