### ISSUE TITLE
Spec publishing failed

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#791]
https://app.travis-ci.com/github/scala/scala/jobs/540626352

```
bad decrypt
652139863037395392:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:564:
```

I'll look into it.

**Comment by lrytz** [comment]
HostNotFoundError

~maybe just retry?~ no, happened again

**Comment by som-snytt** [comment]
I'm not sure lrytz is supposed to be awake now?

**Comment by SethTisue** [comment]
it failed again at https://app.travis-ci.com/github/scala/scala/builds/239027388

**Comment by SethTisue** [comment]
the last green run was https://app.travis-ci.com/github/scala/scala/jobs/540199134

**Comment by SethTisue** [comment]
the last green run was https://app.travis-ci.com/github/scala/scala/jobs/540199134

I diffed the logs and there are no real differences before the `bad decrypt` line

**Comment by SethTisue** [comment]
let's see how https://app.travis-ci.com/github/scala/scala/jobs/541506241 does

**Comment by SethTisue** [comment]
hmm, that's actually the run for the first commit I pushed, and the second commit I pushed (because the first one wasn't quite right) doesn't seem to have triggered a run, I don't know why.

I guess I'll check back in a day or two, probably there will be another run by then?

**Comment by SethTisue** [comment]
#793 needed fixing first

https://app.travis-ci.com/github/scala/scala/builds/239656900

:+1:
