### ISSUE TITLE
Travis-CI isn't operating in scala/scala

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#793]
It didn't run on https://github.com/scala/scala/pull/9697 , which is a PR we actually need it on (since Jenkins doesn't do the Dotty check)

And we don't have a cron run to show us whether https://github.com/scala/scala-dev/issues/791 is fixed

Lukas and I had talked about maybe eliminating Travis-CI from PR validation (since it's largely redundant with Jenkins, and since we only have a one-job-at-a-time plan, so it's a potential bottleneck), maybe now's the time for that, but regardless, we need Travis-CI to be working in order to do releases, and the cron job either needs to be running or be moved to GitHub Actions.

The broader discussion on the whole situation is https://github.com/scala/scala-dev/issues/751 , but I made this separate ticket because we need to do _something_ short term, even if doesn't involve longer term changes

**Comment by lrytz** [comment]
Travis ran on https://github.com/scala/scala/pull/9783

**Comment by lrytz** [comment]
https://app.travis-ci.com/github/scala/scala/requests shows "could not parse" for 2.13.x

**Comment by lrytz** [comment]
https://github.com/scala/scala/commit/a60217a611b21567b8f168c2793e92ff3b24394c#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R158 has a typo

**Comment by SethTisue** [comment]
🤦  — I'll fix it after breakfast

**Comment by SethTisue** [comment]
scala/scala@548c776deb42bc545296a1469291777a16e0b3cf

https://app.travis-ci.com/github/scala/scala/builds/239656900

👍
