### ISSUE TITLE
Add Scala Steward step to release tracking template

### ISSUE THREAD

**Issue by fthomas** [scala/scala-dev#799]
A new step about unblocking new Scala versions in Scala Steward should be added to https://github.com/scala/scala-dev/blob/scala-dev/.github/ISSUE_TEMPLATE/release.md. To unblock a new Scala version, the version numbers in https://github.com/scala-steward-org/scala-steward/blob/5b07442a61912dc7526a7559658cb8f4613560f4/modules/core/src/main/resources/default.scala-steward.conf#L7-L17 need to be bumped to the next unreleased version. See also https://contributors.scala-lang.org/t/coordinate-compiler-and-tooling-releases/5312/45.

**Comment by SethTisue** [comment]
PR: #804
