### ISSUE TITLE
Changed suffix in pr-validation-snapshot artifacts

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#801]
Using scala-runners

```
➜ ~ scala --scala-pr 9822
Resolution error: Error downloading org.scala-lang:scala-compiler:2.13.8-bin-95fed66-SNAPSHOT
  not found: /Users/luc/.ivy2/local/org.scala-lang/scala-compiler/2.13.8-bin-95fed66-SNAPSHOT/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.8-bin-95fed66-SNAPSHOT/scala-compiler-2.13.8-bin-95fed66-SNAPSHOT.pom
  not found: https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.13.8-bin-95fed66-SNAPSHOT/scala-compiler-2.13.8-bin-95fed66-SNAPSHOT.pom
```

The artifact name seems to be `scala-compiler-2.13.8-bin-95fed66-20211206.080301-1`, the suffix is no longer `-SNAPSHOT` but `-20211206.080301-1`.

https://scala-ci.typesafe.com/ui/native/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.13.8-bin-95fed66-SNAPSHOT/

I saw this in another PR as well.

**Comment by lrytz** [comment]
Even very old artifacts seem to no longer have `-SNAPSHOT` in their name, e.g.

https://scala-ci.typesafe.com/ui/native/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.13.1-bin-0449763-SNAPSHOT

So this seems to be a change in the way artifactory presents the artifacts. Not sure if I enabled untattended upgrades for artifactory, will check that.

**Comment by lrytz** [comment]
I found this setting and which looks exactly like the issue we have. But changing it from "Unique" to "Non-unique" doesn't seem to have an effect, at least on on existing artifacts.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/119636/146375954-cf17d1fd-2588-4782-a502-ab26c5e08b84.png">

**Comment by lrytz** [comment]
Didn't find out more.

https://github.com/coursier/coursier/issues/2287 seems oddly related, but downgrading to coursier 2.0.7 didn't change anything for me. Probably I'm doing something wrong.

**Comment by SethTisue** [comment]
I tried e.g. `scala --scala-pr 9902` (a PR that was pushed to within the last few days) and it worked, so I guess it's fixed.

**Comment by lrytz** [comment]
very very weird. even `scala --scala-pr 9822` form the ticket description now works.

**Comment by som-snytt** [comment]
It's too early here to pop some champagne. But maybe not too early EPFL time zone.
