### ISSUE TITLE
Make Scala 3 default version installed by homebrew-core formula

### ISSUE THREAD

**Issue by bishabosha** [scala/scala-dev#805]
I think it would be nice to have one rather than two homebrew formulas for installing Scala 2 or Scala 3. I added some steps I imagine would need to be taken:

- discover what UX might need to be added to dotty formula to reproduce UX of current Scala formula
- make scala@2.13 formula on homebrew-core
- follow up with deprecating lamepfl/brew/dotty formula and updating release procedures

**Comment by SethTisue** [comment]
@bishabosha did this happen?

**Comment by SethTisue** [comment]
@bishabosha ping

**Comment by bishabosha** [comment]
I didn't take any action towards this, I should check what's the status quo

**Comment by SethTisue** [comment]
I tried it just now and `brew install scala` gives me Scala 3 and `brew install scala@2.13` gives me 2.13 but unlinked, so it appears to me this somehow got done by somebody.

**Comment by SethTisue** [comment]
> follow up with deprecating lamepfl/brew/dotty formula and updating release procedures

however note that this part, I'm not sure about (but it's out of scope for scala-dev)

**Comment by SethTisue** [comment]
bit of followup at https://github.com/scala/scala-lang/pull/1464
