### ISSUE TITLE
Travis spec failures (wkhtmltopdf segfault)

### ISSUE THREAD

**Issue by som-snytt** [scala/scala-dev#823]
https://github.com/scala/scala/pull/10194#issuecomment-1284961860

https://github.com/scala/scala/pull/10194/checks?check_run_id=8994521898

It would be nice if Travis didn't slather a big red X just because of a random failure to make a spec pdf.

**Comment by SethTisue** [comment]
```
wkhtmltopdf $WKHTML_OPTS $SPEC_PDF_BUILD_DIR/index.html $WKHTML_TOC $HTML_FILES $PDF || true
Loading pages (1/6)
Error: Failed to load http:/, with network status code 3 and http status code 0 - Host  not found
Warning: Failed loading page http: (ignored)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
./scripts/generate-spec-pdf.sh: line 31:  7619 Segmentation fault      wkhtmltopdf $WKHTML_OPTS $SPEC_PDF_BUILD_DIR/index.html $WKHTML_TOC $HTML_FILES $PDF
````

**Comment by SethTisue** [comment]
What's the failure rate? 1 in 10? 1 in 100? (To gauge how important it is to do something about.)

This particular one succeeded when it re-ran.

Someone with a little shell-scripting fu could make it try a few times before giving up, I guess.

**Comment by som-snytt** [comment]
Someone (not I) commented on a PR somewhere that he supposed this wasn't his fault. Oh, that was why I created the ticket. I've been bitten by it not long ago, which I remember because rebuild command doesn't retrigger. Maybe comparable to a spider bite, albeit not black widow. We have excessive spiders this season.

I'll take a look at it once or twice before giving up.

However, I'm not sure why I need a spec.pdf as part of PR validation.

**Comment by SethTisue** [comment]
> However, I'm not sure why I need a spec.pdf as part of PR validation.

Perhaps it could be smart about whether anything in the `spec` directory changed?

**Comment by SethTisue** [comment]
scala/scala/10159 was bitten

**Comment by SethTisue** [comment]
I wonder whether a little loop that tried it over and over again (up to some maximum) would fix it, or whether any CI run in which it breaks is cursed.

**Comment by som-snytt** [comment]
spooky 🎃

**Comment by SethTisue** [comment]
I don't recall having seen this again lately? I wonder if something got fixed over on Travis-CI's end?

**Comment by som-snytt** [comment]
After All Souls, the spirits retreat to their benighted slumber.

**Comment by SethTisue** [comment]
🤷
