### ISSUE TITLE
Get scabot working again

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#826]
as @som-snytt and one or two others have noted, Scabot stopped doing its thing (kicking off Jenkins jobs, assigning milestones to PRs)

not clear to me what the cause might be — needs investigation

**Comment by SethTisue** [comment]
maybe there's an authorization token that needs to be explicitly given permission to the scala org? I had to do that recently for some private lightbend/* repos, I guess because of the company switching over to Okta for authorization... but I wouldn't expect scala/* to be affected, but perhaps there's some indirect connection I wouldn't have anticipated

**Comment by som-snytt** [comment]
Scabot finally joined The Great Resignation.

**Comment by lrytz** [comment]
`ssh jenkins-master` -> `sudo systemctl restart scabot` did it. not sure why it stopped, it's very rare, so 🤷‍♂️
