### ISSUE TITLE
Accessibility of old Google Groups mailing list archives?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#839]
today on Discord @som-snytt noticed that e.g. https://groups.google.com/g/scala-debate/c/Ht2EkWnnFuk is 403

I don't believe we intended to make any of the archives inaccessible to the public

I know they still exist because I can see them when I'm logged in to my personal Google account

**Comment by dwijnand** [comment]
I suffer this too, so would love to see this fixed.  I've relied on sometimes finding some mirrors, but it's not always available and it's a pain.

**Comment by som-snytt** [comment]
@dwijnand thanks for confirming, and also for suffering along with me.

**Comment by lrytz** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/119636/232428313-c467bd88-dde9-43e9-9ad6-ee71586df581.png">

**Comment by SethTisue** [comment]
list of groups I checked: scala-user, scala-announce, scala-language, scala-debate, scala-internals, scala-tools, scala-sips (the list at https://scala-lang.org/community/#archives)

groups I fixed: scala-announce, scala-debate

that leaves scala-tools. @lrytz I don't have the access to fix it — do you?

the setting to be changed is:

<img width="459" alt="Screenshot 2023-04-17 at 1 53 30 PM" src="https://user-images.githubusercontent.com/161079/232477132-4e30a9ec-f074-4e32-9d7e-a366e8a6cdf0.png">

**Comment by lrytz** [comment]
I don't see scala-tools either.
