### ISSUE TITLE
Try JLine 3.24.1

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#856]
probably we could and should upgrade for Scala 2.13.13
https://github.com/jline/jline3/releases/tag/jline-parent-3.23.0

**Comment by SethTisue** [comment]
https://github.com/jline/jline3/releases/tag/jline-parent-3.24.0 !

**Comment by SethTisue** [comment]
https://github.com/jline/jline3/commit/a2ab0474a023e2ad062978177fc6f5b3c8e69501 "Require JDK 11 and support JDK 21 at build time" is a bit ambiguous — I assume "at build time" is scoped to include "Require JDK 11", but I should double check it does still work at runtime on Java 8

**Comment by SethTisue** [comment]
> I should double check it does still work at runtime on Java 8

It doesn't! `java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;`

I guess that's why they did 3.23.0 and 3.24.0 in close succession — 3.23.0 to clear the decks before dropping support for 8.

So I guess we'll stick with 3.23.0.

**Comment by som-snytt** [comment]
This is only a problem because we are not `scala-cli`. Conversely, REPL could be a multiversion jar for any direct dependencies.

**Comment by SethTisue** [comment]
The JLine 3 folks [now say](https://github.com/jline/jline3/issues/888#issuecomment-1787279373) that 3.24.1 will restore JDK 8 support 👍
