### ISSUE TITLE
regression: Scala PR validation failing due to scala-refactoring related error

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#87]
see recent failures at https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/

attn @sschaef, @dragos

**Comment by SethTisue** [comment]
culprit appears to be https://github.com/scala-ide/scala-refactoring/pull/135

**Comment by kiritsuku** [comment]
Oh man, I forgot about you folks once again. I'm so sorry. I merged the changes to scala-ide: https://github.com/scala-ide/scala-ide/pull/1069

Your build should be back to normal health.

**Comment by SethTisue** [comment]
no worries! thanks, Simon!
