### ISSUE TITLE
contributors forum needs Discourse upgrade

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#881]
@fsalvi it had been a while since we'd upgraded Discourse, and the site dashboard was complaining that our version was out of date, so I upgraded users.scala-lang.org through the web UI and that went fine

but then, I don't know why, but on contributors.scala-lang.org it isn't able to perform the upgrade automatically

at https://contributors.scala-lang.org/admin/dashboard/whats-new it says "A critical update is available. Please upgrade!"

the upgrade page is https://contributors.scala-lang.org/admin/update and it says:

> You are running an old version of the Discourse image
> Updates via the web UI are disabled until you run the latest image. To do so log in to your server using SSH and run:

```
    cd /var/discourse
    git pull
    ./launcher rebuild app
```

is that something you could do...?

not urgent, but we shouldn't let it sit indefinitely, either

**Comment by fsalvi** [comment]
Upgrading thru the web interface doesn't always work fine. I think it can even be a bit risky (it already happened that it can get stuck in the middle of the operation)...
I did the upgrade for contributors, it should be ok now.

**Comment by SethTisue** [comment]
Thank you Fabien!

In the future, would you prefer that I refrain from attempting any upgrades myself?

**Comment by fsalvi** [comment]
Well, maybe it's better if I do them myself. Usually, I do them from time to time, but if you see it's getting too long, you can ping me!
