### ISSUE TITLE
CLA validation is currently broken

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#883]
as seen at e.g. https://github.com/scala-native/scala-native/actions/runs/11835456543/job/32978268311

the problem is at Lightbend's end. our IT staff is working on it

**Comment by SethTisue** [comment]
supposed to be fixed now

@WojciechMazur, all: let us know here if you see otherwise

**Comment by WojciechMazur** [comment]
I can confirm it works as expected now: https://github.com/scala-native/scala-native/actions/runs/11835456543/job/32986217767
