### ISSUE TITLE
Verify our Bluesky account

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#890]
currently we are `@scala-lang.bsky.social` on Bluesky. we would prefer to be `@scala-lang.org`

as per https://bsky.social/about/blog/4-28-2023-domain-handle-tutorial

@fsalvi can you add this to the scala-lang.org DNS settings?

<img width="620" alt="Screenshot 2024-12-12 at 3 00 06 PM" src="https://github.com/user-attachments/assets/4e7da4ac-96c5-4898-8cac-b4ea048f1dd6" />

I've been through this myself with tisue.net and it worked.

**Comment by fsalvi** [comment]
Could you copy/paste the text in order to avoid any mistake? Thanks.

**Comment by SethTisue** [comment]
sure, it's `_atproto` and `TXT` and `did=did:plc:mb6e2ashxeswusv7f7hwusp5`

**Comment by fsalvi** [comment]
Ok, I added it.

**Comment by SethTisue** [comment]
It worked — we are now https://bsky.app/profile/scala-lang.org

Thank you!
