### ISSUE TITLE
Profile + Tune compiler

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#91]
After bootstrapping with the all the latest and greatest in 2.12 (new optimizer, indy functions, no impl classes), a quick test shows performance is about on par with 2.11.8. I tested this by compiling `src/library` with both compilers.

Analysing the YourKit profiles of the new compiler does show some small opportunities for improvements.
- [ ] Name related operations, addressed by https://github.com/scala/scala/pull/4954 (not yet merged to 2.12.x). This needs to be merged forwards to 2.12.x
- [ ] Initialization of `TyperDiagnostics#deadCode` (which is itself dead code outside of `-Ydead-code` !)
- [ ] Initialiation of `object ArrayInstantiation` on every `typedSelect` (no need for that to be nested where it is, move to `TreeInfo`.
- [ ] Initalization of `Reporter#ERROR`. We create a lot more `Reporter` instances these times, we should try to be less allocation hungry in the common case when `hasErrors` is false.
- [ ] Consider changing `reflect.internal.util.WeakHashSet` to use `.equals` rather than `==` (to avoid type tests in `BoxesRuntimes.equals`. 

I've got additional ideas and tools that I collected previously here: https://gist.github.com/retronym/86ec6ad9ccd2c22f6148

**Comment by lrytz** [comment]
in my testing it looks like 2.12.0-M2 (maybe already M1?) is slower than 2.11.8, see https://docs.google.com/spreadsheets/d/12-GILZectCueVLeyC0HjOlnlQRZPBcTADGf9sVmGAW0/edit#gid=37831420

the slowdown in "2.12.x" (in the sheet, 2.12.0-M5) is identified, blog post with analysis coming up.

**Comment by retronym** [comment]
@lrytz Are you testing cold or warm performance?

**Comment by DarkDimius** [comment]
see also https://github.com/lampepfl/dotty/issues/1320 where I compile a silly file with cold performance.

**Comment by lrytz** [comment]
good question, i was looking at cold performance

```
for i in {1..10}; do time /Users/luc/scala/scala-2.12.0-M5/bin/scalac @files; done
```

**Comment by lrytz** [comment]
we should test both

**Comment by retronym** [comment]
There is a simple harness for repeated compilation in:

```
% scala 'scala.tools.nsc.MainBench' sandbox/test.scala
```

But we probably should build this into our new JMH suite to have a standard way to control iterations, number of forks, warmups, convergences etc/

**Comment by retronym** [comment]
``` scala
package scala.tools.nsc

import java.nio.charset.Charset
import java.nio.file.{Files, Path}

import org.openjdk.jmh.annotations.{Benchmark, Scope, Setup, State, _}

import scala.reflect.io.AbstractFile

@State(Scope.
  Thread)
class CompilerBenchmark {

  @Param(Array("-version"))
  var compilerArgs: String = _

  @Setup
  def setup {
  }

  @Benchmark
  def compile: Boolean = {
    val driver = new scala.tools.nsc.MainClass {
      override def processSettingsHook(): Boolean = {
        settings.usejavacp.value = true
        true
      }
    }
    driver.process(compilerArgs.split(" +"))
    true
  }
}
```

args.txt:

```
-nowarn
-language:_
/code/better-files/core/src/main//scala/better/files/Cmds.scala
/code/better-files/core/src/main//scala/better/files/File.scala
/code/better-files/core/src/main//scala/better/files/Implicits.scala
/code/better-files/core/src/main//scala/better/files/package.scala
/code/better-files/core/src/main//scala/better/files/Scanner.scala
/code/better-files/core/src/main//scala/better/files/ThreadBackedFileMonitor.scala
```

2.11.8

```
% sbt 'set List(scalacOptions := Nil, scalaHome := None, scalaVersion := "2.11.8")' "jmh:run -p compilerArgs=@/code/better-files/args.txt -f 1 -wi 10 -i 10 -bm avgt scala.tools.nsc.CompilerBenchmark"


Benchmark                                (compilerArgs)  Mode  Cnt  Score   Error  Units
CompilerBenchmark.compile  @/code/better-files/args.txt  avgt   10  0.621 ± 0.067   s/op
```

2.12.0-M4

```
% sbt 'set List(scalacOptions := Nil, scalaHome := None, scalaVersion := "2.12.0-M4")' "jmh:run -p compilerArgs=@/code/better-files/args.txt -f 1 -wi 10 -i 10 -bm avgt scala.tools.nsc.CompilerBenchmark"

Benchmark                                (compilerArgs)  Mode  Cnt  Score   Error  Units
CompilerBenchmark.compile  @/code/better-files/args.txt  avgt   10  0.610 ± 0.042   s/op
[success] Total time: 38 s, completed 05/07/2016 5:57:58 PM
```

2.12.0-M5:

```
% sbt set 'set List(scalacOptions := Nil, scalaHome := None, scalaVersion := "2.12.0-M5")' "jmh:run -p compilerArgs=@/code/better-files/args.txt -f 1 -wi 10 -i 10 -bm avgt scala.tools.nsc.CompilerBenchmark"
Benchmark                                (compilerArgs)  Mode  Cnt  Score   Error  Units
CompilerBenchmark.compile  @/code/better-files/args.txt  avgt   10  0.611 ± 0.055   s/op
```

I ran this by piggybacking on the library benchmark suite in `test/benchmarks`, but it occurs to me that we  should create a separate SBT project for compiler benchmarks so that the benchemark code can easily cross compile against 2.11 and 2.12.

**Comment by lrytz** [comment]
maybe we can build on top of my benchmarks repo? https://github.com/lrytz/benchmarks

**Comment by lrytz** [comment]
by the way, what is `2.12.x`? the current branch, i.e., M5? given the known regression, it would be interesting to compare against M4.

**Comment by retronym** [comment]
Oh, I just used my WIP branch for another bug for 2.12.x. Updated the comment above to just show `M4` and `M5`.

We should measure with a number of JVM forks (I only used `-f1` above to explore quickly) and possibly more iterations to reduce the variance.

**Comment by retronym** [comment]
Not sure about the best place for the compiler JMH harness (in scala/scala or in scala/something-else?). 

I expect we'll have both macro and micro benchmarks. 

Macro benchmarks are like this one: compile a group of files repeatedly and measure performance (hot + cold). We want to be able to run this against a different Scala versions easily. This would suggest that we use a small API surface area, as in the benchmark above.

We can also have a mode to automate collection of profiling data (flight recorder, perfasm, or vtune).

Micro benchmarks might test subtyping, or parsing, etc individually. These are likely to be more coupled to compiler internals, so will be harder to run retrospectively on old compiler versions.

**Comment by retronym** [comment]
After some discussions with @christhalinger, I've been looking at the effect of deoptimizations in hot methods and into comparisions between C2 and Graal.

We focussed attention on `itransform`, the base logic for all tree transformers. This contains a big pattern match, and some cases will be false 100% of the time in early phases of the compiler (e.g `case _: ArrayValue`). A theory is that this style of code is hostile to JIT, if a new case "comes live" after C2 has run, things have to go back the interpreter and start again. By contrast, a megamorphic callsite doesn't change shape when it goes from N to N+1 active receivers for N>3.

I wasn't able to demonstrate this in a small microbenchmark yet. We might need to simulate other load on the JIT compiler to have a realistic cost for deoptimizations.

I did look at the [trace of deoptimizations](https://gist.github.com/retronym/f59ad507f7cdfd333abd57db90dec102), as logged with `-XX:+TraceDeoptimization`.  The workload was compiling the standard library from a cold start. It took 34 seconds, and there were ~35 deopts in `itransform`.

Overall, I saw 70 deopts/second.  I don't have an intuition about whether that's a problem in and of itself. I guess the cost depends on how much time you spend interpreting or running sub-optimal C1 code in hot methods + the opportunity cost of the JIT compilers time.

I then repeated this with Graam. It also too 34s to compile, but had fewer (10) deopts for that method.

I was a bit disappointed not to see a speedup from Graal. But I remember hearing that it is currently weakest from cold start, so I also run another test (building scala/scala) with a hot JVM.

```
% (for in in {1..5}; do printf ";clean;update\ncompile\n"; done) | sbt
...
[success] Total time: 152 s, completed 12/08/2016 2:55:11 PM
% (for in in {1..5}; do printf ";clean;update\ncompile\n"; done) | useGraal sbt
...
[success] Total time: 125 s, completed 12/08/2016 2:55:11 PM
```

This seems to reproduce the 20% improvement reported in the Graal team for Scala workloads, which is quite encouraging.

So lots of fodder for further investigation. Much of this will have to wait until we've got 2.12.0 ready to roll, but I look forward to picking this up again.

**Comment by retronym** [comment]
For Graal, I used [labsjdk-8u92-jvmci-0.18-darwin-amd64.tar.gz](http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html) and a local build of Graal ([Instructions](https://wiki.openjdk.java.net/display/Graal/Instructions)), and 

``` bash
function useGraal() {
  JAVA_HOME=/Library/Java/JavaVirtualMachines/labsjdk1.8.0_92-jvmci-0.18/ \
  JAVA_OPTS="$JAVA_OPTS -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -d64 -Djvmci.class.path.append=/Users/jason/code/graal/graal-core/mxbuild/dists/graal.jar -Xbootclasspath/a:/Users/jason/code/graal/truffle/mxbuild/dists/truffle-api.jar -Djvmci.Compiler=graal -XX:+UseJVMCICompiler" \
  PATH=$JAVA_HOME/bin:$PATH "$@"
}
```

**Comment by christhalinger** [comment]
Using Graal adds a lot of compilations (in the thousands) into the mix in the first 10-20s; it has to bootstrap itself.  I still don't fully understand `itransform` and why the callsites have to be megamorphic?  Are there a lot of node subclasses?

**Comment by retronym** [comment]
Here's a log of the number and frequency of `Tree` subclasses throughout a compilation run.

https://gist.github.com/retronym/a511bd6f99bea0396c599eeb2fb2886f

Just after the parser:

```
#retained tree nodes by type  : Ident: 88902, Select: 32302, : 25208, Apply: 22852, ValDef: 15648, AppliedTypeTree: 12084, DefDef: 11304, Literal: 11085, TypeTree: 8659, Block: 5425, TypeDef: 5354, TypeBoundsTree: 5219, New: 3296, If: 2798, Template: 1991, This: 1927, CaseDef: 1830, Bind: 1610, ClassDef: 1512, Assign: 1444, : 1416, TypeApply: 1327, PackageDef: 1175, Import: 857, Function: 797, Match: 631, LabelDef: 461, Typed: 448, ModuleDef: 384, Throw: 299, Super: 285, ExistentialTypeTree: 273, SingletonTypeTree: 223, Return: 176, Annotated: 159, AssignOrNamedArg: 96, CompoundTypeTree: 95, Try: 74, Alternative: 11, SelectFromTypeTree: 5
```

Just before code generation. Notice that many node types have been eliminated (e.g. `Import`), and a few new ones have appeared (e.g. `ArrayValue`)

```
#retained tree nodes by type  : Select: 82891, TypeTree: 70660, Apply: 66868, Ident: 56366, This: 35051, ValDef: 29886, : 26720, DefDef: 26088, Literal: 13602, Block: 9853, If: 5078, Super: 4884, TypeApply: 4412, Assign: 4121, New: 3939, LabelDef: 3363, ClassDef: 2305, Template: 2305, Typed: 1597, PackageDef: 1175, Throw: 1016, ApplyToImplicitArgs: 689, CaseDef: 566, ApplyImplicitView: 562, ArrayValue: 183, Return: 170, Match: 98, Try: 88, Bind: 58, TypeDef: 1, ApplyDynamic: 1, Alternative: 1, UnApply: 0, AssignOrNamedArg: 0, Import: 0, AppliedTypeTree: 0, TypeBoundsTree: 0, ModuleDef: 0, CompoundTypeTree: 0, ExistentialTypeTree: 0, : 0, Function: 0, SingletonTypeTree: 0, Annotated: 0, SelectFromTypeTree: 0
```

**Comment by retronym** [comment]
I haven't checked the inlining logs, but I guess that Graal might inline `itransform` all the way into into the `super.transform` calls of each the `Transformer` subclass for the compiler phases, which would lead to stable type profiles.

To give you some context, here's an example of the a particular tree transformer that implements the `flatten` phase that translates nested classes.

``` scala
class Flattener extends Transformer {
    /** Buffers for lifted out classes */
    private val liftedDefs = perRunCaches.newMap[Symbol, ListBuffer[Tree]]()

    override def transform(tree: Tree): Tree = postTransform {
      tree match {
        case PackageDef(_, _) =>
          liftedDefs(tree.symbol.moduleClass) = new ListBuffer
          super.transform(tree)
        case Template(_, _, _) if tree.symbol.isDefinedInPackage =>
          liftedDefs(tree.symbol.owner) = new ListBuffer
          super.transform(tree)
        case ClassDef(_, _, _, _) if tree.symbol.isNestedClass =>
          val liftedBuffer = liftedDefs(tree.symbol.enclosingTopLevelClass.owner)
          val index = liftedBuffer.length
          liftedBuffer.insert(index, super.transform(tree))
          if (tree.symbol.sourceModule.isStaticModule)
            removeSymbolInCurrentScope(tree.symbol.sourceModule)
          EmptyTree
        case _ =>
          super.transform(tree)
      }
    }
```

``` scala
class Transformer {
    def transform(tree: Tree): Tree = itransform(this, tree)
}

```

**Comment by SethTisue** [comment]
should we close this one, as the action on compiler performance has moved elsewhere?

**Comment by SethTisue** [comment]
@retronym ping
