### ISSUE TITLE
PR validation regression: integrate-ide failing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#93]
@sschaef is working on it; see https://gitter.im/scala-ide/scala-ide?at=56ce221cdbccfd8a4fd03cd3

**Comment by dragos** [comment]
Nightlies seem to be back up... do you still see failures?

**Comment by kiritsuku** [comment]
Yes, I tested it. It needs the redirect to function correctly, which is not yet fully in place.

**Comment by dragos** [comment]
Which one? the scalariform one?

**Comment by kiritsuku** [comment]
No, equinox weaving launcher

**Comment by kiritsuku** [comment]
And it is green again: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2194/

Let's see for how long...

**Comment by SethTisue** [comment]
thank you Simon!
