### ISSUE TITLE
regression: Scala PR validation failing due to StandardCompletionTests failure in scala-integrate-ide

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#96]
for example https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2202/console :

```
Failed tests:   completeJavaType(org.scalaide.core.ui.completion.StandardCompletionTests): expected:<...java.util.ArrayList
...
[INFO] org.scala-ide.sdt.core.tests ...................... FAILURE [5:58.452s]
```

attn @sschaef @dragos

**Comment by SethTisue** [comment]
thanks @sschaef — I'll keep an eye on it and let you know if this seems to do the trick

**Comment by kiritsuku** [comment]
Still fails: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2212/console

Probably it is the best to completely disable this test if it makes such huge problems.

**Comment by kiritsuku** [comment]
It is back to live: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2220/

**Comment by SethTisue** [comment]
:sparkles:
