### ISSUE TITLE
scala-2.11.x-integrate-ide is broken since release of 2.11.8

### ISSUE THREAD

**Issue by kiritsuku** [scala/scala-dev#97]
All builds are broken after 2.11.8 has been released today. The first one is: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2244/console

I have no idea what is going on but I have to find it out.

**Comment by dragos** [comment]
What I see is that it tries to use a 2.11.9-SNAPSHOT build of Sbt:

```
 Could not find artifact com.typesafe.sbt:incremental-compiler:jar:0.13.8-on-2.11.9-805a4f3-SNAPSHOT-for-IDE-SNAPSHOT in p
```

**Comment by dragos** [comment]
Oh, wait... that's ok, it just tries to build it right afterwards. So it seems like the 2.11.9-something infers a different type in `build.sbt` for that setting expression, when building Sbt itself?

**Comment by retronym** [comment]
In the build log, I see the error as:

```
[sbt-republish:error] /home/jenkins/workspace/scala-2.11.x-integrate-ide/target/zinc/target-0.9.1/extraction/fb33cc372474a0693075e423ab3b0d0a6c75c44a/projects/59b057909d9175dbaf54445ee8265f6833e4ff8e/build.sbt:139: error: not found: value developers
[sbt-republish:error]   developers := List(
[sbt-republish:error]   ^
[sbt-republish:error] /home/jenkins/workspace/scala-2.11.x-integrate-ide/target/zinc/target-0.9.1/extraction/fb33cc372474a0693075e423ab3b0d0a6c75c44a/projects/59b057909d9175dbaf54445ee8265f6833e4ff8e/build.sbt:68: error: type mismatch;
[sbt-republish:error]  found   : Seq[sbt.Setting[_]]
[sbt-republish:error]  required: sbt.Def.Setting[_]
[sbt-republish:error]     basicAssemblySettings,
[sbt-republish:error]     ^
[sbt-republish:error] /home/jenkins/workspace/scala-2.11.x-integrate-ide/target/zinc/target-0.9.1/extraction/fb33cc372474a0693075e423ab3b0d0a6c75c44a/projects/59b057909d9175dbaf54445ee8265f6833e4ff8e/build.sbt:17: error: not found: value inThisBuild
[sbt-republish:error]     inThisBuild(Seq(
[sbt-republish:error]     ^
```

This suggests that the build for `sbt-republish` requires a more recent version of SBT that the one being used, 0.13.5.

**Comment by retronym** [comment]
> So it seems like the 2.11.9-something infers a different type in build.sbt for that setting expression, when building Sbt itself?

The `.sbt` format evolved to allowed expressions of type `Seq[Setting]` in addition to expressions of type `Setting`.

**Comment by retronym** [comment]
I'd guess the build is picking up `https://github.com/scala-ide/uber-build/blob/master/zinc/sbt-on-2.10.x.properties` rather than `https://github.com/scala-ide/uber-build/blob/master/zinc/sbt-on-2.11.x.properties`

**Comment by kiritsuku** [comment]
I managed to bring back the build locally. I'm going to upload my changes later in the day once I verified that everything works correctly.

**Comment by kiritsuku** [comment]
Build is back to normal: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/2266/

Fix in https://github.com/scala-ide/uber-build/commit/cd807cf3855007abd9c5501bbaf0be0459fc1910
